---
title: "Untitled"
author: "Erick Delgadillo"
date: "`r Sys.Date()`"
output: html_document
---

    "Taxonomic composition of the Prokaryotic  metatranscriptome (No ribosomal RNA) of the control (C) river (R) and river+P (R+P) mesocosms at 0h and 72h  after riverine additions."


```{r, include=FALSE}
# All the packages needed
# remove.packages("feather")
# library(feather)
library(readr)
library(dplyr, warn.conflicts = FALSE)
library(tidyr)
library(stringr)
# library(ggplot2)
library(edgeR)
library(kfigr)
library(knitr)
library(DT)
library(ggh4x)
library(readxl)


# library(grateful)

require(RColorBrewer); sprintf("RColorBrewer: %s", packageVersion("RColorBrewer"))
require(devtools); sprintf("devtools: %s", packageVersion("devtools"))
require(circlize); sprintf("circlize: %s", packageVersion("circlize"))
require(data.table); sprintf("data.table: %s", packageVersion("data.table"))
require(limma); sprintf("limma: %s", packageVersion("limma"))
require(edgeR); sprintf("edgeR: %s", packageVersion("edgeR"))
require(gapminder); sprintf("gapminder: %s", packageVersion("gapminder"))
require(gg.gap); sprintf("gg.gap: %s", packageVersion("gg.gap"))
require(feather); sprintf("feather: %s", packageVersion("feather"))
require(cowplot); sprintf("cowplot: %s", packageVersion("cowplot"))
require(devtools); sprintf("devtools: %s", packageVersion("devtools")) 
require(data.table); sprintf("data.table: %s", packageVersion("data.table")) 
require(purrr); sprintf("purrr: %s", packageVersion("purrr"))
require(readr); sprintf("radr: %s", packageVersion("readr")) 
require(kfigr); sprintf("kfigr: %s", packageVersion("kfigr")) 
require(knitr); sprintf("knitr: %s", packageVersion("knitr")) 
require(tidyr); sprintf("tidyr: %s", packageVersion("tidyr")) 
require(dplyr); sprintf("dplyr: %s", packageVersion("dplyr")) 
require(dtplyr); sprintf("dtplyr: %s", packageVersion("dtplyr")) 
require(viridis); sprintf("viridis: %s", packageVersion("viridis")) 
require(tibble); sprintf("tibble: %s", packageVersion("tibble")) 
require(gridExtra); sprintf("gridExtra: %s", packageVersion("gridExtra")) 
require(stringr); sprintf("stringr: %s", packageVersion("stringr")) 
require(webshot); sprintf("webshot: %s", packageVersion("webshot")) 
require(vegan); sprintf("vegan: %s", packageVersion("vegan")) 
require(plotly); sprintf("plotly: %s", packageVersion("plotly")) 
require(ggpmisc); sprintf("ggpmisc: %s", packageVersion("ggpmisc")) 
require(ggplot2); sprintf("ggplot2: %s", packageVersion("ggplot2")) 
require(ggbiplot); sprintf("ggbiplot: %s", packageVersion("ggbiplot"))
require(ComplexHeatmap); sprintf("ComplexHeatmap: %s", packageVersion("ComplexHeatmap"))
require(Hmisc); sprintf("Hmisc: %s", packageVersion("Hmisc"))
require(CoDaSeq); sprintf("CoDaSeq: %s", packageVersion("CoDaSeq"))
require(ggord); sprintf("ggord: %s", packageVersion("ggord"))
require(gg.gap); sprintf("gg.gap: %s", packageVersion("gg.gap"))
# require(RAM); sprintf("RAM: %s", packageVersion("RAM"))
require(ggthemes); sprintf("ggthemes: %s", packageVersion("ggthemes"))
require(reshape2); sprintf("reshape2: %s", packageVersion("reshape2"))
# library()
library("plotrix")
library(arrow)
# library(pnmath0)

SIGNIFICANCE = 0.05
set.seed(5555) # 5tory-5ecret-5olar-5ystem
# setwd("D:/OneDrive/Documentos/Super_ENVISION")

# Function to check the number of rows
check_row_count <- function(df, label) {
  cat(paste(label, "has", nrow(df), "rows\n"))
  return(df)
}
```

```{r, fig.height=10, fig.width=10}
# Datos ambiebntales
PB_PP <- read.csv(
  "./Environmental data/WP2_Spring_BP_PP_Mesocosmos.csv",
  sep = ",", check.names = F) %>%
  separate(sample, c ("treatment", "time"), sep = "_") %>%
  dplyr::select(-errorstandar)


Nutrients <- read.csv(
  "./Environmental data/WP2_Spring_Mesocosmos.csv",
  sep = ",", check.names = F) %>%
  separate(sample, c ("treatment", "time"), sep = "_") %>%
  # dplyr::filter(variable !="NIT") %>%
  # dplyr::filter(variable !="TDN") %>%
  # dplyr::filter(variable !="NO2") %>%
  dplyr::filter(time  %in% c ("0h", "72h")) %>%
  group_by(treatment, time,  variable) %>%
  dplyr::summarise(mean=mean(value))

# Combine both files
Environmentl_data <-rbind(Nutrients, PB_PP) %>%
  mutate(treatment = ifelse(treatment == "RP", "R+P", treatment)) %>%
  unite(sample, treatment, time, sep = "_", remove = T)%>%
  spread(variable, mean, fill = NA) 


```


```{r, cache = TRUE}
# Taxonomy annotation
taxonomy <- read_tsv("./Raw_files/INTERES Loading files NoRibo/taxonomy_classification_gtdb.tsv")%>%   
  # dplyr::rename(orf = geneid) %>%
  mutate_all(function(x) ifelse(str_detect(x, '_X'), NA, x)) %>%
  mutate_all(function(x) ifelse(str_detect(x, '_A'), NA, x)) %>%
  mutate_all(function(x) ifelse(str_detect(x, '_B'), NA, x)) %>%
  mutate_all(function(x) ifelse(str_detect(x, '_C'), NA, x)) %>%
  mutate_all(function(x) ifelse(str_detect(x, '_D'), NA, x)) %>%
  mutate_all(function(x) ifelse(str_detect(x, '_E'), NA, x)) %>%
  mutate_all(function(x) ifelse(str_detect(x, '_F'), NA, x)) %>%
  mutate_all(function(x) ifelse(str_detect(x, '_G'), NA, x)) %>%
  mutate_all(function(x) ifelse(str_detect(x, '_H'), NA, x)) %>%
  mutate_all(function(x) ifelse(str_detect(x, '_I'), NA, x)) %>%
  mutate_all(function(x) ifelse(str_detect(x, 'uncl.'), NA, x)) %>%
  mutate_all(function(x) ifelse(str_detect(x, 'Unclassified'), NA, x))


```

```{r}
# Selecionamos 
OrderInterest <- c("Rhodobacterales", 
                   "Puniceispirillales", 
                   "Rhizobiales", 
                   "Pelagibacterales",
                   "Pseudomonadales", 
                   "Enterobacterales", 
                   "Burkholderiales", 
                   "Beggiatoales", 
                   "SAR86",
                   "Flavobacteriales"
                   )

ClassInterest <- c("Alphaproteobacteria", "Gammaproteobacteria")



```


```{r}
# Vamos a renombrar las casillas con lo que queremos
Taxonomy <- taxonomy %>% # Esto significa: Si es "Alveolata" y el orden se encuentra entre los seleccionados, copialo en "Our_Taxonomy"
   # filter(Domain == 'Eukaryota')%>%
 mutate(Final_Taxonomy = case_when(
                                  Phylum == "Archaea"  ~ paste0(Phylum),
                                  Phylum == "Actinobacteriota"  ~ paste0(Phylum),
                                  Phylum == "Spirochaetes" ~ paste0(Phylum),
                                  Phylum == "Firmicutes"  ~ paste0(Phylum),
                                  Phylum == "Cyanobacteria"  ~ paste0(Phylum),
                                  Phylum == "Planctomycetota"  ~ paste0(Phylum), 
                                  
                                  
                                  
                                  
                                  Class == "Alphaproteobacteria" & Order %in% OrderInterest ~ paste0(Order), 
                                  Class == "Alphaproteobacteria" & !Order %in% OrderInterest ~ paste0(Class), 
                                  Class == "Gammaproteobacteria" & Order %in% OrderInterest ~ paste0(Order), 
                                  Class == "Gammaproteobacteria" & !Order %in% OrderInterest ~ paste0(Class), 
                                  Phylum == "Bacteroidota" & Order %in% OrderInterest ~ paste0(Order), 
                                  Phylum == "Bacteroidota" & !Order %in% OrderInterest ~ paste0(Phylum), 

                                  
                                  
                                  
                                  Phylum == "Proteobacteria" & !Class %in% ClassInterest ~ paste0(Phylum)
                                  ))%>%
  

 mutate(Final_Taxonomy = ifelse(Final_Taxonomy == "NA", paste0(Phylum), Final_Taxonomy)) %>%
  
 mutate(Final_Taxonomy = ifelse(Final_Taxonomy == "NA", paste0(Domain), Final_Taxonomy))%>%
  
 mutate(Final_Taxonomy = case_when(is.na(Final_Taxonomy) ~ paste0(Domain), !is.na(Final_Taxonomy) ~ Final_Taxonomy)) 


```



```{r, cache = TRUE}
# Correspondence of sample names D:/OneDrive/Obsidian/Brain/Brain/Molecular Biology/
samples_tags <- read.csv("./Raw_files/INTERES Loading files NoRibo/INTERES_Prok_samples_tags.csv", sep = ",") %>%
  dplyr::select(sample, Sample, T1, experiment) %>%
  unite(sample, sample, T1, sep = "_", remove = T)%>%
  separate(Sample, c("Workpackage", "experiment", "treatment", "time", "replic"), sep="_", remove=F)

```



```{r, cache = TRUE}
# Functional annotation 
all_samples_emapper_annotations <- as.data.frame(fread("./Raw_files/INTERES Loading files NoRibo/all_samples_emapper_annotations.tsv"))

all_samples_emapper_annotations <- rename(all_samples_emapper_annotations,c("#query" = "orf")) 

Prok_annotations <- all_samples_emapper_annotations%>%
  dplyr::select(orf, KEGG_ko, KEGG_Module, PFAMs) %>% # 7,619,830
  separate(KEGG_ko, c("KEGG_ko", "KEGG_ko2", "KEGG_ko3"), sep=",", remove=T) %>%
    mutate(KEGG_ko = str_remove(KEGG_ko, 'ko:'))%>%
    mutate(KEGG_ko2 = str_remove(KEGG_ko2, 'ko:'))%>%
    mutate(KEGG_ko3 = str_remove(KEGG_ko3, 'ko:'))%>%
  separate(KEGG_Module, c("KEGG_Module", "Module_2", "Module_3"), sep=",", remove=T)%>%
  dplyr::select(orf, KEGG_ko, KEGG_ko2, KEGG_ko3, KEGG_Module, PFAMs)

```


```{r, fig.height=7, fig.width=7}
counts_raw <- read_tsv(
  './Raw_files/INTERES Loading files NoRibo/counts.tsv.gz', 
  col_types = cols(
    orf = col_character(),
    Chr = col_character(),
    Strand = col_character(),
    Start = col_integer(),
    End = col_integer(),
    Length = col_integer(),
    # sample = col_integer(),
    count = col_integer(),
    tpm = col_double())) %>%
  # dplyr::rename(orf = orf) %>%
  mutate(orf = str_remove(orf, 'cds.')) %>%
  # Join in with eukaryotes from the taxonomy table to subset
  join(Taxonomy, by = 'orf')%>%
  group_by(sample, Domain) %>%
  dplyr::summarize(tpm=sum(tpm)) 


counts_raw_1 <- counts_raw%>%
  ungroup()%>%
  left_join(samples_tags, by = "sample") %>% # 
 mutate(Domain = case_when(is.na(Domain)~ "No domain", !is.na(Domain) ~ Domain)) 


```


```{r}
counts_raw_for_table <- read_tsv(
  './Raw_files/INTERES Loading files NoRibo/counts.tsv.gz', 
  col_types = cols(
    orf = col_character(),
    Chr = col_character(),
    Strand = col_character(),
    Start = col_integer(),
    End = col_integer(),
    Length = col_integer(),
    # sample = col_integer(),
    count = col_integer(),
    tpm = col_double())) %>%
  # dplyr::rename(orf = orf) %>%
  mutate(orf = str_remove(orf, 'cds.')) %>%
  # Join in with eukaryotes from the taxonomy table to subset
  join(Taxonomy, by = 'orf')%>%
  group_by(sample, Domain) %>%
  dplyr::summarize(count=sum(count)) %>%
  left_join(samples_tags, by = "sample")  %>% # 
 mutate(Domain = case_when(is.na(Domain)~ "No domain", !is.na(Domain) ~ Domain))
```


```{r, fig.height=7, fig.width=7}
counts_for_table <- counts_raw_for_table %>%
  filter(
    Workpackage == "WP2",
    replic == "R3",
    treatment == "R+P",
    time == "72h"
  ) %>%
  group_by(treatment, time, replic, Domain) %>%
  # dplyr::summarize(count = sum(count) / 1e6) %>%
  dplyr::summarize(count = sum(count)) %>%
  ungroup()
```


```{r, fig.height=7, fig.width=7}
my.colors_Prokaryotes <- c("Bacteria" = "purple2", "Archaea"  = "darkorange2","No domain"  = "grey33")


MetaTs_compleat_datasetr_plot <- ggplot(counts_for_table, aes(y=count, x=treatment, fill=Domain)) + # fill=Our_Taxonomy
    geom_bar(position="fill", stat="identity") + #, color ="black"
  # geom_text(aes(label = Final_Taxonomy), position = position_fill(vjust = 0.5)) + # Agregar esta línea
  ggtitle ("Taxonomic assignment of the\nprocariotic metatranscriptome")+
    labs(x="", y="", fill="", col="") +
    theme_bw(base_size = 8) +
  theme(plot.title = element_text(size = 10, face = "bold", hjust = 0.5),
        plot.subtitle  = element_text(size = 8, hjust = 0), 
        plot.caption = element_text(size = 8, hjust = 0, vjust = 0),
        axis.title.y = element_blank(),
        axis.title.x = element_text(angle = 0, vjust = 0.5, face = "bold"),
        axis.text.x = element_text(angle = 0, vjust = 0.5, hjust = 0.5, size=8, face = "bold"),
        axis.text.y = element_text(angle = 0, vjust = 0.5, hjust = 0.5, size=8, face = "bold"),
        strip.text = element_text(size = 8), 
        strip.text.x = element_text(size=8, angle=0, face = "bold"),
        strip.text.y = element_text(size=8, angle=270, face = "bold"),
        strip.background = element_rect(colour="black", fill="white"),
        legend.text = element_text(size = 9), # Incrementar el tamaño del texto de la leyenda
        legend.position = "none",
        legend.box = "horizontal",
        legend.margin = margin(t = -1, r = 0, b = 0, l = 0, unit = "cm"),
        legend.box.margin = margin(t = 0, r = 0, b = 0, l = 0, unit = "cm"),
        legend.spacing = unit(0.05, "cm"),
    legend.key.size = unit(0.2, "cm"),  # Ajuste general del tamaño del recuadro
    legend.key.height = unit(0.2, "cm"),  # Ajuste del tamaño de altura del recuadro
    legend.key.width = unit(0.3, "cm"), 
        legend.title = element_blank()) +
      guides(fill = guide_legend(nrow = 41)) +
      scale_fill_manual(values = my.colors_Prokaryotes) +
scale_y_continuous(breaks = seq(0, 1, 0.02), labels = scales::percent)+
facet_nested( ~ time, scales = "free")+
  theme(panel.spacing = unit(0.2, "lines"))

MetaTs_compleat_datasetr_plot
```


```{r, fig.height=7, fig.width=7}
my.colors_Prokaryotes <- c("Bacteria" = "purple2", "Archaea"  = "darkorange2","No domain"  = "grey33")


MetaTs_compleat_datasetr_plot <- ggplot(counts_raw_1, aes(y=tpm, x=treatment, fill=Domain)) + # fill=Our_Taxonomy
    geom_bar(position="fill", stat="identity") + #, color ="black"
  # geom_text(aes(label = Final_Taxonomy), position = position_fill(vjust = 0.5)) + # Agregar esta línea
  ggtitle ("Taxonomic assignment of the\nprocariotic metatranscriptome")+
    labs(x="", y="", fill="", col="") +
    theme_bw(base_size = 8) +
  theme(plot.title = element_text(size = 10, face = "bold", hjust = 0.5),
        plot.subtitle  = element_text(size = 8, hjust = 0), 
        plot.caption = element_text(size = 8, hjust = 0, vjust = 0),
        axis.title.y = element_blank(),
        axis.title.x = element_text(angle = 0, vjust = 0.5, face = "bold"),
        axis.text.x = element_text(angle = 0, vjust = 0.5, hjust = 0.5, size=8, face = "bold"),
        axis.text.y = element_text(angle = 0, vjust = 0.5, hjust = 0.5, size=8, face = "bold"),
        strip.text = element_text(size = 8), 
        strip.text.x = element_text(size=8, angle=0, face = "bold"),
        strip.text.y = element_text(size=8, angle=270, face = "bold"),
        strip.background = element_rect(colour="black", fill="white"),
        legend.text = element_text(size = 9), # Incrementar el tamaño del texto de la leyenda
        legend.position = "none",
        legend.box = "horizontal",
        legend.margin = margin(t = -1, r = 0, b = 0, l = 0, unit = "cm"),
        legend.box.margin = margin(t = 0, r = 0, b = 0, l = 0, unit = "cm"),
        legend.spacing = unit(0.05, "cm"),
    legend.key.size = unit(0.2, "cm"),  # Ajuste general del tamaño del recuadro
    legend.key.height = unit(0.2, "cm"),  # Ajuste del tamaño de altura del recuadro
    legend.key.width = unit(0.3, "cm"), 
        legend.title = element_blank()) +
      guides(fill = guide_legend(nrow = 41)) +
      scale_fill_manual(values = my.colors_Prokaryotes) +
scale_y_continuous(breaks = seq(0, 1, 0.02), labels = scales::percent)+
facet_nested( ~ time, scales = "free")+
  theme(panel.spacing = unit(0.2, "lines"))

MetaTs_compleat_datasetr_plot


# ggsave("../Results/WP1/Supplementary/Supplementary_Figure_1.png",
#        width = 18, # anchura
#        height = 18, # altura
#        units = "cm",
#        dpi = 600)

```




```{r,}
counts_raw <- read_tsv(
  './Raw_files/INTERES Loading files NoRibo/counts.tsv.gz', 
  col_types = cols(
    orf = col_character(),
    Chr = col_character(),
    Strand = col_character(),
    Start = col_integer(),
    End = col_integer(),
    Length = col_integer(),
    # sample = col_integer(),
    count = col_integer(),
    tpm = col_double())) %>%
  # dplyr::rename(orf = orf) %>%
  mutate(orf = str_remove(orf, 'cds.')) %>%
  # Join in with eukaryotes from the taxonomy table to subset
  semi_join(Taxonomy %>%
              filter(Domain != 'Eukaryota'), by = 'orf')



#  Correccion de TPMs 
# Suma total de cunts por muestra despues de filtrar los ORFs de bacterias.
Total_counts_per_sample <- counts_raw %>%
  group_by(sample) %>%
  dplyr::summarize(Total_count=sum(count)) %>%
  ungroup()

# Unimos a suma anterior 
INTERES_Prok_counts_and_TPMs_raw <- counts_raw %>%
    join(Total_counts_per_sample, by = 'sample') %>% #3,465,738 entries
  dplyr::select(-tpm) %>%
      group_by(sample, orf) %>%
      mutate(tpm = (count/ Total_count) *1000000) 

INTERES_Prok_counts_and_TPMs_raw <- check_row_count(INTERES_Prok_counts_and_TPMs_raw, "Original")
   
```


```{r}
# The latest version of the protein profile list (15/05/2023) 
Hiper_proteins <- read_excel("./Protein_profiles_2024.xlsx", sheet = "Protein profiles",  col_names = TRUE) %>% #range = "A1:D10",
  dplyr::select(Category,	Subcategory,	SubcategoryP, name,	gene_protein,	KEGG_ko, kingdom) %>% 
  filter(KEGG_ko != "NA")
```


```{r,}
suppressWarnings({
# Original data

# Perform left_joins and check row counts
INTERES_Prok_counts_and_TPMs_Annotated <- INTERES_Prok_counts_and_TPMs_raw %>%
  left_join(Taxonomy, by = "orf") %>%
  check_row_count("After 1º left_join") %>%  
  left_join(Prok_annotations, by = "orf") %>%
  check_row_count("After 2º left_join") %>%
  left_join(samples_tags, by = "sample") %>%
  check_row_count("After 3º left_join")
})
```

```{r, cache = TRUE}
INTERES_Prok_counts_and_TPMs_Annotated_KEGG_ko <- INTERES_Prok_counts_and_TPMs_Annotated %>%
  dplyr::select(Sample, Workpackage, treatment, time, replic,    # Informacion de la Muestra
                orf,count, tpm,                                  # Datos de expresion 
                KEGG_ko, KEGG_ko2, KEGG_ko3, KEGG_Module, PFAMs, # Datos de Anotacion Funcional
   Final_Taxonomy, Phylum, Class, Order, Family, Genus, Species) # Datos de Anotacion Taxonomica

```


```{r}
# Este archivo contiene los counts de Procariotas sumados por Sample (replic), orf, KEGG_ko y Final_Taxonomy. 
# Es el que usamos para los nMDS
INTERES_Prok_counts_Annotated_KEGG_ko <- INTERES_Prok_counts_and_TPMs_Annotated_KEGG_ko %>%  # 5,057,052
      dplyr::group_by(Workpackage, treatment, time, replic, 
                      orf, Final_Taxonomy, Phylum, Class, Order, Family, Genus, Species,# 
                      KEGG_ko, KEGG_ko2, KEGG_ko3, KEGG_Module, PFAMs) %>%
      dplyr::summarise(count=sum(count), nReplics=n()) %>% # Primero sumamos todo lo que es lo mismo
    ungroup()


# Filtrar COUNTS 
WP1 <- INTERES_Prok_counts_Annotated_KEGG_ko %>%
  filter(Workpackage == "WP1")
# Guardar WP1
write_parquet(WP1, "../Data Frames/WP1/INTERES_Prok_WP1_counts_Annotated_1KEGG_ko.parquet")

# Filtrar COUNTS
WP2 <- INTERES_Prok_counts_Annotated_KEGG_ko %>%
  filter(Workpackage == "WP2")
# Guardar WP2
write_parquet(WP2, "../Data Frames/WP2/INTERES_Prok_WP2_counts_Annotated_1KEGG_ko.parquet")

```


```{r}
# Este archivo contiene los TPMs de Procariotas sumados por Sample (replic), orf, KEGG_ko y Final_Taxonomy. 
# Es el que usamos para las graficas de Barras con error. 
INTERES_Prok_TPMs_Annotated_KEGG_ko <- INTERES_Prok_counts_and_TPMs_Annotated_KEGG_ko%>% 
      dplyr::group_by(Workpackage, treatment, time, replic, 
                      orf, Final_Taxonomy, Phylum, Class, Order, Family, Genus, Species, 
                      KEGG_ko, KEGG_ko2, KEGG_ko3, KEGG_Module, PFAMs) %>%
      dplyr::summarise(tpm=sum(tpm), nReplics=n()) %>% 
    ungroup()


# Filtrar TPMs 
WP1 <- INTERES_Prok_TPMs_Annotated_KEGG_ko %>%
  filter(Workpackage == "WP1")
# Guardar WP1
write_parquet(WP1, "../Data Frames/WP1/INTERES_Prok_WP1_TPMs_Annotated_1KEGG_ko.parquet")


# Filtrar TPMs 
WP2 <- INTERES_Prok_TPMs_Annotated_KEGG_ko %>%
  filter(Workpackage == "WP2")
# Guardar WP2
write_parquet(WP2, "../Data Frames/WP2/INTERES_Prok_WP2_TPMs_Annotated_1KEGG_ko.parquet") # Este es el archivc

```


```{r}
# Esta es la parte donde vamos a aprovechar todas las entradas de KEGG

# Filtrar primero por KEGG_ko presente en Hiper_proteins
filtered_KEGG_ko1 <- WP2 %>%
  filter(KEGG_ko %in% Hiper_proteins$KEGG_ko) %>%
  mutate(KEGG_ko = KEGG_ko)  # Mantener la columna KEGG_ko como está

# Filtrar por KEGG_ko2 solo si KEGG_ko no está presente en Hiper_proteins y renombrar a KEGG_ko
filtered_KEGG_ko2 <- WP2 %>%
  filter(!(KEGG_ko %in% Hiper_proteins$KEGG_ko) & KEGG_ko2 %in% Hiper_proteins$KEGG_ko) %>%
  mutate(KEGG_ko = KEGG_ko2)  # Crear una nueva columna KEGG_ko con el valor de KEGG_ko2

# Filtrar por KEGG_ko3 solo si KEGG_ko y KEGG_ko2 no están presentes en Hiper_proteins y renombrar a KEGG_ko
filtered_KEGG_ko3 <- WP2 %>%
  filter(!(KEGG_ko %in% Hiper_proteins$KEGG_ko) & 
         !(KEGG_ko2 %in% Hiper_proteins$KEGG_ko) & 
          KEGG_ko3 %in% Hiper_proteins$KEGG_ko) %>%
  mutate(KEGG_ko = KEGG_ko3)  # Crear una nueva columna KEGG_ko con el valor de KEGG_ko3

# Combinar todos los resultados y eliminar duplicados
WP2_filtered <- bind_rows(filtered_KEGG_ko1, filtered_KEGG_ko2, filtered_KEGG_ko3) %>%
  distinct()  # Eliminar cualquier fila duplicada que pudiera aparecer
```


```{r}
# Continuar con el procesamiento del dataframe WP2_filtered
WP2_Prokaryotes_1 <- WP2_filtered %>%
  left_join(Hiper_proteins, by = "KEGG_ko") %>%
  dplyr::filter(!kingdom %in% c("Eukarya")) %>%
  dplyr::select(Workpackage, treatment, time, replic, 
                tpm, gene_protein, KEGG_ko, Category, Subcategory, SubcategoryP, 
                Phylum, Class, Order, Final_Taxonomy) %>%
  group_by(Workpackage, treatment, time, replic, gene_protein, KEGG_ko, # El KEGG_ko que contiene todos los posibles KEGG_ko
           Category, Subcategory, SubcategoryP, Final_Taxonomy) %>%
  dplyr::summarise(tpm = sum(tpm)) %>%
  ungroup() 

write_parquet(WP2_Prokaryotes_1, "../Data Frames/WP2/INTERES_Prok_WP2_TPMs_Annotated_3KEGG_ko.parquet") # Es este!!
```



```{r}
# Este archivo contiene los TPMs de Procariotas sumados por Sample (mean by replic), orf, KEGG_ko y Final_Taxonomy. 
# Es el que usamos para las graficas de la proporcion en la asignacion taxonomica del transcriptoma. 
INTERES_Prok_mean_TPMs_Annotated_KEGG_ko <-  INTERES_Prok_TPMs_Annotated_KEGG_ko%>% 
      dplyr::group_by(Workpackage, treatment, time,
                      orf, Final_Taxonomy, Phylum, Class, Order, Family, Genus, Species,# 
                      KEGG_ko, KEGG_ko2, KEGG_ko3, KEGG_Module, PFAMs) %>%
  dplyr::summarize(tpm=mean(tpm), nGenes=n()) %>% # Hacemos una media de las replicas
  ungroup()

# Filtrar TPMs 
WP1 <- INTERES_Prok_mean_TPMs_Annotated_KEGG_ko %>%
  filter(Workpackage == "WP1")
# Guardar WP1
write_parquet(WP1, "../Data Frames/WP1/INTERES_Prok_WP1_TPMs_mean_Annotated_1KEGG_ko.parquet") 

# Filtrar TPMs 
WP2 <- INTERES_Prok_mean_TPMs_Annotated_KEGG_ko %>%
  filter(Workpackage == "WP2")
# Guardar WP1
write_parquet(WP2, "../Data Frames/WP2/INTERES_Prok_WP2_TPMs_mean_Annotated_1KEGG_ko.parquet") 


# INTERES_Prok_mean_TPMs_Annotated_KEGG_ko No lo usamos por ahora pero!
# WP2 si para calcular la proporcion del transcriptoma.
# Proporcion Final
WP2_MetaT_Proportion_FinalTax <- WP2 %>%
      unite(sample, treatment, time, sep = "_", remove = F)%>% 
dplyr::select(sample, tpm, Phylum, Class, Order, Final_Taxonomy)%>%
    group_by(sample, Final_Taxonomy) %>%
  dplyr::summarise(Total_tpm=sum(tpm)) %>%
      ungroup()
```


```{r}
# The latest version of the protein profile list (15/05/2023) 
Hiper_proteins <- read_excel("./Protein_profiles_2024.xlsx", sheet = "Protein profiles",  col_names = TRUE) %>% #range = "A1:D10",
  dplyr::select(Category,	Subcategory,	SubcategoryP, name,	gene_protein,	KEGG_ko, kingdom) %>% 
  filter(KEGG_ko != "NA")

# Activsar para el caso de las correlasiones
Hiper_proteins <- Hiper_proteins %>% # 
  mutate(gene_protein = case_when(
    gene_protein == "pstA"  ~ "pstABCS",
    gene_protein == "pstB"  ~ "pstABCS",
    gene_protein == "pstC"  ~ "pstABCS",
    gene_protein == "pstS"  ~ "pstABCS",
    TRUE ~ gene_protein
  ))
```


```{r}
WP2_Prokaryotes_1 <- WP2 %>%
          unite(sample, treatment, time, sep = "_", remove = T) %>%
  left_join(Hiper_proteins, by="KEGG_ko") %>%
    filter(KEGG_ko %in% Hiper_proteins$KEGG_ko)  %>%
          dplyr::filter(!kingdom %in% c("Eukarya")) %>%
dplyr::select(sample, tpm, gene_protein, Category, Subcategory, SubcategoryP, Phylum, Class, Order, Final_Taxonomy)%>%
  group_by(sample, gene_protein, Category, Subcategory, SubcategoryP, Final_Taxonomy) %>%
  dplyr::summarise(tpm=sum(tpm)) %>%
      ungroup()   %>%
  left_join(WP2_MetaT_Proportion_FinalTax, by = c("sample", "Final_Taxonomy")) %>%
    mutate(GenRatio = tpm / Total_tpm)  %>%
  left_join(Environmentl_data, by="sample")

#############
write.csv(WP2_Prokaryotes_1, "../Data Frames/WP2/WP2_Prok_1KEGG_ko_genes.csv") # ESTE ES EL ANTIGUO

```

```{r}
# Filtrar primero por KEGG_ko presente en Hiper_proteins
filtered_KEGG_ko1 <- WP2 %>%
  filter(KEGG_ko %in% Hiper_proteins$KEGG_ko) %>%
  mutate(KEGG_ko = KEGG_ko)  # Mantener la columna KEGG_ko como está

# Filtrar por KEGG_ko2 solo si KEGG_ko no está presente en Hiper_proteins y renombrar a KEGG_ko
filtered_KEGG_ko2 <- WP2 %>%
  filter(!(KEGG_ko %in% Hiper_proteins$KEGG_ko) & KEGG_ko2 %in% Hiper_proteins$KEGG_ko) %>%
  mutate(KEGG_ko = KEGG_ko2)  # Crear una nueva columna KEGG_ko con el valor de KEGG_ko2

# Filtrar por KEGG_ko3 solo si KEGG_ko y KEGG_ko2 no están presentes en Hiper_proteins y renombrar a KEGG_ko
filtered_KEGG_ko3 <- WP2 %>%
  filter(!(KEGG_ko %in% Hiper_proteins$KEGG_ko) & 
         !(KEGG_ko2 %in% Hiper_proteins$KEGG_ko) & 
          KEGG_ko3 %in% Hiper_proteins$KEGG_ko) %>%
  mutate(KEGG_ko = KEGG_ko3)  # Crear una nueva columna KEGG_ko con el valor de KEGG_ko3

# Combinar todos los resultados y eliminar duplicados
WP2_filtered <- bind_rows(filtered_KEGG_ko1, filtered_KEGG_ko2, filtered_KEGG_ko3) %>%
  distinct()  # Eliminar cualquier fila duplicada que pudiera aparecer
```


```{r}
# Continuar con el procesamiento del dataframe WP2_filtered
WP2_Prokaryotes_1 <- WP2_filtered %>%
  unite(sample, treatment, time, sep = "_", remove = TRUE) %>% 
  left_join(Hiper_proteins, by = "KEGG_ko") %>%
  # Filtrar para eliminar valores de Eukarya
  dplyr::filter(!kingdom %in% c("Eukarya")) %>%
  # Seleccionar las columnas de interés
  dplyr::select(sample, tpm, gene_protein, Category, Subcategory, SubcategoryP, Phylum, Class, Order, Final_Taxonomy) %>%
  # Agrupar por las columnas de interés y sumar TPM
  group_by(sample, gene_protein, Category, Subcategory, SubcategoryP, Final_Taxonomy) %>%
  dplyr::summarise(tpm = sum(tpm)) %>%
  ungroup() %>%
  # Unir con otras tablas y calcular el GenRatio
  left_join(WP2_MetaT_Proportion_FinalTax, by = c("sample", "Final_Taxonomy")) %>%
  mutate(GenRatio = tpm / Total_tpm) %>%
  # Unir con los datos ambientales
  left_join(Environmentl_data, by = "sample")


write.csv(WP2_Prokaryotes_1, "../Data Frames/WP2/WP2_Prok_3KEGG_ko_genes.csv") # ESTE ES ELM QUE TIENE QUE TENER EL RESULTADO ESPERADO


```



```{r, include=FALSE, cache = TRUE}
samples_tags <- read.csv("./Raw_files/INTERES Loading files NoRibo/INTERES_Prok_samples_tags.csv", sep = ",") %>%
  dplyr::select(sample, Sample, group, date) %>%
  separate(Sample, c("Workpackage", "experiment", "treatment", "time", "replic"), sep="_", remove=F)

# COG_categories <- read.csv("D:/OneDrive/Obsidian/Brain/Neural Networks/Prefrontal Cortex (Projects)/UVigo/INTERES/Calculations/COG_categories.csv", sep = ";")

```




```{r read-data}
counts <- read_tsv(
  './Raw_files/INTERES Loading files NoRibo/counts.tsv.gz',
  col_types = cols(
    orf = col_character(),
    Chr = col_character(),
    Strand = col_character(),
    Start = col_integer(),
    End = col_integer(),
    Length = col_integer(), 
    # sample = col_integer(),
    count = col_integer(),
    tpm = col_double())) %>%
  dplyr::rename(orf = orf) %>%
  # mutate(orf = str_remove(orf, 'cds.'), sample = sprintf("s%02d", sample)) %>%
  # Join in with eukaryotes from the taxonomy table to subset
  semi_join(Taxonomy %>%
              filter(Domain != 'Eukaryota'), by = 'orf') %>%
    separate(sample, c("sample", "??"), sep="_", remove=T)

# samples <- read_tsv('samples.tsv', show_col_types = FALSE)
samples <- samples_tags

eggnogs <- Prok_annotations

```


```{r create-dgelist}
# In this chunk I create the DGEList object, i.e. the fundamental data type in EdgeR that contains
# the counts matrix as well as, in our case, sample information.
dgelist <- counts %>%
  # Convert the long table into a wide, using only orf, sample and count
  dplyr::select(orf, sample, count) %>%
  arrange(sample, orf) %>%
  pivot_wider(names_from = sample, values_from = count, values_fill = 0) %>% 
  # Convert the orf column into rownames, to create a pure numerical matrix
  tibble::column_to_rownames('orf') %>%
  # Create the DGEList object, using the samples table as sample information
  DGEList(samples = samples)

# Filter by the EdgeR built-in `filterByExpr()` that supposedly removes genes that are overall too low
dgelist <- dgelist[filterByExpr(dgelist), , keep.lib.sizes = FALSE]

# Calculate the recommended TMM normalization factors that adjust for different distributions of counts
# over the genes between samples.
dgelist <- calcNormFactors(dgelist)
```

```{r create-cdisp}
# In this chunk, I create a dispersion object from the DGEList object created above.

# First, a design matrix from the samples attribute.
design <- model.matrix(~0+group, data = dgelist$samples)
colnames(design) <- levels(dgelist$samples$group)

# Then the dispersion table, using the function that calculates all dispersions.
cdisp <- estimateDisp(dgelist, design)
```

```{r calc-fit-toptags}
# Here the model is fitted to the data, using the design matrix.
fit <- glmQLFit(cdisp, design)

# This part calculates a joint table with genes for selected contrasts.
# First, create an empty table with all columns we want.
toptags <- tibble(
  contrast = character(), adjust.method = character(), test = character(), orf = character(),
  logFC = double(), logCPM = double(), F = double(), PValue = double(), FDR = double()
)
# Then loop over the contrasts we want, do the test, extract top tags (all genes) and make a
# table to add to the growing table.
for ( c in list(   # wp1       |     wp2  
                #  C0  C1  C0  C1  R0  R1  RP0 RP1
              # c( 1, -1,   0,  0,  0,  0,   0,  0 ), # WP1 CT0 VS CT1
              # c( 0,  0,   1, -1,  0,  0,   0,  0 ), # wp2 CT0 VS CT1
              
                c( 0,  0,   -1,  0,  1,  0,   0,  0 ), # WP2 CT0 VS RT0
                c( 0,  0,   -1,  0,  0,  0,   1,  0 ), # WP2 CT0 VS RPO
                c( 0,  0,   0,  0,  -1,  0,  1,  0 ), # WP2 RT0 VS RPO
              
                c( 0,  0,   0,  -1,  0, 1,   0,  0 ), # WP2 CT1 VS RT1
                c( 0,  0,   0,  -1,  0,  0,   0,  1 ), # WP2 CT1 VS RP1
                c( 0,  0,   0,  0,  0,  -1,   0, 1 ) # WP2 RT1 VS RP1

)
      ) {
  test <- glmQLFTest(fit, contrast = c)
  tt   <- topTags(test, n = Inf, adjust.method = 'fdr')
  toptags <- toptags %>%
    union(
      tt$table %>%
        tibble::rownames_to_column('orf') %>%
        mutate(contrast = tt$comparison, adjust.method = tt$adjust.method, test = tt$test)
    )
}
```



```{r toptags-significant, cache = FALSE}
toptags %>%
  filter(FDR <= SIGNIFICANCE) %>%
  left_join(eggnogs, by = 'orf') %>%
  transmute(contrast,  orf, KEGG_Module, PFAMs, logFC = round(logFC, 2), logCPM = round(logCPM, 2), FDR = round(FDR, 2)) %>%
  arrange(contrast, logFC) 

labels <- toptags %>%
  dplyr::select(contrast)

labels <- (unique(labels))

Experiment <- c("WP2", "WP2", "WP2", "WP2", "WP2", "WP2")
comparation <- c(" C  vs R-0h",
                 "C vs R+P-0h",
                 "R vs R+P-0h",
                 " C  vs R-72h",
                 "C vs R+P-72h",
                 "R vs R+P-72h") 




dge_labels <- cbind(labels, Experiment)
dge_labels <- cbind(dge_labels, comparation) #POR AQUI ESTA EL ERROR, ESTAS DUPLICANDO VALORES POR 6 (TODOS LOS TRATAMIENTOS). Checale!
```



```{r toptags-volcano, fig.width = 10, fig.height = 6, fig.cap = '**EdgeR estimated logFC and logCPM.**', cache = FALSE}

toptags$transparency <- ifelse(toptags$PValue <= 0.05 & # More than 0.05p (No significant)
                               toptags$logFC >= -1 & # Between 0 and -1.9 of logFC
                               toptags$logFC <= 1, # And under 1.9 of logFC
                               0.1, # Set as 10% of the alpha (90% transparency)
                        ifelse(toptags$PValue >= 0.05 & # Less than 0.05p (Significant)
                               (toptags$logFC <= 1 | # More than 1.9 of logFC
                               toptags$logFC >= -1), # And above -1.9 of logFC
                               0.1,1)) # Set as 100% of the alpha (0% transparency)



toptags %>%
  mutate(significant = ifelse(FDR <= 0.05, TRUE, FALSE)) %>%
  ggplot(aes(x = logCPM, y = logFC, colour = FDR, shape = significant)) +
  geom_point(alpha = toptags$transparency) +
  scale_colour_viridis_c('FDR') +
  facet_wrap(~contrast, ncol = 3) +
  theme(legend.position = 'top' ) +
        labs(caption = str_wrap(
    "Volcano plot. ", 75)) 

ggsave("../Results/WP2/Supplementary/Prokaryotes_DGE_VolcanoPlot.png",
       width = 18, # anchura
       height = 18, # altura
       units = "cm",
       dpi = 600)

```





```{r}
# Original data
toptags <- check_row_count(toptags, "Original")

DGE_INTERES_WP2 <- toptags %>%  # We keep the same  1,040,758 entries and 38 total columns7
  left_join(Taxonomy, by="orf") %>%
    check_row_count("After 1º left_join") %>%
  left_join(dge_labels, by= "contrast")  %>%
      check_row_count("After 2º left_join")%>%
  left_join(eggnogs, by = 'orf') %>%
  check_row_count("After 3º left_join")


write_parquet(DGE_INTERES_WP2, "../Data Frames/WP2/INTERES_Prok_WP2_DGE.parquet")
```
















```{r calc-fit-toptags}
# Here the model is fitted to the data, using the design matrix.
fit <- glmQLFit(cdisp, design)

# This part calculates a joint table with genes for selected contrasts.
# First, create an empty table with all columns we want.
toptags <- tibble(
  contrast = character(), adjust.method = character(), test = character(), orf = character(),
  logFC = double(), logCPM = double(), F = double(), PValue = double(), FDR = double()
)
# Then loop over the contrasts we want, do the test, extract top tags (all genes) and make a
# table to add to the growing table.
for ( c in list(   # wp1       |     wp2  
             #  C0  C1  C0  C1  R0  R1  RP0 RP1
              c( -1, 1,   0,  0,  0,  0,   0,  0 ) # WP1 CT0 VS CT1
              # c( 0,  0,   1, -1,  0,  0,   0,  0 ) # wp2 CT0 VS CT1
              
                # c( 0,  0,   1,  0,- 1,  0,   0,  0 ), # WP2 CT0 VS RT0
                # c( 0,  0,   1,  0,  0,  0,  -1,  0 ), # WP2 CT0 VS RPO
                # c( 0,  0,   0,  0,  1,  0,  -1,  0 ), # WP2 RT0 VS RPO
                # 
                # c( 0,  0,   0,  1,  0, -1,   0,  0 ), # WP2 CT1 VS RT1
                # c( 0,  0,   0,  1,  0,  0,   0, -1 ), # WP2 CT1 VS RP1
                # c( 0,  0,   0,  0,  0,  1,   0, -1 ) # WP2 RT1 VS RP1

)
      ) {
  test <- glmQLFTest(fit, contrast = c)
  tt   <- topTags(test, n = Inf, adjust.method = 'fdr')
  toptags <- toptags %>%
    union(
      tt$table %>%
        tibble::rownames_to_column('orf') %>%
        mutate(contrast = tt$comparison, adjust.method = tt$adjust.method, test = tt$test)
    )
}
```





```{r toptags-significant, cache = FALSE}
toptags %>%
  filter(FDR <= SIGNIFICANCE) %>%
  left_join(eggnogs, by = 'orf') %>%
  transmute(contrast,  orf, KEGG_Module, PFAMs, logFC = round(logFC, 2), logCPM = round(logCPM, 2), FDR = round(FDR, 2)) %>%
  arrange(contrast, logFC) #%>%
  # datatable(rownames = FALSE)
# write.csv(toptags, "toptags.csv")
# write_parquet(toptags, "toptags_DEG_INTERES_polyA.parquet")

labels <- toptags %>%
  dplyr::select(contrast)

labels <- (unique(labels))

Experiment <- c("WP1")
comparation <- c("0h VS 72h")




dge_labels <- cbind(labels, Experiment)
dge_labels <- cbind(dge_labels, comparation)
```



```{r toptags-volcano, fig.width = 10, fig.height = 6, fig.cap = '**EdgeR estimated logFC and logCPM.**', cache = FALSE}
toptags$transparency <- ifelse(toptags$PValue <= 0.05 & # More than 0.05p (No significant)
                               toptags$logFC >= -1 & # Between 0 and -1.9 of logFC
                               toptags$logFC <= 1, # And under 1.9 of logFC
                               0.1, # Set as 10% of the alpha (90% transparency)
                        ifelse(toptags$PValue >= 0.05 & # Less than 0.05p (Significant)
                               (toptags$logFC <= 1 | # More than 1.9 of logFC
                               toptags$logFC >= -1), # And above -1.9 of logFC
                               0.1,1)) # Set as 100% of the alpha (0% transparency)



toptags %>%
  mutate(significant = ifelse(FDR <= 0.05, TRUE, FALSE)) %>%
  ggplot(aes(x = logCPM, y = logFC, colour = FDR, shape = significant)) +
  geom_point(alpha = toptags$transparency) +
  scale_colour_viridis_c('FDR') +
  facet_wrap(~contrast, ncol = 3) +
  theme(legend.position = 'top' ) +
        labs(caption = str_wrap(
    "Volcano plot. ", 75)) 

ggsave("../Results/WP1/Supplementary/Prokaryotes_DGE_VolcanoPlot.png",
       width = 18, # anchura
       height = 18, # altura
       units = "cm",
       dpi = 600)

```


```{r}
DGE_INTERES_WP1 <- toptags %>% 

  left_join(Taxonomy, by="orf") %>%
  left_join(dge_labels, by= "contrast")  %>%
  left_join(eggnogs, by = 'orf') 


write_parquet(DGE_INTERES_WP1, "../Data Frames/WP1/INTERES_Prok_WP1_DGE.parquet")

```


