---
title: "Untitled"
author: "Erick Delgadillo"
date: "`r Sys.Date()`"
output: html_document
---

"Taxonomic composition of the Eukaryotic metatranscriptome (poly-A mRNA) of the control (C) river (R) and river+P (R+P) mesocosms at 0h and 72h after riverine additions."

```{r, include=FALSE}
# All the packages needed
packages <- c("readr", 
              "dplyr", 
              "tidyr", 
              "stringr", 
              "ggplot2", 
              "edgeR", 
              "kfigr", 
              "knitr", 
              "DT", 
              "ggh4x", 
              "readxl", 
              "arrow", 
              "RColorBrewer", 
              "devtools", 
              "circlize", 
              "data.table", 
              "limma", 
              "gapminder", 
              "gg.gap", 
              "feather", 
              "cowplot", 
              "purrr", 
              "dtplyr", 
              "viridis", 
              "tibble", 
              "gridExtra", 
              "webshot", 
              "vegan", 
              "plotly", 
              "ggpmisc", 
              "ggbiplot", 
              "ComplexHeatmap", 
              "Hmisc", 
              "CoDaSeq", 
              "ggord", 
              "reshape2", 
              "plotrix")
for (pkg in packages) {
  if (!require(pkg, character.only = TRUE)) {
    install.packages(pkg)
    library(pkg, character.only = TRUE)
  }
}


SIGNIFICANCE = 0.05
set.seed(5555) # 5tory-5ecret-5olar-5ystem
# setwd("D:/OneDrive/Documentos/Super_ENVISION")

# Function to check the number of rows
check_row_count <- function(df, label) {
  cat(paste(label, "has", nrow(df), "rows\n"))
  return(df)
}
```


```{r, fig.height=10, fig.width=10}
# Datos ambiebntales
PB_PP <- read.csv(
  "./Environmental data/WP2_Spring_BP_PP_Mesocosmos.csv",
  sep = ",", check.names = F) %>%
  separate(sample, c ("treatment", "time"), sep = "_") %>%
  dplyr::select(-errorstandar)


Nutrients <- read.csv(
  "./Environmental data/WP2_Spring_Mesocosmos.csv",
  sep = ",", check.names = F) %>%
  separate(sample, c ("treatment", "time"), sep = "_") %>%
  # dplyr::filter(variable !="NIT") %>%
  # dplyr::filter(variable !="TDN") %>%
  # dplyr::filter(variable !="NO2") %>%
  dplyr::filter(time  %in% c ("0h", "72h")) %>%
  group_by(treatment, time,  variable) %>%
  dplyr::summarise(mean=mean(value))

# Combine both files
Environmentl_data <-rbind(Nutrients, PB_PP) %>%
  mutate(treatment = ifelse(treatment == "RP", "R+P", treatment)) %>%
  unite(sample, treatment, time, sep = "_", remove = T)%>%
  spread(variable, mean, fill = NA) 


```


```{r}

# Taxonomy annotation
taxonomy <- read_tsv("./Raw_files/INTERES Loading files PolyA/taxonomy_classification.tsv.gz") %>%   
  dplyr::rename(geneid = orf) %>%
  mutate_all(function(x) ifelse(str_detect(x, '_X'), NA, x)) %>%
  mutate_all(function(x) ifelse(str_detect(x, '_A'), NA, x)) %>%
  mutate_all(function(x) ifelse(str_detect(x, '_B'), NA, x)) %>%
  mutate_all(function(x) ifelse(str_detect(x, '_C'), NA, x)) %>%
  mutate_all(function(x) ifelse(str_detect(x, '_D'), NA, x)) %>%
  mutate_all(function(x) ifelse(str_detect(x, '_E'), NA, x)) %>%
  mutate_all(function(x) ifelse(str_detect(x, '_F'), NA, x)) %>%
  mutate_all(function(x) ifelse(str_detect(x, '_G'), NA, x)) %>%
  mutate_all(function(x) ifelse(str_detect(x, '_H'), NA, x)) %>%
  mutate_all(function(x) ifelse(str_detect(x, '_I'), NA, x)) %>%
  mutate_all(function(x) ifelse(str_detect(x, 'uncl.'), NA, x)) %>%
  mutate_all(function(x) ifelse(str_detect(x, 'Unclassified'), NA, x))

```

```{r}
# Selecionamos 
SpeciesInterest <- c("Alexandrium",
                     "Scrippsiella", 
                     "Symbiodinium",
                     "Thalassiosira", 
                     "Chaetoceros", 
                     "Skeletonema",
                     "Pseudo-nitzschia", 
                     "Dinophysiales",
                     "Micromonas", 
                     "Ostreococcus", 
                     "Mamiellales")

FamilyInterest <- c("Choreotrichida", "Tintinnida")

OrderInterest <- c("Spirotrichea")

```


```{r}
# Vamos a renombrar las casillas con lo que queremos
Taxonomy <- taxonomy %>% # Esto significa: Si es "Alveolata" y el orden se encuentra entre los seleccionados, copialo en "Our_Taxonomy"
  mutate(Final_Taxonomy = case_when(
    Phylum == "Amoebozoa"  ~ paste0(Phylum),
    Phylum == "Excavata" ~ paste0(Domain),
    Phylum == "Hacrobia"  ~ paste0(Phylum),
    Phylum == "Opisthokonta"  ~ paste0(Phylum),
    Phylum == "Rhizaria"  ~ paste0(Phylum),
    Family == "Suessiales" & Species %in% SpeciesInterest ~ paste0(Species),
    Family == "Suessiales" & !Species %in% SpeciesInterest ~ paste0(Family),
    Family == "Peridiniales" & Species %in% SpeciesInterest ~ paste0(Species),
    Family == "Peridiniales" & !Species %in% SpeciesInterest ~ paste0(Family),
    Family == "Gymnodiniales" & Species %in% SpeciesInterest ~ paste0(Species),
    Family == "Gymnodiniales" & !Species %in% SpeciesInterest ~ paste0(Family),
    Family == "Gonyaulacales" & Species %in% SpeciesInterest ~ paste0(Species),
    Family == "Gonyaulacales" & !Species %in% SpeciesInterest ~ paste0(Family),
    Family == "Prorocentrales" & Species %in% SpeciesInterest ~ paste0(Species),
    Family == "Prorocentrales" & !Species %in% SpeciesInterest ~ paste0(Family),
    Class == "Dinoflagellata" & !Species %in% SpeciesInterest ~ paste0(Order),
    Order == "Dinophyceae" & !Species %in% SpeciesInterest ~ paste0(Family),
    Family == "Choreotrichida"  ~ paste0(Family),
    Family == "Tintinnida"  ~ paste0(Family),
    Order == "Spirotrichea" & !Family %in% FamilyInterest ~ paste0(Order),
    Class == "Ciliophora" & !Order %in% OrderInterest ~ paste0(Class),
    Order == "Bacillariophyta" & Species %in% SpeciesInterest ~ paste0(Species),
    Order == "Bacillariophyta" & !Species %in% SpeciesInterest ~ paste0(Order),
    Phylum == "Stramenopiles" & Order != "Bacillariophyta" ~ paste0(Class),
    Class == "Ochrophyta" & is.na(Order) ~ paste0(Class),
    Phylum == "Stramenopiles" & is.na(Class) ~ paste0(Phylum),
    Phylum == "Archaeplastida" & Species %in% SpeciesInterest ~ paste0(Species),
    Phylum == "Archaeplastida" & !Species %in% SpeciesInterest ~ paste0(Class)
  )) %>%
  mutate(Final_Taxonomy = case_when(is.na(Final_Taxonomy) ~ paste0(Phylum), !is.na(Final_Taxonomy) ~ Final_Taxonomy)) %>%
  mutate(Final_Taxonomy = ifelse(Final_Taxonomy == "NA", paste0(Class), Final_Taxonomy)) %>%
  mutate(Final_Taxonomy = ifelse(Final_Taxonomy == "NA", paste0(Phylum), Final_Taxonomy)) %>%
  mutate(Final_Taxonomy = ifelse(Final_Taxonomy == "NA", paste0(Domain), Final_Taxonomy))

Taxonomy <- Taxonomy %>% # Esto significa: Si es "Alveolata" y el orden se encuentra entre los seleccionados, copialo en "Our_Taxonomy"
  mutate(Final_Taxonomy = case_when(
    Final_Taxonomy == "Prorocentrales"  ~ "Dinophyceae",
    Final_Taxonomy == "Pelagodinium"  ~ "Suessiaceae",
    Final_Taxonomy == "Noctilucophyceae"  ~ "Dinoflagellata",
    Final_Taxonomy == "Oxyrrhea"  ~ "Dinoflagellata",
    Final_Taxonomy == "Opalozoa"  ~ "Stramenopiles",
    Final_Taxonomy == "Archaeplastida"  ~ "Eukaryota",
    Final_Taxonomy == "Alveolata"  ~ "Eukaryota",
    Final_Taxonomy == "Ciliopora"  ~ "Eukaryota",
    TRUE ~ Final_Taxonomy
  ))

```



```{r}
# # Activsar para el caso de las correlasiones
# Taxonomy <- Taxonomy %>% # Esto significa: Si es "Alveolata" y el orden se encuentra entre los seleccionados, copialo en "Our_Taxonomy"
#   mutate(Final_Taxonomy = case_when(
#     Final_Taxonomy == "Pseudo-nitzschia"  ~ "Diatom",
#     Final_Taxonomy == "Bacillariophyta"  ~ "Diatom",
#     Final_Taxonomy == "Skeletonema"  ~ "Diatom",
#     Final_Taxonomy == "Thalassiosira"  ~ "Diatom",
#     Final_Taxonomy == "Chaetoceros"  ~ "Diatom",
#     TRUE ~ Final_Taxonomy
#   ))

```



```{r}
# Correspondence of sample names 
samples_tags <- read_csv("./Raw_files/INTERES Loading files PolyA/INTERES_Euk_samples_tags.csv", 
                         col_types = cols(sample = col_integer())) %>%
  dplyr::select(sample, Sample, group, date) %>%
  separate(Sample, c("Workpackage", "experiment", "treatment", "time", "replic"), sep = "_", remove = FALSE) %>%
  mutate(sample = as.character(sample))  # Convertir sample a character

```



```{r}
# Functional annotation
all_samples_emapper_annotations <- as.data.frame(fread("./Raw_files/INTERES Loading files PolyA/all_samples_emapper_annotations.tsv"))

all_samples_emapper_annotations <- rename(all_samples_emapper_annotations, c("#query" = "geneid")) 

Euk_annotations <- all_samples_emapper_annotations %>%
  dplyr::select(geneid, KEGG_ko, KEGG_Module, PFAMs, COG_category) %>% # Seleccionar columnas (7,619,830 genes anotados)
  separate(KEGG_ko, c("KEGG_ko", "KEGG_ko2", "KEGG_ko3"), sep = ",", remove = TRUE) %>%
    mutate(KEGG_ko = str_remove(KEGG_ko, 'ko:'))%>%
    mutate(KEGG_ko2 = str_remove(KEGG_ko2, 'ko:'))%>%
    mutate(KEGG_ko3 = str_remove(KEGG_ko3, 'ko:'))%>%
  separate(KEGG_Module, c("KEGG_Module", "Module_2", "Module_3"), sep=",", remove=T)%>%
  dplyr::select(geneid, KEGG_ko, KEGG_ko2, KEGG_ko3, KEGG_Module, PFAMs)

```


```{r}
polyA_counts_raw <- read_tsv(
  './Raw_files/INTERES Loading files PolyA/polyA_counts.tsv.gz', 
  col_types = cols(
    Geneid = col_character(), # la columna se leerá como caracteres (texto).
    Chr = col_character(), # la columna se leerá como caracteres (texto).
    Strand = col_character(), # la columna se leerá como caracteres (texto).
    Start = col_integer(), # la columna se leerá como enteros.
    End = col_integer(), # la columna se leerá como enteros.
    Length = col_integer(), # la columna se leerá como enteros.
    sample = col_integer(), # la columna se leerá como enteros.
    count = col_integer(), # la columna se leerá como enteros.
    tpm = col_double() # columna se leerá como valores decimales (números con decimales).
  )) %>%
  dplyr::rename(geneid = Geneid) %>%
  mutate(geneid = str_remove(geneid, 'cds.')) %>%
  mutate(sample = as.character(sample)) %>% # Convertir sample a character
  join(taxonomy, by = 'geneid')%>%
  group_by(sample, Domain) %>%
  dplyr::summarize(tpm=sum(tpm)) 


polyA_counts_raw_1 <- polyA_counts_raw%>%
  ungroup()%>%
  left_join(samples_tags, by = "sample") %>% # 
 mutate(Domain = case_when(is.na(Domain)~ "No domain", !is.na(Domain) ~ Domain)) %>% 
  filter(experiment != "MICR")


```








```{r}
polyA_counts_raw_for_table <- read_tsv(
  './Raw_files/INTERES Loading files PolyA/polyA_counts.tsv.gz', 
  col_types = cols(
    Geneid = col_character(), # la columna se leerá como caracteres (texto).
    Chr = col_character(), # la columna se leerá como caracteres (texto).
    Strand = col_character(), # la columna se leerá como caracteres (texto).
    Start = col_integer(), # la columna se leerá como enteros.
    End = col_integer(), # la columna se leerá como enteros.
    Length = col_integer(), # la columna se leerá como enteros.
    sample = col_integer(), # la columna se leerá como enteros.
    count = col_integer(), # la columna se leerá como enteros.
    tpm = col_double() # columna se leerá como valores decimales (números con decimales).
  )) %>%
  dplyr::rename(geneid = Geneid) %>%
  mutate(geneid = str_remove(geneid, 'cds.')) %>%
  mutate(sample = as.character(sample)) %>% # Convertir sample a character
  join(taxonomy, by = 'geneid')%>%
  group_by(sample, Domain) %>%
  dplyr::summarize(count=sum(count)) %>%
  left_join(samples_tags, by = "sample")  %>% # 
 mutate(Domain = case_when(is.na(Domain)~ "No domain", !is.na(Domain) ~ Domain))
```


```{r, fig.height=7, fig.width=7}
counts_for_table <- polyA_counts_raw_for_table %>%
  filter(
    Workpackage == "WP2",
    replic == "R3",
    treatment == "R+P",
    time == "72h"
  ) %>%
  group_by(treatment, time, replic, Domain) %>%
  # dplyr::summarize(count = sum(count) / 1e6) %>%
  dplyr::summarize(count = sum(count)) %>%
  ungroup()
```


```{r, fig.height=7, fig.width=7}
my.colors_Eukaryotes <- c("Bacteria" = "purple2", "Archaea"  = "darkorange2", "Eukaryota"  = "darkgreen",
                          "No domain"  = "grey33")

MetaTs_compleat_datasetr_plot <- ggplot(counts_for_table, aes(y=count, x=treatment, fill=Domain)) + # fill=Our_Taxonomy
    geom_bar(position="fill", stat="identity") + #, color ="black"
  # geom_text(aes(label = Final_Taxonomy), position = position_fill(vjust = 0.5)) + # Agregar esta línea
  ggtitle ("Taxonomic assignment of the\nprocariotic metatranscriptome")+
    labs(x="", y="", fill="", col="") +
    theme_bw(base_size = 8) +
  theme(plot.title = element_text(size = 10, face = "bold", hjust = 0.5),
        plot.subtitle  = element_text(size = 8, hjust = 0), 
        plot.caption = element_text(size = 8, hjust = 0, vjust = 0),
        axis.title.y = element_blank(),
        axis.title.x = element_text(angle = 0, vjust = 0.5, face = "bold"),
        axis.text.x = element_text(angle = 0, vjust = 0.5, hjust = 0.5, size=8, face = "bold"),
        axis.text.y = element_text(angle = 0, vjust = 0.5, hjust = 0.5, size=8, face = "bold"),
        strip.text = element_text(size = 8), 
        strip.text.x = element_text(size=8, angle=0, face = "bold"),
        strip.text.y = element_text(size=8, angle=270, face = "bold"),
        strip.background = element_rect(colour="black", fill="white"),
        legend.text = element_text(size = 9), # Incrementar el tamaño del texto de la leyenda
        legend.position = "none",
        legend.box = "horizontal",
        legend.margin = margin(t = -1, r = 0, b = 0, l = 0, unit = "cm"),
        legend.box.margin = margin(t = 0, r = 0, b = 0, l = 0, unit = "cm"),
        legend.spacing = unit(0.05, "cm"),
    legend.key.size = unit(0.2, "cm"),  # Ajuste general del tamaño del recuadro
    legend.key.height = unit(0.2, "cm"),  # Ajuste del tamaño de altura del recuadro
    legend.key.width = unit(0.3, "cm"), 
        legend.title = element_blank()) +
      guides(fill = guide_legend(nrow = 41)) +
      scale_fill_manual(values = my.colors_Eukaryotes) +
scale_y_continuous(breaks = seq(0, 1, 0.02), labels = scales::percent)+
facet_nested( ~ time, scales = "free")+
  theme(panel.spacing = unit(0.2, "lines"))

MetaTs_compleat_datasetr_plot
```



```{r, fig.height=7, fig.width=7}
my.colors_Eukaryotes <- c("Bacteria" = "purple2", "Archaea"  = "darkorange2", "Eukaryota"  = "darkgreen",
                          "No domain"  = "grey33")


PolyA_MetaTs_compleat_datasetr_plot <- ggplot(polyA_counts_raw_1, aes(y=tpm, x=treatment, fill=Domain)) + # fill=Our_Taxonomy
    geom_bar(position="fill", stat="identity") + #, color ="black"
  # geom_text(aes(label = Final_Taxonomy), position = position_fill(vjust = 0.5)) + # Agregar esta línea
  ggtitle ("Taxonomic assignment of the\neukariotic metatranscriptome")+
    labs(x="", y="", fill="", col="") +
    theme_bw(base_size = 8) +
  theme(plot.title = element_text(size = 10, face = "bold", hjust = 0.5),
        plot.subtitle  = element_text(size = 8, hjust = 0), 
        plot.caption = element_text(size = 8, hjust = 0, vjust = 0),
        axis.title.y = element_blank(),
        axis.title.x = element_text(angle = 0, vjust = 0.5, face = "bold"),
        axis.text.x = element_text(angle = 0, vjust = 0.5, hjust = 0.5, size=8, face = "bold"),
        axis.text.y = element_text(angle = 0, vjust = 0.5, hjust = 0.5, size=8, face = "bold"),
        strip.text = element_text(size = 8), 
        strip.text.x = element_text(size=8, angle=0, face = "bold"),
        strip.text.y = element_text(size=8, angle=270, face = "bold"),
        strip.background = element_rect(colour="black", fill="white"),
        legend.text = element_text(size = 9), # Incrementar el tamaño del texto de la leyenda
        legend.position = "right",
        legend.box = "horizontal",
        legend.margin = margin(t = -1, r = 0, b = 0, l = 0, unit = "cm"),
        legend.box.margin = margin(t = 0, r = 0, b = 0, l = 0, unit = "cm"),
        legend.spacing = unit(0.05, "cm"),
    legend.key.size = unit(0.2, "cm"),  # Ajuste general del tamaño del recuadro
    legend.key.height = unit(0.2, "cm"),  # Ajuste del tamaño de altura del recuadro
    legend.key.width = unit(0.3, "cm"), 
        legend.title = element_blank()) +
      guides(fill = guide_legend(nrow = 41)) +
        scale_fill_manual(values = my.colors_Eukaryotes) +
scale_y_continuous(breaks = seq(0, 1, 0.02), labels = scales::percent)+
  facet_nested( ~ time, scales = "free")+
  theme(panel.spacing = unit(0.2, "lines"))

PolyA_MetaTs_compleat_datasetr_plot


# ggsave("../Results/WP1/Supplementary/Supplementary_Figure_1.png",
#        width = 18, # anchura
#        height = 18, # altura
#        units = "cm",
#        dpi = 600)

```
```{r}
# 📚 Cargar la librería patchwork
library(patchwork)

# 📌 Unir las cuatro gráficas en dos columnas
combined_plot <- (MetaTs_compleat_datasetr_plot | PolyA_MetaTs_compleat_datasetr_plot)




# Guarda la imagen
png("../Results/WP1/Supplementary/Supplementary_Figure_1.png",
    width = 18, height = 24, units = 'cm', res=600 )

# Mostrar el gráfico combinado
combined_plot

# Imprime el gráfico final
print(combined_plot)

# Cierra el dispositivo de gráficos
dev.off()
combined_plot
```


```{r}
polyA_counts_raw <- read_tsv(
  './Raw_files/INTERES Loading files PolyA/polyA_counts.tsv.gz', 
  col_types = cols(
    Geneid = col_character(), # la columna se leerá como caracteres (texto).
    Chr = col_character(), # la columna se leerá como caracteres (texto).
    Strand = col_character(), # la columna se leerá como caracteres (texto).
    Start = col_integer(), # la columna se leerá como enteros.
    End = col_integer(), # la columna se leerá como enteros.
    Length = col_integer(), # la columna se leerá como enteros.
    sample = col_integer(), # la columna se leerá como enteros.
    count = col_integer(), # la columna se leerá como enteros.
    tpm = col_double() # columna se leerá como valores decimales (números con decimales).
  )) %>%
  dplyr::rename(geneid = Geneid) %>%
  mutate(geneid = str_remove(geneid, 'cds.')) %>%
  mutate(sample = as.character(sample)) %>% # Convertir sample a character
  semi_join(taxonomy %>% # Realizar una semi-join con taxonomy filtrando solo los registros con Domain igual a 'Eukaryota'
              filter(Domain == 'Eukaryota'), by = 'geneid')

# Correccion de TPMs 
# Suma total de counts por muestra despues de filtrar los ORFs de bacterias.
Total_counts_per_sample <- polyA_counts_raw %>%
  group_by(sample) %>%
  dplyr::summarize(Total_count = sum(count)) %>%
  ungroup()

# Calcular el valor de tpm dividiendo count entre Total_count y multiplicando por 1000000
INTERES_Euk_counts_and_TPMs_raw <- polyA_counts_raw %>%
  left_join(Total_counts_per_sample, by = 'sample') %>% # 3,465,738 entries
  dplyr::select(-tpm) %>%
  group_by(sample, geneid) %>%
  mutate(tpm = (count / Total_count) * 1000000) %>%
  dplyr::select(-Total_count)

INTERES_Euk_counts_and_TPMs_raw <- check_row_count(INTERES_Euk_counts_and_TPMs_raw, "Original")

```


```{r}
# The latest version of the protein profile list (15/05/2023) 
Hiper_proteins <- read_excel("./Protein_profiles_2024.xlsx", sheet = "Protein profiles",  col_names = TRUE) %>% #range = "A1:D10",
  dplyr::select(Category,	Subcategory,	SubcategoryP, name,	gene_protein,	KEGG_ko, kingdom) %>% 
  filter(KEGG_ko != "NA")
```


```{r}
suppressWarnings({
  INTERES_Euk_counts_and_TPMs_Annotated <- INTERES_Euk_counts_and_TPMs_raw %>%
    left_join(Taxonomy, by = "geneid") %>%
      check_row_count("After 1º left_join") 
})
```


```{r}
suppressWarnings({
INTERES_Euk_counts_and_TPMs_Annotated <- INTERES_Euk_counts_and_TPMs_Annotated %>%
    left_join(Euk_annotations, by = "geneid") %>%
    check_row_count("After 2º left_join") 
})
```



```{r}
library(arrow)
# Guardar los DataFrames como Parquet
write_parquet(INTERES_Euk_counts_and_TPMs_Annotated, "INTERES_Euk_counts_and_TPMs_Annotated.parquet")
write_parquet(samples_tags, "samples_tags.parquet")


# Cargar los datasets con Arrow
counts_dataset <- open_dataset("INTERES_Euk_counts_and_TPMs_Annotated.parquet")
samples_dataset <- open_dataset("samples_tags.parquet")

# Realizar el left_join
INTERES_Euk_counts_and_TPMs_Annotated <- counts_dataset %>%
  left_join(samples_dataset, by = "sample") %>%
  collect()  # Recoge el resultado final en memoria si es necesario

```



```{r, cache = TRUE}
INTERES_Euk_counts_and_TPMs_Annotated_KEGG_ko <- INTERES_Euk_counts_and_TPMs_Annotated %>%
  dplyr::select(Sample, Workpackage, treatment, time, replic,
                geneid, 
                count, tpm, 
 KEGG_ko, KEGG_ko2, KEGG_ko3, KEGG_Module, PFAMs,
                # Module_kind, # Or...
                Final_Taxonomy, 
                  Phylum, 
                   Class, 
                    Order, 
                     Family, 
                      Genus, 
                       Species)


```


```{r}
# Este archivo contiene los counts de Eucariotas sumados por Sample (replic), orf, KEGG_ko y Final_Taxonomy. 
# Es el que usamos para los nMDS
INTERES_Euk_counts_Annotated_KEGG_ko <- INTERES_Euk_counts_and_TPMs_Annotated_KEGG_ko %>%  # 5,057,052
      dplyr::group_by(Workpackage, treatment, time, replic, 
                      geneid, Final_Taxonomy, Phylum, Class, Order, Family, Genus, Species,# 
                       KEGG_ko, KEGG_ko2, KEGG_ko3, KEGG_Module, PFAMs,
                      # Module_kind, # Or...
                      ) %>%
      dplyr::summarise(count=sum(count), nReplics=n()) %>% #Primero sumamos todo lo que es lo mismo
    ungroup()

# Filtrar COUNTS 
WP1 <- INTERES_Euk_counts_Annotated_KEGG_ko %>%
  filter(Workpackage == "WP1")
# Guardar WP1
write_parquet(WP1, "../Data Frames/WP1/INTERES_Euk_WP1_counts_Annotated_1KEGG_ko.parquet")

# Filtrar COUNTS 
WP2 <- INTERES_Euk_counts_Annotated_KEGG_ko %>%
  filter(Workpackage == "WP2")
# Guardar WP2
write_parquet(WP2, "../Data Frames/WP2/INTERES_Euk_WP2_counts_Annotated_1KEGG_ko.parquet")
```


```{r}
# Este archivo contiene los TPMs de Procariotas sumados por Sample (replic), orf, KEGG_ko y Final_Taxonomy. 
# Es el que usamos para las graficas de Barras con error. 
INTERES_Euk_TPMs_Annotated_KEGG_ko <- INTERES_Euk_counts_and_TPMs_Annotated_KEGG_ko%>% 
      dplyr::group_by(Workpackage, treatment, time, replic, 
                      geneid, Final_Taxonomy, Phylum, Class, Order, Family, Genus, Species, 
                       KEGG_ko, KEGG_ko2, KEGG_ko3, KEGG_Module, PFAMs,
                      ) %>%
      dplyr::summarise(tpm=sum(tpm), nReplics=n()) %>% 
    ungroup()

# Filtrar TPMs 
WP1 <- INTERES_Euk_TPMs_Annotated_KEGG_ko %>%
  filter(Workpackage == "WP1")
# Guardar WP1
write_parquet(WP1, "../Data Frames/WP1/INTERES_Euk_WP1_TPMs_Annotated_1KEGG_ko.parquet")

# Filtrar TPMs 
WP2 <- INTERES_Euk_TPMs_Annotated_KEGG_ko %>%
  filter(Workpackage == "WP2")
# Guardar WP2
write_parquet(WP2, "../Data Frames/WP2/INTERES_Euk_WP2_TPMs_Annotated_1KEGG_ko.parquet") # Es este!!

```


```{r}
# Esta es la parte donde vamos a aprovechar todas las entradas de KEGG

# Filtrar primero por KEGG_ko presente en Hiper_proteins
filtered_KEGG_ko1 <- WP2 %>%
  filter(KEGG_ko %in% Hiper_proteins$KEGG_ko) %>%
  mutate(KEGG_ko = KEGG_ko)  # Mantener la columna KEGG_ko como está

# Filtrar por KEGG_ko2 solo si KEGG_ko no está presente en Hiper_proteins y renombrar a KEGG_ko
filtered_KEGG_ko2 <- WP2 %>%
  filter(!(KEGG_ko %in% Hiper_proteins$KEGG_ko) & KEGG_ko2 %in% Hiper_proteins$KEGG_ko) %>%
  mutate(KEGG_ko = KEGG_ko2)  # Crear una nueva columna KEGG_ko con el valor de KEGG_ko2

# Filtrar por KEGG_ko3 solo si KEGG_ko y KEGG_ko2 no están presentes en Hiper_proteins y renombrar a KEGG_ko
filtered_KEGG_ko3 <- WP2 %>%
  filter(!(KEGG_ko %in% Hiper_proteins$KEGG_ko) & 
         !(KEGG_ko2 %in% Hiper_proteins$KEGG_ko) & 
          KEGG_ko3 %in% Hiper_proteins$KEGG_ko) %>%
  mutate(KEGG_ko = KEGG_ko3)  # Crear una nueva columna KEGG_ko con el valor de KEGG_ko3

# Combinar todos los resultados y eliminar duplicados
WP2_filtered <- bind_rows(filtered_KEGG_ko1, filtered_KEGG_ko2, filtered_KEGG_ko3) %>%
  distinct()  # Eliminar cualquier fila duplicada que pudiera aparecer
```


```{r}
# Continuar con el procesamiento del dataframe WP2_filtered
WP2_Eukaryotes_1 <- WP2_filtered %>%
  left_join(Hiper_proteins, by = "KEGG_ko") %>%
  dplyr::filter(!kingdom %in% c("Bacteria", "Bacteria/Archaea", "Archaea")) %>%
  dplyr::select(Workpackage, treatment, time, replic, 
                tpm, gene_protein, KEGG_ko, Category, Subcategory, SubcategoryP, 
                Phylum, Class, Order, Final_Taxonomy) %>%
  group_by(Workpackage, treatment, time, replic, gene_protein, KEGG_ko, # El KEGG_ko que contiene todos los posibles KEGG_ko
           Category, Subcategory, SubcategoryP, Final_Taxonomy) %>%
  dplyr::summarise(tpm = sum(tpm)) %>%
  ungroup() 

write_parquet(WP2_Eukaryotes_1, "../Data Frames/WP2/INTERES_Euk_WP2_TPMs_Annotated_3KEGG_ko.parquet") # ESTE ES EL ANTIGUO

```



```{r}
# 
INTERES_Euk_mean_TPMs_Annotated_KEGG_ko <-  INTERES_Euk_TPMs_Annotated_KEGG_ko%>% 
      dplyr::group_by(Workpackage, treatment, time, replic,
                      geneid, Final_Taxonomy, Phylum, Class, Order, Family, Genus, Species,# 
                       KEGG_ko, KEGG_ko2, KEGG_ko3, KEGG_Module, PFAMs,
                      ) %>%
  dplyr::summarize(tpm=mean(tpm), nGenes=n()) %>% 
  ungroup()


```


```{r}
# Filtrar TPMs 
WP1 <- INTERES_Euk_mean_TPMs_Annotated_KEGG_ko %>%
  filter(Workpackage == "WP1")
# Guardar WP1
write_parquet(WP1, "../Data Frames/WP1/INTERES_Euk_WP1_TPMs_mean_Annotated_1KEGG_ko.parquet") # 

# Filtrar TPMs 
WP2 <- INTERES_Euk_mean_TPMs_Annotated_KEGG_ko %>%
  filter(Workpackage == "WP2")
# Guardar WP1
write_parquet(WP2, "../Data Frames/WP2/INTERES_Euk_WP2_TPMs_mean_Annotated_1KEGG_ko.parquet") # 


# INTERES_Prok_mean_TPMs_Annotated_KEGG_ko No lo usamos por ahora pero!
# WP2 si para calcular la proporcion del transcriptoma.
# Proporcion Final
WP2_MetaT_Proportion_FinalTax <- WP2 %>%
      unite(sample, treatment, time, sep = "_", remove = F)%>% 
dplyr::select(sample, tpm, Phylum, Class, Order, Final_Taxonomy)%>%
    group_by(sample, Final_Taxonomy) %>%
  dplyr::summarise(Total_tpm=sum(tpm)) %>%
      ungroup()
```

```{r}
# The latest version of the protein profile list (15/05/2023) 
Hiper_proteins <- read_excel("./Protein_profiles_2024.xlsx", sheet = "Protein profiles",  col_names = TRUE) %>% #range = "A1:D10",
  dplyr::select(Category,	Subcategory, SubcategoryP,	name,	gene_protein,	KEGG_ko, kingdom) %>% 
  filter(KEGG_ko != "NA")


# Activsar para el caso de las correlasiones
Hiper_proteins <- Hiper_proteins %>% # 
  mutate(gene_protein = case_when(
    gene_protein == "pstA"  ~ "pstABCS",
    gene_protein == "pstB"  ~ "pstABCS",
    gene_protein == "pstC"  ~ "pstABCS",
    gene_protein == "pstS"  ~ "pstABCS",
    TRUE ~ gene_protein
  ))

```

```{r}
#########
# Aqui
# Activsar para el caso de las correlasiones
# WP2 <- WP2 %>% #
#   mutate(Final_Taxonomy = case_when(
#     Final_Taxonomy == "Pseudo-nitzschia"  ~ "Diatom",
#     Final_Taxonomy == "Bacillariophyta"  ~ "Diatom",
#     Final_Taxonomy == "Skeletonema"  ~ "Diatom",
#     Final_Taxonomy == "Thalassiosira"  ~ "Diatom",
#     Final_Taxonomy == "Chaetoceros"  ~ "Diatom",
#     TRUE ~ Final_Taxonomy
#   ))


WP2_Eukaryotes_1 <- WP2 %>%
          unite(sample, treatment, time, sep = "_", remove = T) %>% 
  left_join(Hiper_proteins, by="KEGG_ko") %>%   
    filter(KEGG_ko %in% Hiper_proteins$KEGG_ko)  %>% 
  dplyr::filter(!kingdom %in% c("Bacteria", "Bacteria/Archaea", "Archaea")) %>%
dplyr::select(sample, tpm, gene_protein, Category, Subcategory, SubcategoryP, Phylum, Class, Order, Final_Taxonomy)%>%
  group_by(sample, gene_protein, Category, Subcategory, SubcategoryP, Final_Taxonomy) %>%
  dplyr::summarise(tpm=sum(tpm)) %>%
      ungroup()   %>% 
  left_join(WP2_MetaT_Proportion_FinalTax, by = c("sample", "Final_Taxonomy")) %>% 
    mutate(GenRatio = tpm / Total_tpm)  %>%
  left_join(Environmentl_data, by="sample")  

write.csv(WP2_Eukaryotes_1, "../Data Frames/WP2/WP2_Euk_1KEGG_ko_genes.csv")
write_parquet(WP2_Eukaryotes_1, "../Data Frames/WP2/WP2_Euk_1KEGG_ko_genes.parquet") # 

```



```{r}
# Filtrar primero por KEGG_ko presente en Hiper_proteins
filtered_KEGG_ko1 <- WP2 %>%
  filter(KEGG_ko %in% Hiper_proteins$KEGG_ko) %>%
  mutate(KEGG_ko = KEGG_ko)  # Mantener la columna KEGG_ko como está

# Filtrar por KEGG_ko2 solo si KEGG_ko no está presente en Hiper_proteins y renombrar a KEGG_ko
filtered_KEGG_ko2 <- WP2 %>%
  filter(!(KEGG_ko %in% Hiper_proteins$KEGG_ko) & KEGG_ko2 %in% Hiper_proteins$KEGG_ko) %>%
  mutate(KEGG_ko = KEGG_ko2)  # Crear una nueva columna KEGG_ko con el valor de KEGG_ko2

# Filtrar por KEGG_ko3 solo si KEGG_ko y KEGG_ko2 no están presentes en Hiper_proteins y renombrar a KEGG_ko
filtered_KEGG_ko3 <- WP2 %>%
  filter(!(KEGG_ko %in% Hiper_proteins$KEGG_ko) & 
         !(KEGG_ko2 %in% Hiper_proteins$KEGG_ko) & 
          KEGG_ko3 %in% Hiper_proteins$KEGG_ko) %>%
  mutate(KEGG_ko = KEGG_ko3)  # Crear una nueva columna KEGG_ko con el valor de KEGG_ko3

# Combinar todos los resultados y eliminar duplicados
WP2_filtered <- bind_rows(filtered_KEGG_ko1, filtered_KEGG_ko2, filtered_KEGG_ko3) %>%
  distinct()  # Eliminar cualquier fila duplicada que pudiera aparecer
```


```{r}
# ######### 
# # Aqui
# # Activsar para el caso de las correlasiones
# WP2_filtered <- WP2_filtered %>% #
#   mutate(Final_Taxonomy = case_when(
#     Final_Taxonomy == "Pseudo-nitzschia"  ~ "Diatom",
#     Final_Taxonomy == "Bacillariophyta"  ~ "Diatom",
#     Final_Taxonomy == "Skeletonema"  ~ "Diatom",
#     Final_Taxonomy == "Thalassiosira"  ~ "Diatom",
#     Final_Taxonomy == "Chaetoceros"  ~ "Diatom",
#     TRUE ~ Final_Taxonomy
#   ))


# Continuar con el procesamiento del dataframe WP2_filtered
WP2_Eukaryotes_1 <- WP2_filtered %>%
  unite(sample, treatment, time, sep = "_", remove = TRUE) %>% 
  left_join(Hiper_proteins, by = "KEGG_ko") %>%
  # Filtrar para eliminar valores de Eukarya
  dplyr::filter(!kingdom %in% c("Bacteria", "Bacteria/Archaea", "Archaea")) %>%
  # Seleccionar las columnas de interés
  dplyr::select(sample, tpm, gene_protein, Category, Subcategory, SubcategoryP, Phylum, Class, Order, Final_Taxonomy) %>%
  # Agrupar por las columnas de interés y sumar TPM
  group_by(sample, gene_protein, Category, Subcategory, SubcategoryP, Final_Taxonomy) %>%
  dplyr::summarise(tpm = sum(tpm)) %>%
  ungroup() %>%
  # Unir con otras tablas y calcular el GenRatio
  left_join(WP2_MetaT_Proportion_FinalTax, by = c("sample", "Final_Taxonomy")) %>%
  mutate(GenRatio = tpm / Total_tpm) %>%
  # Unir con los datos ambientales
  left_join(Environmentl_data, by = "sample")


write.csv(WP2_Eukaryotes_1, "../Data Frames/WP2/WP2_Euk_3KEGG_ko_genes.csv") 
write_parquet(WP2_Eukaryotes_1, "../Data Frames/WP2/WP2_Euk_3KEGG_ko_genes.parquet") # 

```


```{r, include=FALSE, cache = TRUE}
samples_tags <- read.csv("./Raw_files/INTERES Loading files PolyA/INTERES_Euk_samples_tags.csv", sep = ",") %>%
  dplyr::select(sample, Sample, group, date) %>%
  separate(Sample, c("Workpackage", "experiment", "treatment", "time", "replic"), sep="_", remove=F)

# COG_categories <- read.csv("D:/OneDrive/Obsidian/Brain/Neural Networks/Prefrontal Cortex (Projects)/UVigo/INTERES/Calculations/COG_categories.csv", sep = ";")

```


```{r read-data}

counts <- read_tsv(
  './Raw_files/INTERES Loading files PolyA/polyA_counts.tsv.gz',
  col_types = cols(
    Geneid = col_character(),
    Chr = col_character(),
    Strand = col_character(),
    Start = col_integer(),
    End = col_integer(),
    Length = col_integer(),
    sample = col_integer(),
    count = col_integer(),
    tpm = col_double())) %>%
  dplyr::rename(geneid = Geneid) %>%
  mutate(geneid = str_remove(geneid, 'cds.') 
                  # sample = str_remove(sample, 's'),
         # sample = sprintf("s%02d", sample)
         ) %>%
  # Join in with eukaryotes from the taxonomy table to subset
  semi_join(Taxonomy %>%
              filter(Domain == 'Eukaryota'), by = 'geneid')

# samples <- read_tsv('samples.tsv', show_col_types = FALSE)
samples <- samples_tags

eggnogs <- Euk_annotations

```



```{r create-dgelist}
# In this chunk I create the DGEList object, i.e. the fundamental data type in EdgeR that contains
# the counts matrix as well as, in our case, sample information.
dgelist <- counts %>%
  # Convert the long table into a wide, using only geneid, sample and count
  dplyr::select(geneid, sample, count) %>%
  arrange(sample, geneid) %>%
  pivot_wider(names_from = sample, values_from = count, values_fill = 0) %>%
  # Convert the geneid column into rownames, to create a pure numerical matrix
  tibble::column_to_rownames('geneid') %>%
  # Create the DGEList object, using the samples table as sample information
  DGEList(samples = samples)

# Filter by the EdgeR built-in `filterByExpr()` that supposedly removes genes that are overall too low
dgelist <- dgelist[filterByExpr(dgelist), , keep.lib.sizes = FALSE]

# Calculate the recommended TMM normalization factors that adjust for different distributions of counts
# over the genes between samples.
dgelist <- calcNormFactors(dgelist)

```

```{r create-cdisp}
# In this chunk, I create a dispersion object from the DGEList object created above.

# First, a design matrix from the samples attribute.
design <- model.matrix(~0+group, data = dgelist$samples)
colnames(design) <- levels(dgelist$samples$group)

# Then the dispersion table, using the function that calculates all dispersions.
cdisp <- estimateDisp(dgelist, design)
```



```{r calc-fit-toptags WP2}
# Here the model is fitted to the data, using the design matrix.
fit <- glmQLFit(cdisp, design)

# This part calculates a joint table with genes for selected contrasts.
# First, create an empty table with all columns we want.
toptags <- tibble(
  contrast = character(), adjust.method = character(), test = character(), geneid = character(),
  logFC = double(), logCPM = double(), F = double(), PValue = double(), FDR = double()
)
# Then loop over the contrasts we want, do the test, extract top tags (all genes) and make a
# table to add to the growing table.
for ( c in list(   # wp1        |     wp2
              # #  c0  C1  CA1  C0  C1  R0  R1  RP0 RP1
              # c( 1, -1,   0,  0,  0,  0,  0,   0,  0 ), # WP1 CT0 VS CT1
              # c( 1,  0,  -1,  0,  0,  0,  0,   0,  0 ), # WP1 CT0 vs CAT1
              # c( 0,  1,  -1,  0,  0,  0,  0,   0,  0 ) # WP1 CT1 VS CAT1

                c( 0,  0,   0,   -1,  0,  1,  0,   0,  0 ), # WP2 CT0 VS RT0
                c( 0,  0,   0,   -1,  0,  0,  0,   1,  0 ), # WP2 CT0 VS RPO
                c( 0,  0,   0,   0,  0,  -1,  0,   1,  0 ), # WP2 RT0 VS RPO

                c( 0,  0,   0,   0,  -1,  0,  1,   0,  0 ), # WP2 CT1 VS RT1
                c( 0,  0,   0,   0,  -1,  0,  0,   0,  1 ), # WP2 CT1 VS RP1
                c( 0,  0,   0,   0,  0,  0,  -1,   0,  1 ) # WP2 RT1 VS RP1


                )
      ) {
  test <- glmQLFTest(fit, contrast = c)
  tt   <- topTags(test, n = Inf, adjust.method = 'fdr')
  toptags <- toptags %>%
    union(
      tt$table %>%
        tibble::rownames_to_column('geneid') %>%
        mutate(contrast = tt$comparison, adjust.method = tt$adjust.method, test = tt$test)
    )
}
```




```{r toptags-significant WP2, cache = FALSE}
toptags %>%
  filter(FDR <= SIGNIFICANCE) %>%
  left_join(eggnogs, by = 'geneid') %>%
  transmute(contrast, geneid, KEGG_Module, PFAMs, logFC = round(logFC, 2), logCPM = round(logCPM, 2), FDR = round(FDR, 2)) %>%
  arrange(contrast, logFC) #%>%
  # datatable(rownames = FALSE)
# write.csv(toptags, "toptags.csv")
# write_parquet(toptags, "toptags_DEG_INTERES_polyA.parquet")

labels <- toptags %>%
  dplyr::select(contrast)

labels <- (unique(labels))

Experiment <- c("WP2", "WP2", "WP2", "WP2", "WP2", "WP2")
comparation <- c(" C  vs R-0h",
                 "C vs R+P-0h",
                 "R vs R+P-0h",
                 " C  vs R-72h",
                 "C vs R+P-72h",
                 "R vs R+P-72h") 



dge_labels <- cbind(labels, Experiment)
dge_labels <- cbind(dge_labels, comparation)
```



```{r toptags-volcano WP1, fig.width = 10, fig.height = 6, fig.cap = '**EdgeR estimated logFC and logCPM.**', cache = FALSE}
toptags %>%
  mutate(significant = ifelse(FDR <= 0.05, TRUE, FALSE)) %>%
  ggplot(aes(x = logCPM, y = logFC, colour = FDR, shape = significant)) +
  geom_point() +
  scale_colour_viridis_c('FDR') +
  facet_wrap(~contrast, ncol = 3) +
  theme(
    legend.position = 'bottom'
  )

ggsave("../Results/WP2/Supplementary/Eukaryotes_DGE_VolcanoPlot.png",
       width = 18, # anchura
       height = 18, # altura
       units = "cm",
       dpi = 600)

```


```{r WP2}
# Original data
toptags <- check_row_count(toptags, "Original")

DGE_INTERES_WP2 <- toptags %>%   # We keep the same  1,040,758 entries and 38 total columns7
  left_join(Taxonomy, by="geneid") %>%
    check_row_count("After 1º left_join") %>%
  left_join(dge_labels, by= "contrast") %>%
      check_row_count("After 2º left_join")%>%
  left_join(eggnogs, by = 'geneid') %>%
  check_row_count("After 3º left_join")

write_parquet(DGE_INTERES_WP2, "../Data Frames/WP2/INTERES_Euk_WP2_DGE.parquet")


```


```{r calc-fit-toptags WP1}
# Here the model is fitted to the data, using the design matrix.
fit <- glmQLFit(cdisp, design) 

# This part calculates a joint table with genes for selected contrasts.
# First, create an empty table with all columns we want.
toptags <- tibble(
  contrast = character(), adjust.method = character(), test = character(), geneid = character(),
  logFC = double(), logCPM = double(), F = double(), PValue = double(), FDR = double()
)
# Then loop over the contrasts we want, do the test, extract top tags (all genes) and make a
# table to add to the growing table.
for ( c in list(   # wp1    |     wp2
              #  c0  C1  CA1  C0  C1  R0  R1  RP0 RP1
              c( -1, 1,   0,  0,  0,  0,  0,   0,  0 ), # WP1 CT0 VS CT1
              c( -1,  0,  1,  0,  0,  0,  0,   0,  0 ), # WP1 CT0 vs CAT1
              c( 0,  -1,  1,  0,  0,  0,  0,   0,  0 ) # WP1 CT1 VS CAT1

                # c( 0,  0,   0,   1,  0,- 1,  0,   0,  0 ), # WP2 CT0 VS RT0
                # c( 0,  0,   0,   1,  0,  0,  0,  -1,  0 ), # WP2 CT0 VS RPO
                # c( 0,  0,   0,   0,  0,  1,  0,  -1,  0 ), # WP2 RT0 VS RPO
                # 
                # c( 0,  0,   0,   0,  1,  0, -1,   0,  0 ), # WP2 CT1 VS RT1
                # c( 0,  0,   0,   0,  1,  0,  0,   0, -1 ), # WP2 CT1 VS RP1
                # c( 0,  0,   0,   0,  0,  0,  1,   0, -1 ) # WP2 RT1 VS RP1


                )
      ) {
  test <- glmQLFTest(fit, contrast = c)
  tt   <- topTags(test, n = Inf, adjust.method = 'fdr')
  toptags <- toptags %>%
    union(
      tt$table %>%
        tibble::rownames_to_column('geneid') %>%
        mutate(contrast = tt$comparison, adjust.method = tt$adjust.method, test = tt$test)
    )
}
```




```{r toptags-significant, cache = FALSE}
toptags %>%
  filter(FDR <= SIGNIFICANCE) %>%
  left_join(eggnogs, by = 'geneid') %>%
  transmute(contrast, geneid, KEGG_Module, PFAMs, logFC = round(logFC, 2), logCPM = round(logCPM, 2), FDR = round(FDR, 2)) %>%
  arrange(contrast, logFC) #%>%
  # datatable(rownames = FALSE)
# write.csv(toptags, "toptags.csv")
# write_parquet(toptags, "toptags_DEG_INTERES_polyA.parquet")
```



```{r toptags-significant WP1, cache = FALSE}
labels <- toptags %>%
  dplyr::select(contrast)

labels <- (unique(labels))

Experiment <- c("WP1", "WP1", "WP1")
comparation <- c("Control-0h VS Control-72h",
                 "Control-0h VS Antibiotics-72h",
                 "Control-72h VS Antibiotics-72h")




dge_labels <- cbind(labels, Experiment)
dge_labels <- cbind(dge_labels, comparation)
```



```{r toptags-volcano, fig.width = 10, fig.height = 6, fig.cap = '**EdgeR estimated logFC and logCPM.**', cache = FALSE}
toptags %>%
  mutate(significant = ifelse(FDR <= 0.05, TRUE, FALSE)) %>%
  ggplot(aes(x = logCPM, y = logFC, colour = FDR, shape = significant)) +
  geom_point() +
  scale_colour_viridis_c('FDR') +
  facet_wrap(~contrast, ncol = 3) +
  theme(
    legend.position = 'bottom'
  )

ggsave("../Results/WP1/Supplementary/Eukaryotes_DGE_VolcanoPlot.png",
       width = 18, # anchura
       height = 18, # altura
       units = "cm",
       dpi = 600)

```


```{r}
DGE_INTERES_WP1 <- toptags %>%   # We keep the same  1,040,758 entries and 38 total columns7
  left_join(Taxonomy, by="geneid") %>%
    check_row_count("After 1º left_join") %>%
  left_join(dge_labels, by= "contrast") %>%
      check_row_count("After 2º left_join")%>%
  left_join(eggnogs, by = 'geneid') %>%
  check_row_count("After 3º left_join")


write_parquet(DGE_INTERES_WP1, "../Data Frames/WP1/INTERES_Euk_WP1_DGE.parquet")

```

