 ---
title: "WorkPackage2_MicrobialCommunity_MetaT"
output: "D:\OneDrive\Obsidian\Brain\Projects\INTERES\WorkPakage2"
date: "2023-11-10"
---


```{r libraries, message = FALSE, cache = FALSE, include = FALSE}
# All the packages needed
# remove.packages("feather")
# library(feather)
require(readr); sprintf("readr: %s", packageVersion("readr"))
require(tidyr); sprintf("tidyr: %s", packageVersion("tidyr"))
require(stringr); sprintf("stringr: %s", packageVersion("stringr"))
require(ggplot2); sprintf("ggplot2: %s", packageVersion("ggplot2"))
require(edgeR); sprintf("edgeR: %s", packageVersion("edgeR"))
require(kfigr); sprintf("kfigr: %s", packageVersion("kfigr"))
require(knitr); sprintf("knitr: %s", packageVersion("knitr"))
require(DT); sprintf("DT: %s", packageVersion("DT"))
require(ggh4x); sprintf("ggh4x: %s", packageVersion("ggh4x"))
require(readxl); sprintf("readxl: %s", packageVersion("readxl"))   
require(ggpattern); sprintf("ggpattern: %s", packageVersion("ggpattern"))
require(VennDiagram); sprintf("VennDiagram: %s", packageVersion("VennDiagram"))
require(grid); sprintf("grid: %s", packageVersion("grid"))
require(grateful); sprintf("grateful: %s", packageVersion("grateful"))
require(plotrix); sprintf("plotrix: %s", packageVersion("plotrix"))
require(RColorBrewer); sprintf("RColorBrewer: %s", packageVersion("RColorBrewer"))
require(devtools); sprintf("devtools: %s", packageVersion("devtools"))
require(circlize); sprintf("circlize: %s", packageVersion("circlize"))
require(data.table); sprintf("data.table: %s", packageVersion("data.table"))
require(gapminder); sprintf("gapminder: %s", packageVersion("gapminder"))
require(gg.gap); sprintf("gg.gap: %s", packageVersion("gg.gap"))
require(feather); sprintf("feather: %s", packageVersion("feather"))
require(cowplot); sprintf("cowplot: %s", packageVersion("cowplot"))
require(purrr); sprintf("purrr: %s", packageVersion("purrr"))
require(dplyr); sprintf("dplyr: %s", packageVersion("dplyr"))
require(dtplyr); sprintf("dtplyr: %s", packageVersion("dtplyr"))
require(viridis); sprintf("viridis: %s", packageVersion("viridis"))
require(tibble); sprintf("tibble: %s", packageVersion("tibble"))
require(gridExtra); sprintf("gridExtra: %s", packageVersion("gridExtra"))
require(webshot); sprintf("webshot: %s", packageVersion("webshot"))
require(vegan); sprintf("vegan: %s", packageVersion("vegan"))
require(plotly); sprintf("plotly: %s", packageVersion("plotly"))
require(ggpmisc); sprintf("ggpmisc: %s", packageVersion("ggpmisc"))
require(ggbiplot); sprintf("ggbiplot: %s", packageVersion("ggbiplot"))
require(ComplexHeatmap); sprintf("ComplexHeatmap: %s", packageVersion("ComplexHeatmap"))
require(Hmisc); sprintf("Hmisc: %s", packageVersion("Hmisc"))
require(CoDaSeq); sprintf("CoDaSeq: %s", packageVersion("CoDaSeq"))
require(ggord); sprintf("ggord: %s", packageVersion("ggord"))
require(ggthemes); sprintf("ggthemes: %s", packageVersion("ggthemes"))
require(reshape2); sprintf("reshape2: %s", packageVersion("reshape2"))
require(arrow); sprintf("arrow: %s", packageVersion("arrow"))


SIGNIFICANCE = 0.05
set.seed(5555) # 5tory-5ecret-5olar-5ystem
# setwd("D:/OneDrive/Documentos/Super_ENVISION")

```


```{r}
# library(grateful)
# 
# # Crear carpeta de salida si no existe
# dir.create("../Results/WP2/Supplementary/grateful_output", recursive = TRUE, 
#            showWarnings = FALSE)
# 
# # Generar archivo de citas y .bib basado en todos los paquetes usados
# grateful::cite_packages(
#   pkgs = "All",   # Detecta automáticamente los paquetes cargados
#   output = "file",
#   out.dir = "../Results/WP2/Supplementary/grateful_output",
#   out.file = "WP2_citas_reporte",
#   bib.file = "WP2_citas"
# )


```

```{r, , fig.height=15, fig.width=15}

# Definir los colores especificados
my.colors_All <- c(
  "Alphaproteobacteria" = "blue4",
  "Rhodobacterales" = "deepskyblue4",
  "Puniceispirillales" = "royalblue2",
  "Rhizobiales" = "turquoise2",
  "Gammaproteobacteria" = "purple4",
  "Burkholderiales" = "deeppink2",
  "Beggiatoales" = "mediumpurple2",
  "Enterobacterales" = "magenta2",
  "Pseudomonadales" = "plum3",
  "SAR86" = "purple2",
  "Bacteroidota" = "peachpuff4",
  "Flavobacteriales" = "peachpuff1",
  "Firmicutes" = "lightcyan2",
  "Cyanobacteria" = "chartreuse2",
  "Actinobacteriota" = "darkred",
  "Planctomycetota" = "aquamarine2",
  "Archaea" = "darkorange2",
  "Other prokaryotes" = "grey33",
  "Spirotrichea" = "slateblue4",
  "Choreotrichida" = "slateblue",
  "Tintinnida" = "slateblue1",
  "Dinoflagellata" = "navy",
  "Gonyaulacales" = "turquoise3",
  "Alexandrium" = "turquoise1",
  "Gymnodiniales" = "lightskyblue",
  "Peridiniales" = "royalblue",
  "Suessiales" = "skyblue3",
  "Symbiodinium" = "skyblue1",
  "Syndiniales" = "lightsteelblue1",
  "Stramenopiles" = "darkgreen",
  "Ochrophyta" = "springgreen4",
  "Bacillariophyta" = "lightgreen",
  "Thalassiosira" = "green3",
  "Chaetoceros" = "darkolivegreen1",
  "Skeletonema" = "springgreen4",
  "Pseudo-nitzschia" = "green1",
  "Glaucophyta" = "orangered3",
  "Chlorophyta" = "aquamarine2",
  "Amoebozoa" = "lightpink4",
  "Hacrobia" = "khaki3",
  "Rhizaria" = "thistle3",
  "Other eukaryotes" = "grey33"
)


```

```{r, fig.height=7, fig.width=5}
PB_PP <- read.csv(
  "../Calculation/Environmental data/WP2_Spring_BP_PP_Mesocosmos.csv",
  sep = ",", check.names = F) %>%
  separate(sample, c ("treatment", "time"), sep = "_")


Nutrients <- read.csv(
  "../Calculation/Environmental data/WP2_Spring_Mesocosmos.csv",
  sep = ",", check.names = F) %>%
  separate(sample, c ("treatment", "time"), sep = "_") %>%
  dplyr::filter(variable !="NIT") %>%
  dplyr::filter(variable !="TDN") %>%
  dplyr::filter(variable !="NO2") %>%
  dplyr::filter(time !="96h") %>%
  dplyr::filter(time !="120h") %>%
  group_by(treatment, time,  variable) %>%
  dplyr::summarise(mean=mean(value), errorstandar=std.error(value))

# Combine both files
Environmentl_data <-rbind(Nutrients, PB_PP)


Environmentl_data$treatment <- factor(Environmentl_data$treatment,
                                     levels = c("C", "R", "RP"),
                                     labels = c("C",
                                                "R",
                                                "R+P"))




```


```{r, fig.height=5, fig.width=5}
Environmentl_data_1 <- Environmentl_data %>%
      dplyr::filter(!variable %in% c("PO4","SiO4H4","ab","BP","chla","PP")) 

Environmentl_data_1$variable <- factor(
  Environmentl_data_1$variable,levels = c("DOC","DON","DIN","NH4","NO3","NP"), 
  labels = c("DOC\n(µmol L⁻¹)",
             "DON\n(µmol L⁻¹)",
             "DIN\n(µmol L⁻¹)",
             "NH₄⁺\n(µmol L⁻¹)",
             "NO₃⁻\n(µmol L⁻¹)",
             "N:P \nratio" ))

Nutrients_plot1 <- ggplot(Environmentl_data_1, aes(y=mean, x=time, fill=variable)) + # fill=Our_Taxonomy
    geom_errorbar(aes(ymin=mean-errorstandar, ymax=mean+errorstandar), width=0.4, position=position_dodge(0.9)) +
    geom_bar(stat = "identity", alpha=1) + #
    theme_bw(base_size = 8) +
    theme(plot.subtitle  = element_text(size = 8, face = "bold", hjust = 0)) +
     theme(plot.title = element_text(size = 8, face = "bold", hjust = 0.5))+
     theme(axis.text.x = element_text(angle = 45, face = "bold", vjust = 1, hjust = 1, size=8)) +
     theme(axis.text.y = element_text(angle = 0, face = "bold", vjust = 1, hjust = 1, size=8)) +
    theme(strip.text.x = element_text(size=8, angle=0, face="bold"),
          strip.text.y = element_text(size=8, angle=0, face="bold"),
          strip.background = element_rect(colour="black", fill="white")) +
    ylab("") +
    xlab("") +
    # scale_fill_viridis(discrete = TRUE,  option="D") +      
scale_fill_manual(values = c(
  "#006BC9",  # DON (µmol L⁻¹)
  "#0079C3",  # DOC (µmol L⁻¹)
  "#0086BC",  # NH₄⁺ (µmol L⁻¹)
  "#0094B5",  # DIN (µmol L⁻¹)
  "#00A1AE",  # NO₃⁻ (µmol L⁻¹)
  "#00AEA8"  # SiO₄H₄ (µmol L⁻¹
))+

  facet_nested(variable~treatment, scales = "free_y") + #sDSles = "free_y",
        theme(legend.position="none") +
    theme(strip.text = element_text(size = 8))+
      facetted_pos_scales(
    y = list(
      scale_y_continuous(limits = c(0, 150), breaks = seq(0, 150, by = 50)),   # P starvation response
      scale_y_continuous(limits = c(0, 10), breaks = seq(0, 10, by = 5)),   # P starvation response
      scale_y_continuous(limits = c(0, 6), breaks = seq(0, 6, by = 2)),   # P starvation response
      scale_y_continuous(limits = c(0, 2), breaks = seq(0, 2, by = 1)),   # P starvation response
      scale_y_continuous(limits = c(0, 3), breaks = seq(0, 3, by = 1.5)),   # P starvation response
      scale_y_continuous(limits = c(0, 60), breaks = seq(0, 60, by = 20))
    ))
  #Nutrients_plot1


Environmentl_data_2 <- Environmentl_data%>%
      dplyr::filter(!variable %in% c(
        "DOC","DON","DIN","NH4","NO3","NP")) 

Environmentl_data_2$variable <- factor(Environmentl_data_2$variable,
                                     levels = c(
                                       "PO4",
                                       "SiO4H4",
                                       "ab",
                                       "BP",
                                       "chla",
                                       "PP"), 
                                     labels = c(
                                       "PO₄⁻³\n(µmol L⁻¹)",
                                       "Si(OH)₄⁺\n(µmol L⁻¹)", # Reuerda borrar el- de la figura final.
                                       "Bacterial\nabundance\n(Cell ml⁻¹)",
                                       "Bacterial\nproduction\n(µgC L⁻¹ d⁻¹)",
                                       "Chlorophyll a\n(mg m⁻³)",
                                       "Primary\nproduction\n(µgC L⁻¹ h⁻¹)" ))


Nutrients_plot2 <- ggplot(Environmentl_data_2, aes(y=mean, x=time, fill=variable)) + # fill=Our_Taxonomy
    geom_errorbar(aes(ymin=mean-errorstandar, ymax=mean+errorstandar), width=0.4, position=position_dodge(0.9)) +
    geom_bar(stat = "identity", alpha=1) + #
    theme_bw(base_size = 8) +
    theme(plot.subtitle  = element_text(size = 8, face = "bold", hjust = 0)) +
     theme(plot.title = element_text(size = 8, face = "bold", hjust = 0.5))+
     theme(axis.text.x = element_text(angle = 45, face = "bold", vjust = 1, hjust = 1, size=8)) +
     theme(axis.text.y = element_text(angle = 0, face = "bold", vjust = 1, hjust = 1, size=8)) +
    theme(strip.text.x = element_text(size=8, angle=0, face="bold"),
          strip.text.y = element_text(size=8, angle=0, face="bold"),
          strip.background = element_rect(colour="black", fill="white")) +
    ylab("") +
    xlab("") +
    # scale_fill_viridis(discrete = TRUE,  option="D") +      
scale_fill_manual(values = c(
  "#00C99A",  # PO₄⁻³ (µmol L⁻¹)
  "#00D794",  # N:P ratio
  "#00E48D",  # Bacterial abundance (Cell ml⁻¹)
  "#00F286",  # Bacterial production (µgC L⁻¹ d⁻¹)
  "#00FF80",  # Chlorophyll a (mg m⁻³)
  "#00FF72"   # Primary production (µgC L⁻¹ h⁻¹) ← blanco, puedes cambiarlo si quieres
))+

  facet_nested(variable~treatment, scales = "free_y") + #sDSles = "free_y",
        theme(legend.position="none") +
    theme(strip.text = element_text(size = 8))+
      facetted_pos_scales(
    y = list(
      scale_y_continuous(limits = c(0, 2), breaks = seq(0, 2, by = 1)),   # P starvation response
      scale_y_continuous(limits = c(0, 15), breaks = seq(0, 15, by = 5)),  # High affinity transporters
      scale_y_continuous(limits = c(0, 3500000), breaks = seq(0, 3500000, by = 1000000)),  # Low affinity transporters
      scale_y_continuous(limits = c(0, 50), breaks = seq(0, 50, by = 25)),   # P starvation response
      scale_y_continuous(limits = c(0, 3), breaks = seq(0, 3, by = 1.5)),   # P starvation response
      scale_y_continuous(limits = c(0, 15), breaks = seq(0, 15, by = 5))  # High affinity transporters
    ))
  #Nutrients_plot2
```



```{r}
# 📚 Cargar la librería patchwork
library(patchwork)

# 📌 Unir las cuatro gráficas en dos columnas
combined_plot <- (Nutrients_plot1 | Nutrients_plot2)
## 💾 Guardar
#png("../Results/WP2/Figure_1.png",
#    width = 18, height = 12, units = 'cm', res=600 )

# Mostrar el gráfico combinado
combined_plot

# Imprime el gráfico final
# print(combined_plot)

# Cierra el dispositivo de gráficos
#dev.off()
#combined_plot
```
```{r}
library(magick)
library(ggplot2)
library(grid)
library(cowplot)
library(patchwork)

# 1. Leer imagen del mapa como grob
mapa_img <- image_read("../Scripts/Mapa Ria Vigo/Mapa_RiaVigo.jpg")
mapa_grob <- rasterGrob(mapa_img, interpolate = TRUE)

# 2. Convertir tu gráfico de patchwork a grob
plot_grob <- ggdraw() + draw_plot(combined_plot)

# 3. Crear lienzo con menos márgenes laterales y menos espacio blanco
figura_final <- ggdraw() +
  draw_plot(mapa_grob, x = 0.02, y = 0.52, width = 0.96, height = 0.5) +  # margen lateral reducido
  draw_plot(plot_grob, x = 0,    y = 0, width = 1,    height = 0.56) +  # menos margen abajo
  draw_label("↓", x = 0.65, y = 0.695, fontface = "bold", size = 20, color = "#000")+
  draw_label("a)", x = 0.01, y = 0.98, hjust = 0, fontface = "bold", size = 16) +
  draw_label("b)", x = 0.01, y = 0.56, hjust = 0, fontface = "bold", size = 16)

# 4. Guardar figura finalQuiero q ue
ggsave("../Results/WP2/Figure_1.png", figura_final,
       width = 18, height = 24, units = "cm", dpi = 600, bg = "white")






```


```{r}
# The latest version of the protein profile list (15/05/2023) 
Hiper_proteins <- read_excel("../Calculation/Protein_profiles_2025.xlsx", sheet = "Protein profiles",  col_names = TRUE) %>% #range = "A1:D10",
  dplyr::select(Category,	Subcategory, name,	gene_protein,	KEGG_ko, kingdom) %>% 
  filter(KEGG_ko != "NA")
# %>% 
  # filter(kingdom != "none")

# # The latest version of the protein profile list (15/05/2023) 
# Hiper_modules <- read_excel("D:/OneDrive/Obsidian/Brain/Neural Networks/Basal Ganglia (Skills)/Informatics/Bioinformatics/Databases/Genes/Protein_profiles_2023.xlsm", sheet = "KEGG Pathway Maps",  col_names = TRUE) 
# 
# # The latest version of the protein profile list (15/05/2023) 
# AbsoluteCategory <- read_excel("D:/OneDrive/Obsidian/Brain/Neural Networks/Basal Ganglia (Skills)/Informatics/Bioinformatics/Databases/Genes/Protein_profiles_2023.xlsm", sheet = "AbsoluteCategory",  col_names = TRUE) 

env_flags_myrda <- read.csv("../Calculation/Raw_files/int_flags.csv") %>%
  tibble::column_to_rownames('Sample')
```



```{r setup, include=FALSE}
Prok_INTERES_WP2_TPMs <- read_parquet("../Data Frames/WP2/INTERES_Prok_WP2_TPMs_mean_Annotated_1KEGG_ko.parquet") %>%
  mutate(Final_Taxonomy = ifelse(Final_Taxonomy == "Bacteria", "Other prokaryotes", Final_Taxonomy))%>%
  mutate(Final_Taxonomy = ifelse(Final_Taxonomy == "Proteobacteria", "Other prokaryotes", Final_Taxonomy))%>%
  mutate(Final_Taxonomy = ifelse(Final_Taxonomy == "Pelagibacterales", "Alphaproteobacteria", Final_Taxonomy))%>%
  mutate(Final_Taxonomy = ifelse(Final_Taxonomy == "Alphaproteobacteria", "Alphaproteobacteria", Final_Taxonomy))%>%
  mutate(Final_Taxonomy = ifelse(Final_Taxonomy == "Gammaproteobacteria", "Gammaproteobacteria", Final_Taxonomy))%>%
  mutate(Final_Taxonomy = ifelse(Final_Taxonomy == "No domain", "Other prokaryotes", Final_Taxonomy))


Tlist <- Prok_INTERES_WP2_TPMs %>%
  dplyr::select(Final_Taxonomy)

Tlist <- unique(Tlist)
```

```{r}
Prok_INTERES_WP2_TPMs$Final_Taxonomy  <- factor(  Prok_INTERES_WP2_TPMs$Final_Taxonomy,
                                                     levels = c("Alphaproteobacteria",
                                                                 "Rhodobacterales","Pelagibacterales", "Puniceispirillales", "Rhizobiales", 
                                                                "Gammaproteobacteria",
                                                                 "Beggiatoales","Burkholderiales", "Enterobacterales", "Pseudomonadales", "SAR86",
                                                                 "Proteobacteria",
                                                                 "Bacteroidota", # Protista
                                                                 "Flavobacteriales", # Protista
                                                                 "Firmicutes",
                                                                 "Cyanobacteria",
                                                                 "Actinobacteriota",
                                                                 "Planctomycetota",
                                                                 "Archaea",
                                                                "Other prokaryotes"))

```


```{r fig.height=15, fig.width=10} 
Prok_INTERES_WP2_TPMs_2 <- Prok_INTERES_WP2_TPMs %>%
  group_by(Workpackage, treatment, time, Final_Taxonomy) %>%
  dplyr::summarise(tpm=sum(tpm)) %>% 
  mutate(Label = "Prokaryotes") ##
  
```




```{r}
Euk_INTERES_WP2_TPMs <- read_parquet("../Data Frames/WP2/INTERES_Euk_WP2_TPMs_Annotated_1KEGG_ko.parquet") %>%
  # mutate(Final_Taxonomy = ifelse(Final_Taxonomy == "Others", "Other eukaryotes", Final_Taxonomy))%>%
  mutate(Final_Taxonomy = ifelse(Final_Taxonomy == "Eukaryota", "Other eukaryotes", Final_Taxonomy))%>%
  mutate(Final_Taxonomy = ifelse(Final_Taxonomy == "Alveolata", "Other eukaryotes", Final_Taxonomy))%>%
  mutate(Final_Taxonomy = ifelse(Final_Taxonomy == "Opisthokonta", "Other eukaryotes", Final_Taxonomy))%>%
  mutate(Final_Taxonomy = ifelse(Final_Taxonomy == "Ciliophora", "Other eukaryotes", Final_Taxonomy))%>%
  mutate(Final_Taxonomy = ifelse(Final_Taxonomy == "Dinophyceae", "Dinoflagellata", Final_Taxonomy))%>%
  mutate(Final_Taxonomy = ifelse(Final_Taxonomy == "Sagenista", "Stramenopiles", Final_Taxonomy))%>%
  mutate(Final_Taxonomy = ifelse(Final_Taxonomy == "Rhodophyta", "Other eukaryotes", Final_Taxonomy))%>%
  mutate(Final_Taxonomy = ifelse(Final_Taxonomy == "Micromonas", "Chlorophyta", Final_Taxonomy))%>%
  mutate(Final_Taxonomy = ifelse(Final_Taxonomy == "Ostreococcus", "Chlorophyta", Final_Taxonomy))%>%
  mutate(Final_Taxonomy = ifelse(Final_Taxonomy == "Peridinium", "Peridiniales", Final_Taxonomy))%>%
  mutate(Final_Taxonomy = ifelse(Final_Taxonomy == "Scrippsiella", "Peridiniales", Final_Taxonomy))
Tlist <- Euk_INTERES_WP2_TPMs %>%
  dplyr::select(Final_Taxonomy)

Tlist <- unique(Tlist)
```


```{r} 
Euk_INTERES_WP2_TPMs$Final_Taxonomy <- factor(Euk_INTERES_WP2_TPMs$Final_Taxonomy, levels = c(
# Phylum: Alveolata
         "Alveolata",
  #  Class: Ciliophora
           "Ciliophora",
    # Order: Spirotrichea  
            "Spirotrichea", # Order
    # Family: Choreotrichida
             "Choreotrichida", # Family
    # Family: Tintinnida
             "Tintinnida", # Family
  
#  Class: Dinoflagellata  ↓ 
           "Dinoflagellata",
    # Order: Dinophyceae  ↓ 
            "Dinophyceae",
    # Family: Gonyaulacales
             "Gonyaulacales",
      # Genus:
        "Alexandrium",
        "Ceratium",
        "Lingulodinium",
    # Family: Gonyaulacales
             "Gymnodiniales",
      # Genus:
        "Karenia",
        "Karlodinium",
    # Family: Peridiniales
             "Peridiniales",
      # Genus:
        "Scrippsiella",
        "Peridinium", 
    # Family: Prorocentrales
     "Prorocentrales", 
      # Genus:
        "Prorocentrum", 
    # Family: Suessiales
     "Suessiales", 
      # Genus:
        "Pelagodinium",
        "Symbiodinium",
    # Order: Syndiniales  
            "Syndiniales", 
    # Order: Noctilucophyceae  
  "Noctilucophyceae",  
    # Order: Oxyrrhea  
  "Oxyrrhea", 



# Phylum: Stramenopiles
         "Stramenopiles",
  #  Class: Ochrophyta  
           "Ochrophyta", # Class
    # Order: Bacillariophyta  
            "Bacillariophyta", 
      # Genus:
        "Thalassionema",
        "Thalassiosira",
        "Chaetoceros",
        "Skeletonema",
        "Coscinodiscus",
        "Pseudo-nitzschia",
        "Cylindrotheca",
        "Licomophora",

# Phylum Archaeplastida, mostly Chlorophyta
        "Archaeplastida", # Phylum
  #  Class: Rhodophyta 
           "Rhodophyta", 
#  Class: Glaucophyta  
           "Glaucophyta",
#  Class: Chlorophyta  
           "Chlorophyta",# Class
      # # Genus:
      #   "Micromonas",
      #   "Ostreococcus",


"Amoebozoa", # Protista
"Hacrobia", # Protista
"Rhizaria", # Protista
"Excavata", # Protista
"Opisthokonta",
 # "Ciliophora", # Class
"Other eukaryotes"# Fungi/Metazoa
))


                                           
```



```{r} 


Euk_INTERES_WP2_TPMs_Replics_Mean <- Euk_INTERES_WP2_TPMs %>%
  group_by(Workpackage, treatment, time, Final_Taxonomy) %>%
  dplyr::summarise(tpm=sum(tpm)) %>%
  mutate(Label = "Eukaryotes") ##

```


```{r, fig.height=7, fig.width=7}
# Prok_INTERES_WP2_TPMs_2
# Euk_INTERES_WP2_TPMs_Replics_Mean

MetaTs <-rbind(Prok_INTERES_WP2_TPMs_2, Euk_INTERES_WP2_TPMs_Replics_Mean)
MetaTs$Label  <- factor(  MetaTs$Label,
                                                     levels = c("Prokaryotes","Eukaryotes"))

MetaTs_plot <- ggplot(MetaTs, aes(y=tpm, x=treatment, fill=Final_Taxonomy)) + # fill=Our_Taxonomy
    geom_bar(position="fill", stat="identity") + #, color ="black"
  # geom_text(aes(label = Final_Taxonomy), position = position_fill(vjust = 0.5)) + # Agregar esta línea
  ggtitle ("a) Metatranscriptomic Taxonomy Distribution")+
    labs(x="", y="", fill="", col="") +
    theme_bw(base_size = 8) +
  theme(plot.title = element_text(size = 10, face = "bold", hjust = 0.5),
        plot.subtitle  = element_text(size = 8, hjust = 0), 
        plot.caption = element_text(size = 8, hjust = 0, vjust = 0),
        axis.title.y = element_blank(),
        axis.title.x = element_text(angle = 0, vjust = 0.5, face = "bold"),
        axis.text.x = element_text(angle = 0, vjust = 0.5, hjust = 0.5, size=8, face = "bold"),
        axis.text.y = element_text(angle = 0, vjust = 0.5, hjust = 0.5, size=8, face = "bold"),
        strip.text = element_text(size = 8), 
        strip.text.x = element_text(size=8, angle=0, face = "bold"),
        strip.text.y = element_text(size=8, angle=270, face = "bold"),
        strip.background = element_rect(colour="black", fill="white"),
        legend.text = element_text(size = 9), # Incrementar el tamaño del texto de la leyenda
        legend.position = "right",
        legend.box = "horizontal",
        legend.margin = margin(t = -1, r = 0, b = 0, l = 0, unit = "cm"),
        legend.box.margin = margin(t = 0, r = 0, b = 0, l = 0, unit = "cm"),
        legend.spacing = unit(0.05, "cm"),
    legend.key.size = unit(0.2, "cm"),  # Ajuste general del tamaño del recuadro
    legend.key.height = unit(0.2, "cm"),  # Ajuste del tamaño de altura del recuadro
    legend.key.width = unit(0.3, "cm"), 
        legend.title = element_blank()) +
      guides(fill = guide_legend(nrow = 42)) +
    scale_fill_manual(values = my.colors_All) +
    scale_y_continuous(labels = scales::percent) +
facet_nested( ~ Label+time, scales = "free")+
  theme(panel.spacing = unit(0.2, "lines"))

MetaTs_plot
```
```{r}
library(dplyr)
library(tidyr)

Prok_INTERES_WP2_TPMs <- read_parquet("../Data Frames/WP2/INTERES_Prok_WP2_TPMs_Annotated_1KEGG_ko.parquet") 
Euk_INTERES_WP2_TPMs <- read_parquet("../Data Frames/WP2/INTERES_Euk_WP2_TPMs_Annotated_1KEGG_ko.parquet")
```


```{r}
Prok_INTERES_WP2_TPMs_2 <- Prok_INTERES_WP2_TPMs %>%
  group_by(Workpackage, treatment, time, Final_Taxonomy, replic) %>%
  dplyr::summarise(tpm=sum(tpm)) %>% 
  mutate(Label = "Prokaryotes") ##

Euk_INTERES_WP2_TPMs_Replics_Mean <- Euk_INTERES_WP2_TPMs %>%
  group_by(Workpackage, treatment, time, Final_Taxonomy, replic) %>%
  dplyr::summarise(tpm=sum(tpm)) %>%
  mutate(Label = "Eukaryotes") ##

MetaTs <-rbind(Prok_INTERES_WP2_TPMs_2, Euk_INTERES_WP2_TPMs_Replics_Mean)
# MetaTs$Label  <- factor(  MetaTs$Label,
#                                                      levels = c("Prokaryotes","Eukaryotes"))


# Colapsa TPM por réplica
df_rep <- MetaTs %>%
  dplyr::group_by(time, Label, Final_Taxonomy, treatment, replic) %>%
  dplyr::summarise(tpm = sum(tpm), .groups = "drop") %>%
  dplyr::filter(is.finite(tpm))

# Alinear pares por 'replic' y quedarte con pares completos
C_vs_R <- df_rep %>%
  dplyr::group_by(time, Label, Final_Taxonomy) %>%
  dplyr::filter(n_distinct(treatment) == 3) %>%
  tidyr::pivot_wider(id_cols = c(time, Label, Final_Taxonomy, replic),
                     names_from = treatment, values_from = tpm) %>%
  tidyr::drop_na() %>%
  ungroup()%>%
  dplyr::select(-"R+P")

# t-test pareado SIN ajuste (one-sample sobre las diferencias)
paired_results <- C_vs_R %>%
  dplyr::group_by(time, Label, Final_Taxonomy) %>%
  dplyr::group_modify(~{
    trt_cols <- setdiff(names(.x), c("time","Label", "Final_Taxonomy", "replic"))
    if (length(trt_cols) != 2) return(tibble::tibble())
    trt_cols <- sort(trt_cols)                # define orden A - B
    diff <- .x[[trt_cols[1]]] - .x[[trt_cols[2]]]
    if (length(diff) < 2 || sd(diff) == 0 || any(!is.finite(diff))) {
      return(tibble::tibble(
        n_pairs = length(diff),
        treatment_A = trt_cols[1], treatment_B = trt_cols[2],
        estimate = NA_real_, conf.low = NA_real_, conf.high = NA_real_,
        statistic = NA_real_, df = NA_real_, p = NA_real_, d_z = NA_real_
      ))
    }
    tt <- stats::t.test(diff, mu = 0)        # p no ajustado en tt$p.value
    d_z <- mean(diff)/sd(diff)               # tamaño de efecto pareado
    tibble::tibble(
      n_pairs = length(diff),
      treatment_A = trt_cols[1], treatment_B = trt_cols[2],
      estimate = unname(tt$estimate),
      conf.low = unname(tt$conf.int[1]),
      conf.high = unname(tt$conf.int[2]),
      statistic = unname(tt$statistic),
      df = unname(tt$parameter),
      p = unname(tt$p.value),
      d_z = d_z
    )
  }) %>%
  arrange(p) %>%
  ungroup()

Sig_genes_paired <- paired_results %>%
dplyr::mutate(GPvale = p * sqrt((6) / 100)) #%>%
  # dplyr::filter(!is.na(GPvale), GPvale < 0.05) 
```


```{r}
# Alinear pares por 'replic' y quedarte con pares completos
C_vs_RP <- df_rep %>%
  dplyr::group_by(time, Label, Final_Taxonomy) %>%
  dplyr::filter(n_distinct(treatment) == 3) %>%
  tidyr::pivot_wider(id_cols = c(time, Label, Final_Taxonomy, replic),
                     names_from = treatment, values_from = tpm) %>%
  tidyr::drop_na() %>%
  ungroup()%>%
  dplyr::select(-"R")

# t-test pareado SIN ajuste (one-sample sobre las diferencias)
paired_results <- C_vs_RP %>%
  dplyr::group_by(time, Label, Final_Taxonomy) %>%
  dplyr::group_modify(~{
    trt_cols <- setdiff(names(.x), c("time","Label", "Final_Taxonomy","replic"))
    if (length(trt_cols) != 2) return(tibble::tibble())
    trt_cols <- sort(trt_cols)                # define orden A - B
    diff <- .x[[trt_cols[1]]] - .x[[trt_cols[2]]]
    if (length(diff) < 2 || sd(diff) == 0 || any(!is.finite(diff))) {
      return(tibble::tibble(
        n_pairs = length(diff),
        treatment_A = trt_cols[1], treatment_B = trt_cols[2],
        estimate = NA_real_, conf.low = NA_real_, conf.high = NA_real_,
        statistic = NA_real_, df = NA_real_, p = NA_real_, d_z = NA_real_
      ))
    }
    tt <- stats::t.test(diff, mu = 0)        # p no ajustado en tt$p.value
    d_z <- mean(diff)/sd(diff)               # tamaño de efecto pareado
    tibble::tibble(
      n_pairs = length(diff),
      treatment_A = trt_cols[1], treatment_B = trt_cols[2],
      estimate = unname(tt$estimate),
      conf.low = unname(tt$conf.int[1]),
      conf.high = unname(tt$conf.int[2]),
      statistic = unname(tt$statistic),
      df = unname(tt$parameter),
      p = unname(tt$p.value),
      d_z = d_z
    )
  }) %>%
  arrange(p) %>%
  ungroup()

Sig_genes_paired2 <- paired_results %>%
dplyr::mutate(GPvale = p * sqrt((6) / 100)) #%>%
  # dplyr::filter(!is.na(GPvale), GPvale < 0.05) 

```


```{r, ,fig.height=60, fig.width=35} 
Prok_INTERES_WP2_TPMs_1 <- read_parquet("../Data Frames/WP2/INTERES_Prok_WP2_TPMs_Annotated_1KEGG_ko.parquet") %>%
  mutate(Final_Taxonomy = ifelse(Final_Taxonomy == "Bacteria", "Other prokaryotes", Final_Taxonomy))%>%
  mutate(Final_Taxonomy = ifelse(Final_Taxonomy == "Proteobacteria", "Other prokaryotes", Final_Taxonomy))%>%
  mutate(Final_Taxonomy = ifelse(Final_Taxonomy == "Pelagibacterales", "Alphaproteobacteria", Final_Taxonomy))%>%
  mutate(Final_Taxonomy = ifelse(Final_Taxonomy == "Alphaproteobacteria", "Alphaproteobacteria", Final_Taxonomy))%>%
  mutate(Final_Taxonomy = ifelse(Final_Taxonomy == "Gammaproteobacteria", "Gammaproteobacteria", Final_Taxonomy))%>%
  mutate(Final_Taxonomy = ifelse(Final_Taxonomy == "No domain", "Other prokaryotes", Final_Taxonomy))


Prok_INTERES_WP2_TPMs_1$Final_Taxonomy  <- factor(  Prok_INTERES_WP2_TPMs_1$Final_Taxonomy,
                                                     levels = c("Alphaproteobacteria",
                                                                 "Rhodobacterales","Pelagibacterales", "Puniceispirillales", "Rhizobiales", 
                                                                "Gammaproteobacteria",
                                                                 "Beggiatoales","Burkholderiales", "Enterobacterales", "Pseudomonadales", "SAR86",
                                                                 "Proteobacteria",
                                                                 "Bacteroidota", # Protista
                                                                 "Flavobacteriales", # Protista
                                                                 "Firmicutes",
                                                                 "Cyanobacteria",
                                                                 "Actinobacteriota",
                                                                 "Planctomycetota",
                                                                 "Archaea",
                                                                "Other prokaryotes"))

```




```{r}
Euk_INTERES_WP2_TPMs_1 <- read_parquet("../Data Frames/WP2/INTERES_Euk_WP2_TPMs_Annotated_1KEGG_ko.parquet") %>%
  # mutate(Final_Taxonomy = ifelse(Final_Taxonomy == "Others", "Other eukaryotes", Final_Taxonomy))%>%
  mutate(Final_Taxonomy = ifelse(Final_Taxonomy == "Eukaryota", "Other eukaryotes", Final_Taxonomy))%>%
  mutate(Final_Taxonomy = ifelse(Final_Taxonomy == "Alveolata", "Other eukaryotes", Final_Taxonomy))%>%
  mutate(Final_Taxonomy = ifelse(Final_Taxonomy == "Opisthokonta", "Other eukaryotes", Final_Taxonomy))%>%
  mutate(Final_Taxonomy = ifelse(Final_Taxonomy == "Ciliophora", "Other eukaryotes", Final_Taxonomy))%>%
  mutate(Final_Taxonomy = ifelse(Final_Taxonomy == "Dinophyceae", "Dinoflagellata", Final_Taxonomy))%>%
  mutate(Final_Taxonomy = ifelse(Final_Taxonomy == "Sagenista", "Stramenopiles", Final_Taxonomy))%>%
  mutate(Final_Taxonomy = ifelse(Final_Taxonomy == "Rhodophyta", "Other eukaryotes", Final_Taxonomy))%>%
  mutate(Final_Taxonomy = ifelse(Final_Taxonomy == "Micromonas", "Chlorophyta", Final_Taxonomy))%>%
  mutate(Final_Taxonomy = ifelse(Final_Taxonomy == "Ostreococcus", "Chlorophyta", Final_Taxonomy))%>%
  mutate(Final_Taxonomy = ifelse(Final_Taxonomy == "Peridinium", "Peridiniales", Final_Taxonomy))%>%
  mutate(Final_Taxonomy = ifelse(Final_Taxonomy == "Scrippsiella", "Peridiniales", Final_Taxonomy))


Euk_INTERES_WP2_TPMs_1$Final_Taxonomy <- factor(Euk_INTERES_WP2_TPMs_1$Final_Taxonomy, levels = c(
         "Alveolata",
           "Ciliophora",
            "Spirotrichea", # Order
             "Choreotrichida", # Family
             "Tintinnida", # Family
             "Dinoflagellata",
            "Dinophyceae",
             "Gonyaulacales",
        "Alexandrium",
        "Ceratium",
        "Lingulodinium",
             "Gymnodiniales",
        "Karenia",
        "Karlodinium",
             "Peridiniales",
        "Scrippsiella",
        "Peridinium", 
     "Prorocentrales", 
        "Prorocentrum", 
     "Suessiales", 
        "Pelagodinium",
        "Symbiodinium",
            "Syndiniales", 
  "Noctilucophyceae",  
  "Oxyrrhea", 
         "Stramenopiles",
           "Ochrophyta", # Class
            "Bacillariophyta", 
        "Thalassionema",
        "Thalassiosira",
        "Chaetoceros",
        "Skeletonema",
        "Coscinodiscus",
        "Pseudo-nitzschia",
        "Cylindrotheca",
        "Licomophora",
        "Archaeplastida", # Phylum
           "Rhodophyta", 
           "Glaucophyta",
           "Chlorophyta",# Class
"Amoebozoa", # Protista
"Hacrobia", # Protista
"Rhizaria", # Protista
"Excavata", # Protista
"Opisthokonta",
"Other eukaryotes"# Fungi/Metazoa
))


                                           
```




```{r, ,fig.height=15, fig.width=10} 
Prok_P_Genes <- Prok_INTERES_WP2_TPMs_1 %>%
    left_join(Hiper_proteins, by="KEGG_ko") %>%
    dplyr::filter(KEGG_ko %in% Hiper_proteins$KEGG_ko)  %>% 
dplyr::select(tpm, gene_protein, KEGG_ko, Subcategory, Workpackage, treatment, time, replic, Final_Taxonomy, Category, Subcategory) %>%
    dplyr::filter(Category == "Phosphorus metabolism") %>%
  mutate(Domain = "Prokaryotes") ##




Euk_P_Genes <- Euk_INTERES_WP2_TPMs_1 %>%
    left_join(Hiper_proteins, by="KEGG_ko") %>%
    dplyr::filter(KEGG_ko %in% Hiper_proteins$KEGG_ko)  %>%
dplyr::select(tpm, gene_protein, KEGG_ko, Subcategory, Workpackage, treatment, time, replic, Final_Taxonomy, Category, Subcategory) %>%
  mutate(Domain = "Eukaryotes") ##





  P_Genes <-rbind(Prok_P_Genes, Euk_P_Genes)

```

<!-- e -->


<!-- e -->
```{r, fig.height=7, fig.width=17}
library(dplyr)

# Paso 1: Calcular la abundancia total por Subcategory y Genus
Prok_INTERES_WP2_TPMs_2 <- Prok_INTERES_WP2_TPMs_1 %>%
  dplyr::left_join(Hiper_proteins, by = "KEGG_ko") 
  
H_affinity_Rhodobacterales <- Prok_INTERES_WP2_TPMs_2 %>%
      # dplyr::filter(Category == "Phosphorus metabolism") %>%
      dplyr::filter(Subcategory == "High affinity transporters") %>%
  dplyr::filter(gene_protein %in% c("pstA", "pstB", "pstC", "pstS")) %>%
  dplyr::filter(Final_Taxonomy %in% c ("Rhodobacterales", "Pseudomonadales")) %>%
  dplyr::group_by(Workpackage, treatment, time, replic, Subcategory, Genus, Final_Taxonomy) %>%
  dplyr::summarise(tpm = sum(tpm)) %>%
  dplyr::group_by(Workpackage, treatment, time, Subcategory, Genus, Final_Taxonomy) %>%
  dplyr::summarise(tpm = mean(tpm))  %>%
  mutate(Genus = ifelse(Genus == "HTCC2207", "Porticoccaceae", Genus))


H_affinity_Rhodobacterales_2 <- H_affinity_Rhodobacterales %>%
      # dplyr::filter(Category == "Phosphorus metabolism") %>%
  dplyr::group_by(Genus, Final_Taxonomy) %>%
  dplyr::summarise(tpm = mean(tpm))  


# 
# Paso 2: Filtrar los géneros más abundantes por Subcategory
# Por ejemplo, seleccionamos los 5 géneros más abundantes por Subcategory
top_genus <- H_affinity_Rhodobacterales_2 %>%
  dplyr::group_by(Final_Taxonomy) %>%
  top_n(4, tpm)  # Cambia el número (5) si quieres más o menos géneros

# Paso 3: Generar el gráfico con los géneros más abundantes
MetaTs_plot <- ggplot(top_genus, aes(y= tpm, x = Final_Taxonomy, fill = Genus)) +
  geom_bar(position = "fill", stat = "identity") +
  ggtitle("a) Metatranscriptomic Taxonomy Distribution") +
  labs(x = "", y = "", fill = "", col = "") +
  theme_bw(base_size = 8) +
  theme(plot.title = element_text(size = 10, face = "bold", hjust = 0.5),
        plot.subtitle = element_text(size = 8, hjust = 0), 
        plot.caption = element_text(size = 8, hjust = 0, vjust = 0),
        axis.title.y = element_blank(),
        axis.title.x = element_text(angle = 0, vjust = 0.5, face = "bold"),
        axis.text.x = element_text(angle = 0, vjust = 0.5, hjust = 0.5, size = 8, face = "bold"),
        axis.text.y = element_text(angle = 0, vjust = 0.5, hjust = 0.5, size = 8, face = "bold"),
        strip.text = element_text(size = 8), 
        strip.text.x = element_text(size = 8, angle = 0, face = "bold"),
        strip.text.y = element_text(size = 8, angle = 270, face = "bold"),
        strip.background = element_rect(colour = "black", fill = "white"),
        legend.text = element_text(size = 9), 
        legend.position = "right",
        legend.box = "horizontal",
        legend.margin = margin(t = -1, r = 0, b = 0, l = 0, unit = "cm"),
        legend.box.margin = margin(t = 0, r = 0, b = 0, l = 0, unit = "cm"),
        legend.spacing = unit(0.05, "cm"),
        legend.key.size = unit(0.2, "cm"),
        legend.key.height = unit(0.2, "cm"),
        legend.key.width = unit(0.3, "cm"),
        legend.title = element_blank()) +
  guides(fill = guide_legend(nrow = 42)) +
  scale_y_continuous(labels = scales::percent) +
    facet_nested( ~ Final_Taxonomy, scales = "free_x", labeller = label_wrap_gen(15)) +
  theme(panel.spacing = unit(0.2, "lines"))

MetaTs_plot



```


```{r, fig.height=7, fig.width=17}
library(dplyr)

Organic_P_hydrolysis_Rhodobacterales <- Prok_INTERES_WP2_TPMs_2 %>%
      # dplyr::filter(Category == "Phosphorus metabolism") %>%
      dplyr::filter(Subcategory == "Organic P hydrolysis") %>%
  dplyr::filter(gene_protein %in% c("phoA", "phoD")) %>%
  dplyr::filter(Final_Taxonomy %in% c ("Pseudomonadales")) %>%
  dplyr::group_by(Workpackage, treatment, time, replic, Subcategory, Family, Genus, Final_Taxonomy) %>%
  dplyr::summarise(tpm = sum(tpm)) %>%
  dplyr::group_by(Workpackage, treatment, time, Subcategory, Family, Genus, Final_Taxonomy) %>%
  dplyr::summarise(tpm = mean(tpm))  %>%
mutate(Genus = ifelse(is.na(Genus), Family, Genus))

Organic_P_hydrolysis_Rhodobacterales_2 <- Organic_P_hydrolysis_Rhodobacterales %>%
      # dplyr::filter(Category == "Phosphorus metabolism") %>%
  dplyr::group_by(Genus, Final_Taxonomy) %>%
  dplyr::summarise(tpm = mean(tpm))  


# 
# Paso 2: Filtrar los géneros más abundantes por Subcategory
# Por ejemplo, seleccionamos los 5 géneros más abundantes por Subcategory
top_genus <- Organic_P_hydrolysis_Rhodobacterales_2 %>%
  dplyr::group_by(Final_Taxonomy) %>%
  top_n(4, tpm)  # Cambia el número (5) si quieres más o menos géneros

# Paso 3: Generar el gráfico con los géneros más abundantes
MetaTs_plot <- ggplot(top_genus, aes(y= tpm, x = Final_Taxonomy, fill = Genus)) +
  geom_bar(position = "fill", stat = "identity") +
  ggtitle("a) Metatranscriptomic Taxonomy Distribution") +
  labs(x = "", y = "", fill = "", col = "") +
  theme_bw(base_size = 8) +
  theme(plot.title = element_text(size = 10, face = "bold", hjust = 0.5),
        plot.subtitle = element_text(size = 8, hjust = 0), 
        plot.caption = element_text(size = 8, hjust = 0, vjust = 0),
        axis.title.y = element_blank(),
        axis.title.x = element_text(angle = 0, vjust = 0.5, face = "bold"),
        axis.text.x = element_text(angle = 0, vjust = 0.5, hjust = 0.5, size = 8, face = "bold"),
        axis.text.y = element_text(angle = 0, vjust = 0.5, hjust = 0.5, size = 8, face = "bold"),
        strip.text = element_text(size = 8), 
        strip.text.x = element_text(size = 8, angle = 0, face = "bold"),
        strip.text.y = element_text(size = 8, angle = 270, face = "bold"),
        strip.background = element_rect(colour = "black", fill = "white"),
        legend.text = element_text(size = 9), 
        legend.position = "right",
        legend.box = "horizontal",
        legend.margin = margin(t = -1, r = 0, b = 0, l = 0, unit = "cm"),
        legend.box.margin = margin(t = 0, r = 0, b = 0, l = 0, unit = "cm"),
        legend.spacing = unit(0.05, "cm"),
        legend.key.size = unit(0.2, "cm"),
        legend.key.height = unit(0.2, "cm"),
        legend.key.width = unit(0.3, "cm"),
        legend.title = element_blank()) +
  guides(fill = guide_legend(nrow = 42)) +
  scale_y_continuous(labels = scales::percent) +
    facet_nested( ~ Final_Taxonomy, scales = "free_x", labeller = label_wrap_gen(15)) +
  theme(panel.spacing = unit(0.2, "lines"))

MetaTs_plot



```


```{r, fig.height=7, fig.width=17}
library(dplyr)

Phosphonate_metabolism_Rhodobacterales <- Prok_INTERES_WP2_TPMs_2 %>%
      # dplyr::filter(Category == "Phosphorus metabolism") %>%
      dplyr::filter(Subcategory == "Phosphonate metabolism") %>%
  dplyr::filter(gene_protein %in% c("phnC")) %>%
  dplyr::filter(Final_Taxonomy %in% c ("Rhodobacterales")) %>%
  dplyr::group_by(Workpackage, treatment, time, replic, Subcategory, Family, Genus, Final_Taxonomy) %>%
  dplyr::summarise(tpm = sum(tpm)) %>%
  dplyr::group_by(Workpackage, treatment, time, Subcategory, Family, Genus, Final_Taxonomy) %>%
  dplyr::summarise(tpm = mean(tpm))  %>%
mutate(Genus = ifelse(is.na(Genus), Family, Genus))

Phosphonate_metabolism_Rhodobacterales_2 <- Phosphonate_metabolism_Rhodobacterales %>%
      # dplyr::filter(Category == "Phosphorus metabolism") %>%
  dplyr::group_by(Genus, Final_Taxonomy) %>%
  dplyr::summarise(tpm = mean(tpm))  


# 
# Paso 2: Filtrar los géneros más abundantes por Subcategory
# Por ejemplo, seleccionamos los 5 géneros más abundantes por Subcategory
top_genus <- Phosphonate_metabolism_Rhodobacterales_2 %>%
  dplyr::group_by(Final_Taxonomy) %>%
  top_n(4, tpm)  # Cambia el número (5) si quieres más o menos géneros

# Paso 3: Generar el gráfico con los géneros más abundantes
MetaTs_plot <- ggplot(top_genus, aes(y= tpm, x = Final_Taxonomy, fill = Genus)) +
  geom_bar(position = "fill", stat = "identity") +
  ggtitle("a) Metatranscriptomic Taxonomy Distribution") +
  labs(x = "", y = "", fill = "", col = "") +
  theme_bw(base_size = 8) +
  theme(plot.title = element_text(size = 10, face = "bold", hjust = 0.5),
        plot.subtitle = element_text(size = 8, hjust = 0), 
        plot.caption = element_text(size = 8, hjust = 0, vjust = 0),
        axis.title.y = element_blank(),
        axis.title.x = element_text(angle = 0, vjust = 0.5, face = "bold"),
        axis.text.x = element_text(angle = 0, vjust = 0.5, hjust = 0.5, size = 8, face = "bold"),
        axis.text.y = element_text(angle = 0, vjust = 0.5, hjust = 0.5, size = 8, face = "bold"),
        strip.text = element_text(size = 8), 
        strip.text.x = element_text(size = 8, angle = 0, face = "bold"),
        strip.text.y = element_text(size = 8, angle = 270, face = "bold"),
        strip.background = element_rect(colour = "black", fill = "white"),
        legend.text = element_text(size = 9), 
        legend.position = "right",
        legend.box = "horizontal",
        legend.margin = margin(t = -1, r = 0, b = 0, l = 0, unit = "cm"),
        legend.box.margin = margin(t = 0, r = 0, b = 0, l = 0, unit = "cm"),
        legend.spacing = unit(0.05, "cm"),
        legend.key.size = unit(0.2, "cm"),
        legend.key.height = unit(0.2, "cm"),
        legend.key.width = unit(0.3, "cm"),
        legend.title = element_blank()) +
  guides(fill = guide_legend(nrow = 42)) +
  scale_y_continuous(labels = scales::percent) +
    facet_nested( ~ Final_Taxonomy, scales = "free_x", labeller = label_wrap_gen(15)) +
  theme(panel.spacing = unit(0.2, "lines"))

MetaTs_plot



```

```{r, fig.height=7, fig.width=17}
library(dplyr)

Phosphonate_metabolism_Rhodobacterales <- Prok_INTERES_WP2_TPMs_2 %>%
      # dplyr::filter(Category == "Phosphorus metabolism") %>%
      dplyr::filter(Subcategory == "Phosphonate metabolism") %>%
  # dplyr::filter(gene_protein %in% c("phoA", "phoD")) %>%
  dplyr::filter(Final_Taxonomy %in% c ("Rhodobacterales")) %>%
  dplyr::group_by(Workpackage, treatment, time, replic, Subcategory, Family, Genus, Final_Taxonomy) %>%
  dplyr::summarise(tpm = sum(tpm)) %>%
  dplyr::group_by(Workpackage, treatment, time, Subcategory, Family, Genus, Final_Taxonomy) %>%
  dplyr::summarise(tpm = mean(tpm))  %>%
mutate(Genus = ifelse(is.na(Genus), Family, Genus))

Phosphonate_metabolism_Rhodobacterales_2 <- Phosphonate_metabolism_Rhodobacterales %>%
      # dplyr::filter(Category == "Phosphorus metabolism") %>%
  dplyr::group_by(Genus, Final_Taxonomy) %>%
  dplyr::summarise(tpm = mean(tpm))  


# 
# Paso 2: Filtrar los géneros más abundantes por Subcategory
# Por ejemplo, seleccionamos los 5 géneros más abundantes por Subcategory
top_genus <- Phosphonate_metabolism_Rhodobacterales_2 %>%
  dplyr::group_by(Final_Taxonomy) %>%
  top_n(4, tpm)  # Cambia el número (5) si quieres más o menos géneros

# Paso 3: Generar el gráfico con los géneros más abundantes
MetaTs_plot <- ggplot(top_genus, aes(y= tpm, x = Final_Taxonomy, fill = Genus)) +
  geom_bar(position = "fill", stat = "identity") +
  ggtitle("a) Metatranscriptomic Taxonomy Distribution") +
  labs(x = "", y = "", fill = "", col = "") +
  theme_bw(base_size = 8) +
  theme(plot.title = element_text(size = 10, face = "bold", hjust = 0.5),
        plot.subtitle = element_text(size = 8, hjust = 0), 
        plot.caption = element_text(size = 8, hjust = 0, vjust = 0),
        axis.title.y = element_blank(),
        axis.title.x = element_text(angle = 0, vjust = 0.5, face = "bold"),
        axis.text.x = element_text(angle = 0, vjust = 0.5, hjust = 0.5, size = 8, face = "bold"),
        axis.text.y = element_text(angle = 0, vjust = 0.5, hjust = 0.5, size = 8, face = "bold"),
        strip.text = element_text(size = 8), 
        strip.text.x = element_text(size = 8, angle = 0, face = "bold"),
        strip.text.y = element_text(size = 8, angle = 270, face = "bold"),
        strip.background = element_rect(colour = "black", fill = "white"),
        legend.text = element_text(size = 9), 
        legend.position = "right",
        legend.box = "horizontal",
        legend.margin = margin(t = -1, r = 0, b = 0, l = 0, unit = "cm"),
        legend.box.margin = margin(t = 0, r = 0, b = 0, l = 0, unit = "cm"),
        legend.spacing = unit(0.05, "cm"),
        legend.key.size = unit(0.2, "cm"),
        legend.key.height = unit(0.2, "cm"),
        legend.key.width = unit(0.3, "cm"),
        legend.title = element_blank()) +
  guides(fill = guide_legend(nrow = 42)) +
  scale_y_continuous(labels = scales::percent) +
    facet_nested( ~ Final_Taxonomy, scales = "free_x", labeller = label_wrap_gen(15)) +
  theme(panel.spacing = unit(0.2, "lines"))

MetaTs_plot



```

```{r, fig.height=9, fig.width=7}
Phosphorus_Genes <- P_Genes %>%
  group_by(Workpackage, treatment, time, replic, Subcategory, Domain) %>%
  dplyr::summarise(tpm = sum(tpm)) %>%
  group_by(Workpackage, treatment, time, Subcategory, Domain) %>%
  dplyr::summarise(mean=mean(tpm), errorstandar=std.error(tpm))


Phosphorus_Genes$Domain  <- factor(  Phosphorus_Genes$Domain,
                                                     levels = c("Prokaryotes","Eukaryotes"))

Phosphorus_Genes$Subcategory  <- factor(  Phosphorus_Genes$Subcategory,
                                                     levels = c("P starvation response",
                                                                "High affinity transporters",
                                                                "Low affinity transporters",
                                                                "Organic P hydrolysis",
                                                                "Phosphonate metabolism",
                                                                "Pi mobilization"))
```


```{r, fig.height=9, fig.width=7}
Phosphorus_Genes_tax <- P_Genes %>%
  group_by(Workpackage, treatment, time, replic, Category, Subcategory, Domain, Final_Taxonomy) %>%
  dplyr::summarise(tpm = sum(tpm)) %>%
  group_by(Workpackage, treatment, time, Category, Subcategory, Domain, Final_Taxonomy) %>%
  dplyr::summarise(tpm=mean(tpm))


Phosphorus_Genes_tax$Domain  <- factor(  Phosphorus_Genes_tax$Domain,
                                                     levels = c("Prokaryotes","Eukaryotes"))

Phosphorus_Genes_tax$Subcategory  <- factor(  Phosphorus_Genes_tax$Subcategory,
                                                     levels = c("P starvation response",
                                                                "High affinity transporters",
                                                                "Low affinity transporters",
                                                                "Organic P hydrolysis",
                                                                "Phosphonate metabolism",
                                                                "Pi mobilization"))

```



```{r}
# IMPORTANTE. Esta seccion es para añadir una letra a cada columna en funcion al pvalue.
# Tener en cuena que el orden es el original. No importa que determines un orden distinto con "data$col <- factor (data$col (level = c())) 
Phosphorus_Genes$label <- c(
                          # High affinity   Low affinity    Organic P.    P starvation    Phosphonate    Pi
                          # transporters    transporters    hydrolysis    response        metabolism     mobilization
                          # EUK   PROK      EUK   PROK      EUK   PROK    EUK   PROK      EUK   PROK     EUK   PROK
                            "a",  "a",      "a",  "a",      "a",  "a",    "a", "a",       "a", "a",      "a", "a", # CONTROL  O HORAS
                            "a",  "a",      "a",  "a",      "a",  "a",    "a", "a",       "a", "a",      "a", "a", # CONTROL  72 HORAS
                            "b",  "b",      "b",  "a",      "b",  "b",    "b", "b",       "b", "b",      "a", "ab", # RIO      0 HORAS
                            "b",  "b",      "b",  "b",      "b",  "b",    "b", "a",       "b", "b",      "a", "b", # RIO     72 HORAS
                            "c",  "c",      "c",  "b",      "c",  "c",    "c", "c",       "ab","a",      "a", "b", # RIO+P    0 HORAS
                            "b",  "c",      "c",  "c",      "c",  "c",    "b", "b",       "b", "c",      "b", "a"  # RIO+P   72 HORAS
                            ) # Ejemplo de etiquetas
# Crear el gráfico base
Phosphorus_Barplot <- ggplot(Phosphorus_Genes, aes(y=mean, x=treatment)) + 
  geom_errorbar(aes(ymin = mean - errorstandar, ymax = mean + errorstandar), width = 0.4, position = position_dodge(0.8)) +
  geom_bar(data = Phosphorus_Genes_tax, aes(fill = Final_Taxonomy, y = tpm, x = treatment), stat = "identity") + 
  geom_text(aes(label = label, y = mean + errorstandar * 0.85), position = position_dodge(0.8), vjust = -0.5) +  # Ajusta '0.1' según sea necesario para separar las etiquetas de los errores estándar
  labs(x="", y="(TPM)", fill="", col="") +
  theme_bw(base_size = 8) +
  theme(plot.title = element_text(size = 8, face = "bold", hjust = 0),
        plot.subtitle  = element_text(size = 8, hjust = 0), 
        plot.caption = element_text(size = 8, hjust = 0, vjust = 0),
        axis.title.y = element_text(angle = 90, vjust = 0.5, face = "bold"),
        axis.title.x = element_text(angle = 0, vjust = 0.5, face = "bold"),
        axis.text.x = element_text(angle = 0, vjust = 0.5, hjust = 0.5, size=8, face = "bold"),
        axis.text.y = element_text(angle = 0, vjust = 0.5, hjust = 0.5, size=8, face = "bold"),
        strip.text = element_text(size = 8), 
        strip.text.x = element_text(size=8, angle=0, face = "bold"),
        strip.text.y = element_text(size=8, angle=0, face = "bold"),
        strip.background = element_rect(colour="black", fill="white"),
        legend.text = element_text(size = 8), 
        legend.position = "right",
        legend.box = "horizontal",
        legend.spacing = unit(0.005, "cm"),
        legend.key.size = unit(0.2, "cm"),
        legend.key.height = unit(0.2, "cm"),
        legend.key.width = unit(0.2, "cm"), 
        legend.title = element_blank()) +
  guides(fill = guide_legend(override.aes = list(size=5), nrow = 41)) +
  scale_fill_manual(values = my.colors_All) +
  facet_nested(Subcategory ~ Domain + time, scales = "free_y", labeller = label_wrap_gen(15)) +
  theme(panel.spacing = unit(0.2, "lines")) +
  facetted_pos_scales(
    y = list(
      scale_y_continuous(limits = c(0, 2000), breaks = seq(0, 2000, by = 400)),   # P starvation response
      scale_y_continuous(limits = c(0, 7000), breaks = seq(0, 7000, by = 1400)),  # High affinity transporters
      scale_y_continuous(limits = c(0, 8500), breaks = seq(0, 8000, by = 1600)),  # Low affinity transporters
      scale_y_continuous(limits = c(0, 1250), breaks = seq(0, 1200, by = 240)),   # Organic P hydrolysis
      scale_y_continuous(limits = c(0, 210), breaks = seq(0, 200, by = 40)),      # Phosphonate metabolism
      # scale_y_continuous(limits = c(0, 320), breaks = seq(0, 320, by = 40)),      # Phosphonate metabolism
      scale_y_continuous(limits = c(0, 4000), breaks = seq(0, 4000, by = 800))    # Pi mobilization
    ))

# # 💾 Guardar
# png("../Results/WP2/Figure_3.png",
#     width = 18, height = 24, units = 'cm', res=600 )
# 
# # Mostrar el gráfico combinado
# Phosphorus_Barplot
# 
# # Imprime el gráfico final
# print(Phosphorus_Barplot)
# 
# # Cierra el dispositivo de gráficos
# dev.off()
# Phosphorus_Barplot


ggsave(
  filename = "../Results/WP2/Figure_3.pdf",
  plot     = Phosphorus_Barplot,
  width    = 18, height = 24, units = "cm",
  device   = cairo_pdf          # mejor para transparencias y texto
)
```



```{r}
Total_Phoshorus <- P_Genes %>%
  group_by(Workpackage, treatment, time, replic, Category, Domain) %>%
  dplyr::summarise(tpm = sum(tpm)) %>%
  group_by(Workpackage, treatment, time, Category, Domain) %>%
  dplyr::summarise(Total_P_mean=mean(tpm), errorstandar=std.error(tpm)) %>%
ungroup()

Total_Phoshorus$Domain  <- factor(  Total_Phoshorus$Domain,
                                                     levels = c("Prokaryotes","Eukaryotes"))

Phosphorus_Barplot <- ggplot(Total_Phoshorus, aes(y=Total_P_mean, x=treatment)) + 
  geom_errorbar(aes(ymin = Total_P_mean - errorstandar, ymax = Total_P_mean + errorstandar), width = 0.4, position = position_dodge(0.8)) +
  geom_bar(data = Total_Phoshorus, aes(fill = treatment, y = Total_P_mean, x = treatment), stat = "identity") + 
  
  labs(x="", y="(TPM)", fill="", col="") +
  theme_bw(base_size = 8) +
  theme(plot.title = element_text(size = 8, face = "bold", hjust = 0),
        plot.subtitle  = element_text(size = 8, hjust = 0), 
        plot.caption = element_text(size = 8, hjust = 0, vjust = 0),
        axis.title.y = element_text(angle = 90, vjust = 0.5, face = "bold"),
        axis.title.x = element_text(angle = 0, vjust = 0.5, face = "bold"),
        axis.text.x = element_text(angle = 0, vjust = 0.5, hjust = 0.5, size=8, face = "bold"),
        axis.text.y = element_text(angle = 0, vjust = 0.5, hjust = 0.5, size=8, face = "bold"),
        strip.text = element_text(size = 8), 
        strip.text.x = element_text(size=8, angle=0, face = "bold"),
        strip.text.y = element_text(size=8, angle=0, face = "bold"),
        strip.background = element_rect(colour="black", fill="white"),
        legend.text = element_text(size = 8), 
        legend.position = "right",
        legend.box = "horizontal",
        legend.spacing = unit(0.005, "cm"),
        legend.key.size = unit(0.2, "cm"),
        legend.key.height = unit(0.2, "cm"),
        legend.key.width = unit(0.2, "cm"), 
        legend.title = element_blank()) +
    scale_fill_manual(values=c("royalblue3", "deepskyblue3", "darkorchid3" )) +
  facet_nested( ~ Category + Domain + time, scales = "free_y", labeller = label_wrap_gen(30)) +
  theme(panel.spacing = unit(0.2, "lines")) 
Phosphorus_Barplot

```

```{r, fig.height=9, fig.width=7}
Phosphorus_Subcategory <- P_Genes %>%
  group_by(Workpackage, treatment, time, replic, Category, Subcategory, Domain) %>%
  dplyr::summarise(tpm = sum(tpm)) %>%
  group_by(Workpackage, treatment, time, Category, Subcategory, Domain) %>%
  dplyr::summarise(SubCat_mean=mean(tpm), errorstandar=std.error(tpm))%>%
ungroup()

Phosphorus_Subcategory$Domain  <- factor(  Phosphorus_Subcategory$Domain,
                                                     levels = c("Prokaryotes","Eukaryotes"))

Phosphorus_Barplot <- ggplot(Phosphorus_Subcategory, aes(y=SubCat_mean, x=treatment)) + 
  geom_errorbar(aes(ymin = SubCat_mean - errorstandar, ymax = SubCat_mean + errorstandar), width = 0.4, position = position_dodge(0.8)) +
  geom_bar(data = Phosphorus_Subcategory, aes(fill = treatment, y = SubCat_mean, x = treatment), stat = "identity") + 
  
  labs(x="", y="(TPM)", fill="", col="") +
  theme_bw(base_size = 8) +
  theme(plot.title = element_text(size = 8, face = "bold", hjust = 0),
        plot.subtitle  = element_text(size = 8, hjust = 0), 
        plot.caption = element_text(size = 8, hjust = 0, vjust = 0),
        axis.title.y = element_text(angle = 90, vjust = 0.5, face = "bold"),
        axis.title.x = element_text(angle = 0, vjust = 0.5, face = "bold"),
        axis.text.x = element_text(angle = 0, vjust = 0.5, hjust = 0.5, size=8, face = "bold"),
        axis.text.y = element_text(angle = 0, vjust = 0.5, hjust = 0.5, size=8, face = "bold"),
        strip.text = element_text(size = 8), 
        strip.text.x = element_text(size=8, angle=0, face = "bold"),
        strip.text.y = element_text(size=8, angle=0, face = "bold"),
        strip.background = element_rect(colour="black", fill="white"),
        legend.text = element_text(size = 8), 
        legend.position = "right",
        legend.box = "horizontal",
        legend.spacing = unit(0.005, "cm"),
        legend.key.size = unit(0.2, "cm"),
        legend.key.height = unit(0.2, "cm"),
        legend.key.width = unit(0.2, "cm"), 
        legend.title = element_blank()) +
      scale_fill_manual(values=c("royalblue3", "deepskyblue3", "darkorchid3", 
                                 "royalblue3", "deepskyblue3", "darkorchid3", 
                                 "royalblue3", "deepskyblue3", "darkorchid3", 
                                 "royalblue3", "deepskyblue3", "darkorchid3", 
                                 "royalblue3", "deepskyblue3", "darkorchid3", 
                                 "royalblue3", "deepskyblue3", "darkorchid3" 
                                 )) +
  guides(fill = guide_legend(override.aes = list(size=5), nrow = 41)) +
  facet_nested(Subcategory ~ Category + Domain + time, scales = "free_y", labeller = label_wrap_gen(30)) +
  theme(panel.spacing = unit(0.2, "lines")) 
Phosphorus_Barplot


```

```{r, fig.height=8, fig.width=6}

Sobcategory_proportions <- Phosphorus_Subcategory %>%
  dplyr::select(-Category, -errorstandar) %>%
  left_join(Total_Phoshorus, by = c("Workpackage", "treatment", "time", "Domain"))%>%
  dplyr::select(-Category, -errorstandar) %>%
  group_by(Domain, Workpackage, treatment, time, Subcategory) %>%
  mutate(Proportion =(SubCat_mean/Total_P_mean)*100)

# Paleta colorblind-friendly (Okabe & Ito) 
# colors <- c(
#   "High affinity transporters" = "#CC79A7",
#   "High affinity\ntransporters" = "#CC79A7",
#   "Low affinity transporters" = "#D55E00",
#   "Low affinity\ntransporters" = "#D55E00",
#   "Organic P hydrolysis" = "#F0E442",
#   "Organic P\nhydrolysis" = "#F0E442",
#   "P starvation response" = "#009E73",
#   "P starvation\nresponse" = "#009E73",
#   "Phosphonate metabolism" = "#E69F00",
#   "Phosphonate\nmetabolism" = "#E69F00",
#   "Pi mobilization" = "#56B4E9",
#   "Pi\nmobilization" = "#56B4E9"
# )
# Definir colores estandar
colors <- c(
  "High affinity transporters" = "plum3",
  "High affinity\ntransporters" = "plum3",
  "Low affinity transporters" = "slateblue1",
  "Low affinity\ntransporters" = "slateblue1",
  "Organic P hydrolysis" = "turquoise3",
  "Organic P\nhydrolysis" = "turquoise3",
  "P starvation response" = "aquamarine1",
  "P starvation\nresponse" = "aquamarine1",
  "Phosphonate metabolism" = "aquamarine3",
  "Phosphonate\nmetabolism" = "aquamarine3",
  "Pi mobilization" = "lightsteelblue1",
  "Pi\nmobilization" = "lightsteelblue1"
)

Sobcategory_proportions$Domain  <- factor(  Sobcategory_proportions$Domain,
                                                     levels = c("Prokaryotes","Eukaryotes"))

Sobcategory_proportions$Subcategory  <- factor(  Sobcategory_proportions$Subcategory,
                                                     levels = c("P starvation response",
                                                                "High affinity transporters",
                                                                "Low affinity transporters",
                                                                "Organic P hydrolysis",
                                                                "Phosphonate metabolism",
                                                                "Pi mobilization"))

Sobcategory_proportions$Subcategory <- factor(Sobcategory_proportions$Subcategory, levels = c(
                             
                                                                 "P starvation response",
                                                                 "High affinity transporters",
                                                                 "Low affinity transporters",
                                                                 "Organic P hydrolysis",
                                                                 "Phosphonate metabolism",
                                                                 "Pi mobilization"),
                  labels = c(
                                                                 "P starvation\nresponse",
                                                                 "High affinity\ntransporters",
                                                                 "Low affinity\ntransporters",
                                                                 "Organic P\nhydrolysis",
                                                                 "Phosphonate\nmetabolism",
                                                                 "Pi\nmobilization"))




Sobcat_proportions_plot <- ggplot(Sobcategory_proportions, aes(y=Proportion, x=treatment, fill=Subcategory)) +
    geom_bar(position="fill", stat="identity") + #, color ="black"
geom_text(aes(label = ifelse(Proportion > 1, sprintf("%.2f", Proportion), "")), 
          position = position_fill(vjust = 0.5), size =2, face = "bold") +
ggtitle ("")+
    labs(x="", y="", fill="", col="") +
    theme_bw(base_size = 8) +
theme(
    plot.title = element_text(size = 10, face = "bold", hjust = 0.5), # Configura el título del gráfico
    plot.subtitle  = element_text(size = 8, hjust = 0), # Configura el subtítulo 
    plot.caption = element_text(size = 8, hjust = 0, vjust = 0), # Configura el texto del pie de gráfico 
    axis.title.y = element_blank(),  # Elimina el título del eje Y.
    axis.title.x = element_text(angle = 0, vjust = 0.5, face = "bold"),  # Configura el título del eje X
    axis.text.x = element_text(angle = 0, vjust = 0.5, hjust = 0.5, size=8, face = "bold"),  # Configura las etiquetas del eje X 
    axis.text.y = element_text(angle = 0, vjust = 0.5, hjust = 0.5, size=8, face = "bold"),  # Configura las etiquetas del eje Y 
    strip.text = element_text(size = 8),  # Configura el texto de los *facets*
    strip.text.x = element_text(size=8, angle=0, face = "bold"),  # Configura el texto de los *facets* en el eje X
    strip.text.y = element_text(size=8, angle=270, face = "bold"),  # Configura el texto de los *facets* en el eje Y 
    strip.background = element_rect(colour="black", fill="white"),  # Define el fondo de los *facets* 
    legend.text = element_text(size = 8),  # Configura el tamaño del texto de la leyenda
    # legend.title = element_blank(),  # Elimina el título de la leyenda
    # legend.position = "right",  # Ubica la leyenda 
    legend.margin = margin(t = 0.1, r = 0.2, b = 1.5, l = 0.05, unit = "cm"),  # Define el margen exterior de la leyenda
    # legend.box = "horizontal",  # Hace que la leyenda se organice en una caja horizontal
    # legend.box.spacing = unit(1, "cm"),  #  Espacio entre múltiples leyendas si existen
    # legend.spacing.y = unit(10, "cm"),  #  Espacio entre categorías en la leyenda
    # legend.spacing.x = unit(5, "cm"),  #  Espacio horizontal entre los elementos dentro de la leyenda
    # legend.key = element_rect(color = NA, fill = NA),  # Hace que los cuadros de la leyenda sean transparentes
    # legend.key.size = unit(1, "cm"),  # Ajusta el tamaño general del cuadro de color
    legend.key.height = unit(2, "cm"),  # Ajusta la altura de los cuadros de la leyenda
    # legend.key.width = unit(1.2, "cm"),  # Ajusta el ancho de los cuadros de la leyenda
    # legend.key.spacing = unit(2, "cm"),  # Espaciado dentro de una categoría en la leyenda
    panel.spacing = unit(0.2, "lines")  #  Espaciado entre paneles en *facets*
) +

      guides(fill = guide_legend(ncol = 1)) +
    scale_fill_manual(values = colors) +
    scale_y_continuous(labels = scales::percent) +
facet_nested( ~ Domain+time, scales = "free")

# 💾 Guardar
png("../Results/WP2/Supplementary/Supplementary_Figure_3.png",
    width = 18, height = 14, units = 'cm', res=600 )

# Mostrar el gráfico combinado
Sobcat_proportions_plot

# Imprime el gráfico final
print(Sobcat_proportions_plot)

# Cierra el dispositivo de gráficos
dev.off()
Sobcat_proportions_plot


```


```{r}
INTERES_Prok_DGE <- read_parquet("../Data Frames/WP2/INTERES_Prok_WP2_DGE.parquet") %>%
    unite(orf, Final_Taxonomy, orf,  sep = "_", remove = F)%>%
  # left_join(Hiper_modules, by="KEGG_Module") %>%
  mutate(Final_Taxonomy = ifelse(Final_Taxonomy == "Bacteria", "Other prokaryotes", Final_Taxonomy))%>%
  mutate(Final_Taxonomy = ifelse(Final_Taxonomy == "Proteobacteria", "Other prokaryotes", Final_Taxonomy))%>%
  mutate(Final_Taxonomy = ifelse(Final_Taxonomy == "Pelagibacterales", "Alphaproteobacteria", Final_Taxonomy))%>%
  mutate(Final_Taxonomy = ifelse(Final_Taxonomy == "Alphaproteobacteria", "Alphaproteobacteria", Final_Taxonomy))%>%
  mutate(Final_Taxonomy = ifelse(Final_Taxonomy == "Gammaproteobacteria", "Gammaproteobacteria", Final_Taxonomy))%>%
  mutate(Final_Taxonomy = ifelse(Final_Taxonomy == "No domain", "Other prokaryotes", Final_Taxonomy))




INTERES_Prok_DGE$Final_Taxonomy  <- factor(  INTERES_Prok_DGE$Final_Taxonomy,
                                                     levels = c("Other prokaryotes",
                                                                 "Archaea",
                                                                 "Planctomycetota",
                                                                 "Actinobacteriota",
                                                                 "Cyanobacteria",
                                                                 "Firmicutes",
                                                                 "Flavobacteriales", # Protista
                                                                 "Bacteroidota", # Protista
                                                                 "SAR86",
                                                                 "Pseudomonadales",
                                                                 "Enterobacterales",
                                                                 "Burkholderiales", 
                                                                 "Beggiatoales",
                                                                "Gammaproteobacteria",
                                                                 "Rhizobiales",
                                                                 "Puniceispirillales", 
                                                                 "Rhodobacterales", 
                                                                "Alphaproteobacteria"))


INTERES_Prok_DGE$comparation  <- factor(  INTERES_Prok_DGE$comparation,
                                                      levels =  c(" C  vs R-0h",
                                                                  "C vs R+P-0h",
                                                                  "R vs R+P-0h",
                                                                  " C  vs R-72h",
                                                                  "C vs R+P-72h",
                                                                  "R vs R+P-72h"))


```





```{r fig.height=18, fig.width=25}
INTERES_Prok_DGE_1 <- INTERES_Prok_DGE %>%
    mutate(KEGG_ko2 = str_remove(KEGG_ko2, 'ko:'))%>%
    mutate(KEGG_ko3 = str_remove(KEGG_ko3, 'ko:'))%>%
    dplyr::filter(KEGG_ko !="NA") %>% 
    dplyr::filter(KEGG_ko !="-")


```


```{r fig.height=18, fig.width=25}
# # Filtrar primero por KEGG_ko presente en Hiper_proteins
# filtered_KEGG_ko1 <- INTERES_Prok_DGE_1 %>%
#   filter(KEGG_ko %in% Hiper_proteins$KEGG_ko) %>%
#   mutate(KEGG_ko = KEGG_ko)  # Mantener la columna KEGG_ko como está
# 
# # Filtrar por KEGG_ko2 solo si KEGG_ko no está presente en Hiper_proteins y renombrar a KEGG_ko
# filtered_KEGG_ko2 <- INTERES_Prok_DGE_1 %>%
#   filter(!(KEGG_ko %in% Hiper_proteins$KEGG_ko) & KEGG_ko2 %in% Hiper_proteins$KEGG_ko) %>%
#   mutate(KEGG_ko = KEGG_ko2)  # Crear una nueva columna KEGG_ko con el valor de KEGG_ko2
# 
# # Filtrar por KEGG_ko3 solo si KEGG_ko y KEGG_ko2 no están presentes en Hiper_proteins y renombrar a KEGG_ko
# filtered_KEGG_ko3 <- INTERES_Prok_DGE_1 %>%
#   filter(!(KEGG_ko %in% Hiper_proteins$KEGG_ko) &
#          !(KEGG_ko2 %in% Hiper_proteins$KEGG_ko) &
#           KEGG_ko3 %in% Hiper_proteins$KEGG_ko) %>%
#   mutate(KEGG_ko = KEGG_ko3)  # Crear una nueva columna KEGG_ko con el valor de KEGG_ko3
# 
# # Combinar todos los resultados y eliminar duplicados
# INTERES_Prok_DGE_1 <- bind_rows(filtered_KEGG_ko1, filtered_KEGG_ko2, filtered_KEGG_ko3) %>%
#   distinct()  # Eliminar cualquier fila duplicada que pudiera aparecer


Prok_DGE_INTERES_Selected_Genes <- INTERES_Prok_DGE_1 %>%
  left_join(Hiper_proteins, by="KEGG_ko") %>% 
  filter(KEGG_ko %in% Hiper_proteins$KEGG_ko) %>% #################### Es aqui donde filtramos las poteinas/genes OBJETIVO.
      dplyr::filter(!kingdom %in% c("Eukarya")) %>%
      dplyr::filter(!KEGG_ko %in% c("K06163", "K00819", "K00459")) %>%
  # filter(Category %in% c("Phosphorus metabolism", #
  #                        "Nitrogen metabolism")) %>%
  unite(gene_KEGG, gene_protein, KEGG_ko, sep = " ", remove=F) %>%
    separate(comparation, c("comparation", "Time"), sep="-", remove=T) %>%
    dplyr::filter(gene_protein !="rocD*")  


Prok_DGE_INTERES_Selected_Genes$Subcategory  <- factor(  Prok_DGE_INTERES_Selected_Genes$Subcategory,
                                                     levels = c("P starvation response",
                                                                "High affinity transporters",
                                                                "Low affinity transporters",
                                                                "Organic P hydrolysis",
                                                                "Phosphonate metabolism",
                                                                "Pi mobilization"))
```

```{r}

```



```{r}
INTERES_Prok_DGE <- read_parquet("../Data Frames/WP2/INTERES_Prok_WP2_DGE.parquet")
INTERES_polyA_DGE <- read_parquet("../Data Frames/WP2/INTERES_Euk_WP2_DGE.parquet")

INTERES_Prok_DGE$transparency <- ifelse(INTERES_Prok_DGE$PValue <= 0.05 & # More than 0.05p (No significant)
                               INTERES_Prok_DGE$logFC >= -1 & # Between 0 and -1.9 of logFC
                               INTERES_Prok_DGE$logFC <= 1, # And under 1.9 of logFC
                               0.1, # Set as 10% of the alpha (90% transparency)
                        ifelse(INTERES_Prok_DGE$PValue >= 0.05 & # Less than 0.05p (Significant)
                               (INTERES_Prok_DGE$logFC <= 1 | # More than 1.9 of logFC
                               INTERES_Prok_DGE$logFC >= -1), # And above -1.9 of logFC
                               0.1,1)) # Set as 100% of the alpha (0% transparency)


INTERES_Prok_DGE_plot <- INTERES_Prok_DGE %>%
  mutate(significant = ifelse(FDR <= 0.05, TRUE, FALSE)) %>%
      mutate(Label = "Prokaryotes")  %>%
      separate(comparation, c("comparation", "Time"), sep="-", remove=T) %>%

  ggplot(aes(y = logCPM, x = logFC, colour = FDR, shape = significant)) +
    annotate("rect", xmin = -Inf, xmax = 0, ymin = -Inf, ymax = Inf, fill = "dimgrey", alpha = 0.3) +
  annotate("rect", xmin = 0, xmax = Inf, ymin = -Inf, ymax = Inf, fill = "snow3", alpha = 0.3)+
  geom_point(alpha = INTERES_Prok_DGE$transparency) +
  scale_colour_viridis_c('FDR') +
  facet_nested(Time ~ Label + comparation) +
  # theme(legend.position = 'top' ) +
  #       labs(caption = str_wrap(
  #   "Volcano plot. ", 75)) +
    theme_bw(base_size = 8) +
    guides(shape = "none") +  # 🔥 También asegura que shape se oculta
    theme(plot.title = element_text(size = 8, face = "bold", hjust = 0),
        plot.subtitle = element_text(size = 8, hjust = 0), 
        plot.caption = element_text(size = 8, hjust = 0, vjust = 0),
        axis.title.y = element_text(angle = 90, vjust = 0.5, face = "bold"),
        axis.title.x = element_text(angle = 0, vjust = 0.5, face = "bold"),
        axis.text.x = element_text(angle = 0, vjust = 0.5, hjust = 0.5, size = 8, face = "bold"),
        axis.text.y = element_text(angle = 0, vjust = 0.5, hjust = 0.5, size = 8, face = "bold"),
        strip.text = element_text(size = 8), 
        strip.text.x = element_text(size = 8, angle = 0, face = "bold"),
        strip.text.y = element_text(size = 8, angle = 0, face = "bold"),
        strip.background = element_rect(colour = "black", fill = "white"),
        legend.text = element_text(size = 8), # Incrementar el tamaño del texto de la leyenda
        legend.position = c(1, 1),
        legend.justification = c("right", "top"),
        legend.box = "vertical",
        legend.margin = margin(t = 0, r = 0, b = 0, l = 0, unit = "cm"),
        legend.box.margin = margin(t = 0, r = 0, b = 0, l = 0, unit = "cm"),
        legend.spacing = unit(0.005, "cm"),
        legend.key.size = unit(0.3, "cm"),
        legend.key.height = unit(0.3, "cm"),
        legend.key.width = unit(0.3, "cm"),
        legend.background = element_rect(
          fill = "snow3"),           # grosor del contorno
        panel.spacing = unit(0.2, "lines")) 
INTERES_Prok_DGE_plot
```


```{r}
INTERES_polyA_DGE$transparency <- ifelse(INTERES_polyA_DGE$PValue <= 0.05 & # More than 0.05p (No significant)
                               INTERES_polyA_DGE$logFC >= -1 & # Between 0 and -1.9 of logFC
                               INTERES_polyA_DGE$logFC <= 1, # And under 1.9 of logFC
                               0.1, # Set as 10% of the alpha (90% transparency)
                        ifelse(INTERES_polyA_DGE$PValue >= 0.05 & # Less than 0.05p (Significant)
                               (INTERES_polyA_DGE$logFC <= 1 | # More than 1.9 of logFC
                               INTERES_polyA_DGE$logFC >= -1), # And above -1.9 of logFC
                               0.1,1)) # Set as 100% of the alpha (0% transparency)


INTERES_polyA_DGE_plot <- INTERES_polyA_DGE %>%
  mutate(significant = ifelse(FDR <= 0.05, TRUE, FALSE)) %>%
      mutate(Label = "Eukaryotes")  %>%
      separate(comparation, c("comparation", "Time"), sep="-", remove=T) %>%

  ggplot(aes(y = logCPM, x = logFC, colour = FDR, shape = significant)) +
    annotate("rect", xmin = -Inf, xmax = 0, ymin = -Inf, ymax = Inf, fill = "dimgrey", alpha = 0.3) +
  annotate("rect", xmin = 0, xmax = Inf, ymin = -Inf, ymax = Inf, fill = "snow3", alpha = 0.3)+
  geom_point(alpha = INTERES_polyA_DGE$transparency) +
  scale_colour_viridis_c('FDR') +
  facet_nested(Time ~ Label + comparation) +
  # theme(legend.position = 'top' ) +
  #       labs(caption = str_wrap(
  #   "Volcano plot. ", 75)) +
    theme_bw(base_size = 8) +
    guides(colour = "none") +  # 🔥 También asegura que shape se oculta
    theme(plot.title = element_text(size = 8, face = "bold", hjust = 0),
        plot.subtitle = element_text(size = 8, hjust = 0), 
        plot.caption = element_text(size = 8, hjust = 0, vjust = 0),
        axis.title.y = element_text(angle = 90, vjust = 0.5, face = "bold"),
        axis.title.x = element_text(angle = 0, vjust = 0.5, face = "bold"),
        axis.text.x = element_text(angle = 0, vjust = 0.5, hjust = 0.5, size = 8, face = "bold"),
        axis.text.y = element_text(angle = 0, vjust = 0.5, hjust = 0.5, size = 8, face = "bold"),
        strip.text = element_text(size = 8), 
        strip.text.x = element_text(size = 8, angle = 0, face = "bold"),
        strip.text.y = element_text(size = 8, angle = 0, face = "bold"),
        strip.background = element_rect(colour = "black", fill = "white"),
        legend.text = element_text(size = 8), # Incrementar el tamaño del texto de la leyenda
        legend.position = c(1, 1),
        legend.justification = c("right", "top"),
        legend.box = "vertical",
        legend.margin = margin(t = 0, r = 0, b = 0, l = 0, unit = "cm"),
        legend.box.margin = margin(t = 0, r = 0, b = 0, l = 0, unit = "cm"),
        legend.spacing = unit(0.005, "cm"),
        legend.key.size = unit(0.3, "cm"),
        legend.key.height = unit(0.3, "cm"),
        legend.key.width = unit(0.3, "cm"),
        legend.background = element_rect(
          fill = "snow3"),           # grosor del contorno
        panel.spacing = unit(0.2, "lines")) 
INTERES_polyA_DGE_plot
#
```


```{r}
# 📚 Cargar la librería patchwork
library(patchwork)

# 📌 Unir las cuatro gráficas en dos columnas
combined_plot <- (INTERES_Prok_DGE_plot / INTERES_polyA_DGE_plot)




# 💾 Guardar
png("../Results/WP2/Supplementary/Supplementary_Figure_2.png",
    width = 18, height = 24, units = 'cm', res=600 )

# Mostrar el gráfico combinado
combined_plot

# Imprime el gráfico final
print(combined_plot)

# Cierra el dispositivo de gráficos
dev.off()
combined_plot
```


```{r} 
#                                                                         !! Revisar !!
# Hsta aqui todo esta Hecho  
# DEBERIAMOS USAR EL OTRO ARCHIVO 
INTERES_polyA_DGE <- read_parquet("../Data Frames/WP2/INTERES_Euk_WP2_DGE.parquet") %>%
    unite(YOrdenation, Final_Taxonomy, geneid,  sep = "_", remove = F)%>%
  # left_join(Hiper_modules, by="KEGG_Module")%>%
# mutate(KEGG_pathway = ifelse(is.na(KEGG_pathway), "Unknown", KEGG_pathway)) %>%
  mutate(Final_Taxonomy = ifelse(Final_Taxonomy == "Eukaryota", "Other eukaryotes", Final_Taxonomy))%>%
  mutate(Final_Taxonomy = ifelse(Final_Taxonomy == "Alveolata", "Other eukaryotes", Final_Taxonomy))%>%
  mutate(Final_Taxonomy = ifelse(Final_Taxonomy == "Opisthokonta", "Other eukaryotes", Final_Taxonomy))%>%
  mutate(Final_Taxonomy = ifelse(Final_Taxonomy == "Ciliophora", "Other eukaryotes", Final_Taxonomy))%>%
  mutate(Final_Taxonomy = ifelse(Final_Taxonomy == "Dinophyceae", "Dinoflagellata", Final_Taxonomy))%>%
  mutate(Final_Taxonomy = ifelse(Final_Taxonomy == "Sagenista", "Stramenopiles", Final_Taxonomy))%>%
  mutate(Final_Taxonomy = ifelse(Final_Taxonomy == "Rhodophyta", "Other eukaryotes", Final_Taxonomy))%>%
  mutate(Final_Taxonomy = ifelse(Final_Taxonomy == "Micromonas", "Chlorophyta", Final_Taxonomy))%>%
  mutate(Final_Taxonomy = ifelse(Final_Taxonomy == "Ostreococcus", "Chlorophyta", Final_Taxonomy))%>%
  mutate(Final_Taxonomy = ifelse(Final_Taxonomy == "Peridinium", "Peridiniales", Final_Taxonomy))%>%
  mutate(Final_Taxonomy = ifelse(Final_Taxonomy == "Scrippsiella", "Peridiniales", Final_Taxonomy))





INTERES_polyA_DGE$Final_Taxonomy  <- factor(  INTERES_polyA_DGE$Final_Taxonomy,
                                                levels =  c("Other eukaryotes",
                                                            "Opisthokonta",
                                                            "Rhizaria",
                                                            "Hacrobia",
                                                            "Amoebozoa",
                                                            "Chlorophyta",
                                                            "Glaucophyta",
                                                            "Archaeplastida",
                                                            "Pseudo-nitzschia",
                                                            "Skeletonema",
                                                            "Chaetoceros",
                                                            "Thalassiosira",
                                                            "Bacillariophyta",
                                                            "Ochrophyta",
                                                            "Stramenopiles",
                                                            "Syndiniales",
                                                            "Symbiodinium",
                                                            "Suessiales", 
                                                            "Peridiniales",
                                                            "Gymnodiniales",
                                                            "Alexandrium",
                                                            "Gonyaulacales",
                                                            "Dinoflagellata",
                                                            "Tintinnida",
                                                            "Choreotrichida",
                                                            "Spirotrichea"))



INTERES_polyA_DGE$comparation  <- factor(  INTERES_polyA_DGE$comparation, 
                                                      levels =  c(" C  vs R-0h",
                                                                  "C vs R+P-0h",
                                                                  "R vs R+P-0h",
                                                                  " C  vs R-72h",
                                                                  "C vs R+P-72h",
                                                                  "R vs R+P-72h"))


```
                                           


```{r}
INTERES_polyA_DGE_1 <- INTERES_polyA_DGE %>%
    # dplyr::filter(Final_Taxonomy !="NA") %>%
    dplyr::filter(KEGG_ko !="NA") %>% 
    dplyr::filter(KEGG_ko !="-") 



# # Filtrar primero por KEGG_ko presente en Hiper_proteins
# filtered_KEGG_ko1 <- INTERES_polyA_DGE_1 %>%
#   filter(KEGG_ko %in% Hiper_proteins$KEGG_ko) %>%
#   mutate(KEGG_ko = KEGG_ko)  # Mantener la columna KEGG_ko como está
# 
# # Filtrar por KEGG_ko2 solo si KEGG_ko no está presente en Hiper_proteins y renombrar a KEGG_ko
# filtered_KEGG_ko2 <- INTERES_polyA_DGE_1 %>%
#   filter(!(KEGG_ko %in% Hiper_proteins$KEGG_ko) & KEGG_ko2 %in% Hiper_proteins$KEGG_ko) %>%
#   mutate(KEGG_ko = KEGG_ko2)  # Crear una nueva columna KEGG_ko con el valor de KEGG_ko2
# 
# # Filtrar por KEGG_ko3 solo si KEGG_ko y KEGG_ko2 no están presentes en Hiper_proteins y renombrar a KEGG_ko
# filtered_KEGG_ko3 <- INTERES_polyA_DGE_1 %>%
#   filter(!(KEGG_ko %in% Hiper_proteins$KEGG_ko) &
#          !(KEGG_ko2 %in% Hiper_proteins$KEGG_ko) &
#           KEGG_ko3 %in% Hiper_proteins$KEGG_ko) %>%
#   mutate(KEGG_ko = KEGG_ko3)  # Crear una nueva columna KEGG_ko con el valor de KEGG_ko3
# 
# # Combinar todos los resultados y eliminar duplicados
# INTERES_polyA_DGE_1 <- bind_rows(filtered_KEGG_ko1, filtered_KEGG_ko2, filtered_KEGG_ko3) %>%
#   distinct()  # Eliminar cualquier fila duplicada que pudiera aparecer


PolyA_DGE_INTERES_Selected_Genes <- INTERES_polyA_DGE_1 %>%
  left_join(Hiper_proteins, by="KEGG_ko") %>% 
  filter(KEGG_ko %in% Hiper_proteins$KEGG_ko) %>% #################### Es aqui donde filtramos las poteinas/genes OBJETIVO.
      dplyr::filter(!kingdom %in% c("Bacteria", "Archaea")) %>%
      # dplyr::filter(!KEGG_ko %in% c("K06163", "K00819", "K00459")) %>%
  # filter(Category %in% c("Phosphorus metabolism", #
  #                        "Nitrogen metabolism")) %>%
  unite(gene_KEGG, gene_protein, KEGG_ko, sep = " ", remove=F) %>%
    separate(comparation, c("comparation", "Time"), sep="-", remove=T) %>%
    dplyr::filter(gene_protein !="rocD*")  



PolyA_DGE_INTERES_Selected_Genes$Subcategory  <- factor(  PolyA_DGE_INTERES_Selected_Genes$Subcategory,
                                                     levels = c("P starvation response",
                                                                "High affinity transporters",
                                                                "Low affinity transporters",
                                                                "Organic P hydrolysis",
                                                                "Phosphonate metabolism",
                                                                "Pi mobilization"))
```


```{r, fig.height=7, fig.width=7}
set.seed(123)

Prok_logCPM = 1

 

Phosphorus_DGE_sig <- Prok_DGE_INTERES_Selected_Genes %>%
  filter(Category == "Phosphorus metabolism") 
# write.csv(Phosphorus_DGE_sig, "../Data Frames/WP2/Prok_DGE_INTERES_Selected_Genes.csv")

Phosphorus_DGE_sig <- Prok_DGE_INTERES_Selected_Genes %>%
  filter(Category == "Phosphorus metabolism") %>% # & 
  filter(gene_protein %in% c("pstA", "pstB", "pstC", "pstS", 
                             "nptA", "pit", 
                             "acp5", "phoA", "phoD",  
                             "phoB", "phoR", "phoU", 
                             "phnC", "phnD", "phnE", 
                             "ppA", "ppK1")) %>% #
  arrange(factor(Final_Taxonomy, levels= levels(.$Final_Taxonomy)))%>%
  mutate(orf=forcats::fct_inorder(orf))


# Set the transparenci 
Phosphorus_DGE_sig$transparency <- ifelse(Phosphorus_DGE_sig$logCPM <= Prok_logCPM, 
                                          0.1, # Set as 10% of the alpha (90% transparency) if logCPM is less than 2
                                          ifelse(Phosphorus_DGE_sig$PValue < 0.05 & # Significant PValue
                                                   Phosphorus_DGE_sig$logFC > -2 & # logFC between -2 and 2
                                                   Phosphorus_DGE_sig$logFC < 2, 
                                                 0.1, # Set as 10% of the alpha (90% transparency)
                                                 ifelse(Phosphorus_DGE_sig$PValue > 0.05 & # Non-significant PValue
                                                          (Phosphorus_DGE_sig$logFC < 2 | # logFC less than 2
                                                             Phosphorus_DGE_sig$logFC > -2), # logFC greater than -2
                                                        0.05, 1))) # Set as 100% of the alpha (0% transparency)





# # 💾 Guardar
# png("../Results/WP2/Figure_4.png",
#     width = 18, height = 24, units = 'cm', res=600 )


Phosphorus_DGE_sig$Final_Taxonomy <- factor(Phosphorus_DGE_sig$Final_Taxonomy, 
                                             levels = rev(levels(Phosphorus_DGE_sig$Final_Taxonomy)))

Phosphorus_DGE_sig_plot <- ggplot(Phosphorus_DGE_sig, aes(y=orf, x=logFC, size=logCPM, fill = Final_Taxonomy, alpha = transparency)) + 
  annotate("rect", xmin = -Inf, xmax = 0, ymin = -Inf, ymax = Inf, fill = "dimgrey", alpha = 0.3) +
  annotate("rect", xmin = 0, xmax = Inf, ymin = -Inf, ymax = Inf, fill = "snow3", alpha = 0.3)+
  geom_point(alpha = Phosphorus_DGE_sig$transparency, shape = 21) +
  geom_vline(xintercept = 0) +
  labs(x = "(logFC)", y = "", fill = "", size = "logCPM") +
  theme_bw(base_size = 8) +
  theme(plot.title = element_text(size = 8, face = "bold", hjust = 0),
        plot.subtitle = element_text(size = 8, hjust = 0), 
        plot.caption = element_text(size = 8, hjust = 0, vjust = 0),
        axis.title.y = element_blank(),
        axis.title.x = element_text(angle = 0, vjust = 0.5, face = "bold"),
        axis.text.x = element_text(angle = 270, vjust = 0.5, hjust = 0.5, size = 8, face = "bold"),
        axis.text.y = element_blank(),
        strip.text = element_text(size = 8), 
        strip.text.x = element_text(size = 8, angle = 0, face = "bold"),
        strip.text.y = element_text(size = 8, angle = 0, face = "bold"),
        strip.background = element_rect(colour = "black", fill = "white"),
        legend.text = element_text(size = 8), # Incrementar el tamaño del texto de la leyenda
        legend.position = "top",
        legend.box = "vertical",
        legend.margin = margin(t = 0, r = 0, b = 0, l = 0, unit = "cm"),
        legend.box.margin = margin(t = 0, r = 0, b = 0, l = 0, unit = "cm"),
        legend.spacing = unit(0.005, "cm"),
        legend.key.size = unit(0.3, "cm"),
        legend.key.height = unit(0.3, "cm"),
        legend.key.width = unit(0.3, "cm"),
        panel.spacing = unit(0.2, "lines")) +
  scale_fill_manual(values = my.colors_All) +
  scale_size(range = c(1, 4), breaks = c(1, 3, 5)) +
  xlim(-10, 10) +
  facet_nested(Subcategory + gene_protein ~ Time + comparation,  
               space = "free", 
               # scales  = "free_y", 
               strip = strip_nested(size = "variable"), 
               labeller = label_wrap_gen(15)) +
  guides(fill = guide_legend(nrow = 4, byrow = TRUE, override.aes = list(size = 3)),
         size = guide_legend(order = 1))

Phosphorus_DGE_sig_plot


Phosphorus_DGE_sig_plot

# # Imprime el gráfico final
# print(Phosphorus_DGE_sig_plot)
# 
# # Cierra el dispositivo de gráficos
# dev.off()
# Phosphorus_DGE_sig_plot 

ggsave(
  filename = "../Results/WP2/Figure_4.pdf",
  plot     = Phosphorus_DGE_sig_plot,
  width    = 18, height = 24, units = "cm",
  device   = cairo_pdf          # mejor para transparencias y texto
)
```



```{r, fig.height=7, fig.width=7}
set.seed(123)
Phosphorus_DGE_sig <- Prok_DGE_INTERES_Selected_Genes %>%
  filter(Category == "Phosphorus metabolism") %>% # & 
  filter(Subcategory %in% c("High affinity transporters", "Low affinity transporters")) %>% #
  arrange(factor(Final_Taxonomy, levels= levels(.$Final_Taxonomy)))%>%
  mutate(orf=forcats::fct_inorder(orf))


# Set the transparenci 
Phosphorus_DGE_sig$transparency <- ifelse(Phosphorus_DGE_sig$logCPM <= Prok_logCPM, 
                                          0.1, # Set as 10% of the alpha (90% transparency) if logCPM is less than 2
                                          ifelse(Phosphorus_DGE_sig$PValue < 0.05 & # Significant PValue
                                                   Phosphorus_DGE_sig$logFC > -2 & # logFC between -2 and 2
                                                   Phosphorus_DGE_sig$logFC < 2, 
                                                 0.1, # Set as 10% of the alpha (90% transparency)
                                                 ifelse(Phosphorus_DGE_sig$PValue > 0.05 & # Non-significant PValue
                                                          (Phosphorus_DGE_sig$logFC < 2 | # logFC less than 2
                                                             Phosphorus_DGE_sig$logFC > -2), # logFC greater than -2
                                                        0.05, 1))) # Set as 100% of the alpha (0% transparency)





# # 💾 Guardar
# png("../Results/WP2/Supplementary/Bubbles/Prokaryotes_DGE_Phosphorus_transporters.png",
#     width = 18, height = 24, units = 'cm', res=600 )


Phosphorus_DGE_sig$Final_Taxonomy <- factor(Phosphorus_DGE_sig$Final_Taxonomy, 
                                             levels = rev(levels(Phosphorus_DGE_sig$Final_Taxonomy)))

Phosphorus_DGE_sig_plot <- ggplot(Phosphorus_DGE_sig, aes(y=orf, x=logFC, size=logCPM, fill = Final_Taxonomy, alpha = transparency)) + 
  annotate("rect", xmin = -Inf, xmax = 0, ymin = -Inf, ymax = Inf, fill = "dimgrey", alpha = 0.3) +
  annotate("rect", xmin = 0, xmax = Inf, ymin = -Inf, ymax = Inf, fill = "snow3", alpha = 0.3)+
  geom_point(alpha = Phosphorus_DGE_sig$transparency, shape = 21) +
  geom_vline(xintercept = 0) +
  labs(x = "(logFC)", y = "", fill = "", size = "logCPM") +
  theme_bw(base_size = 8) +
  theme(plot.title = element_text(size = 8, face = "bold", hjust = 0),
        plot.subtitle = element_text(size = 8, hjust = 0), 
        plot.caption = element_text(size = 8, hjust = 0, vjust = 0),
        axis.title.y = element_blank(),
        axis.title.x = element_text(angle = 0, vjust = 0.5, face = "bold"),
        axis.text.x = element_text(angle = 270, vjust = 0.5, hjust = 0.5, size = 8, face = "bold"),
        axis.text.y = element_blank(),
        strip.text = element_text(size = 8), 
        strip.text.x = element_text(size = 8, angle = 0, face = "bold"),
        strip.text.y = element_text(size = 8, angle = 0, face = "bold"),
        strip.background = element_rect(colour = "black", fill = "white"),
        legend.text = element_text(size = 8), # Incrementar el tamaño del texto de la leyenda
        legend.position = "top",
        legend.box = "vertical",
        legend.margin = margin(t = 0, r = 0, b = 0, l = 0, unit = "cm"),
        legend.box.margin = margin(t = 0, r = 0, b = 0, l = 0, unit = "cm"),
        legend.spacing = unit(0.005, "cm"),
        legend.key.size = unit(0.3, "cm"),
        legend.key.height = unit(0.3, "cm"),
        legend.key.width = unit(0.3, "cm"),
        panel.spacing = unit(0.2, "lines")) +
  scale_fill_manual(values = my.colors_All) +
  scale_size(range = c(1, 4), breaks = c(1, 3, 5)) +
  xlim(-10, 10) +
  facet_nested(Subcategory + gene_protein ~ Time + comparation,  
               space = "free", 
               # scales  = "free_y", 
               strip = strip_nested(size = "variable"), 
               labeller = label_wrap_gen(15)) +
  guides(fill = guide_legend(nrow = 4, byrow = TRUE, override.aes = list(size = 3)),
         size = guide_legend(order = 1))

Phosphorus_DGE_sig_plot


Phosphorus_DGE_sig_plot

# # Imprime el gráfico final
# print(Phosphorus_DGE_sig_plot)
# 
# # Cierra el dispositivo de gráficos
# dev.off()
# Phosphorus_DGE_sig_plot 


```

```{r, fig.height=7, fig.width=7}
set.seed(123)
Phosphorus_DGE_sig <- Prok_DGE_INTERES_Selected_Genes %>%
  filter(Category == "Phosphorus metabolism") %>% # & 
  filter(!Subcategory %in% c("High affinity transporters", "Low affinity transporters")) %>% #
  arrange(factor(Final_Taxonomy, levels= levels(.$Final_Taxonomy)))%>%
  mutate(orf=forcats::fct_inorder(orf))


# Set the transparenci 
Phosphorus_DGE_sig$transparency <- ifelse(Phosphorus_DGE_sig$logCPM <= Prok_logCPM, 
                                          0.1, # Set as 10% of the alpha (90% transparency) if logCPM is less than 2
                                          ifelse(Phosphorus_DGE_sig$PValue < 0.05 & # Significant PValue
                                                   Phosphorus_DGE_sig$logFC > -2 & # logFC between -2 and 2
                                                   Phosphorus_DGE_sig$logFC < 2, 
                                                 0.1, # Set as 10% of the alpha (90% transparency)
                                                 ifelse(Phosphorus_DGE_sig$PValue > 0.05 & # Non-significant PValue
                                                          (Phosphorus_DGE_sig$logFC < 2 | # logFC less than 2
                                                             Phosphorus_DGE_sig$logFC > -2), # logFC greater than -2
                                                        0.05, 1))) # Set as 100% of the alpha (0% transparency)





# 💾 Guardar
png("../Results/WP2/Supplementary/Bubbles/Prokaryotes_DGE_Phosphorus.png",
    width = 18, height = 24, units = 'cm', res=600 )


Phosphorus_DGE_sig$Final_Taxonomy <- factor(Phosphorus_DGE_sig$Final_Taxonomy, 
                                             levels = rev(levels(Phosphorus_DGE_sig$Final_Taxonomy)))

Phosphorus_DGE_sig_plot <- ggplot(Phosphorus_DGE_sig, aes(y=orf, x=logFC, size=logCPM, fill = Final_Taxonomy, alpha = transparency)) + 
  annotate("rect", xmin = -Inf, xmax = 0, ymin = -Inf, ymax = Inf, fill = "dimgrey", alpha = 0.3) +
  annotate("rect", xmin = 0, xmax = Inf, ymin = -Inf, ymax = Inf, fill = "snow3", alpha = 0.3)+
  geom_point(alpha = Phosphorus_DGE_sig$transparency, shape = 21) +
  geom_vline(xintercept = 0) +
  labs(x = "(logFC)", y = "", fill = "", size = "logCPM") +
  theme_bw(base_size = 8) +
  theme(plot.title = element_text(size = 8, face = "bold", hjust = 0),
        plot.subtitle = element_text(size = 8, hjust = 0), 
        plot.caption = element_text(size = 8, hjust = 0, vjust = 0),
        axis.title.y = element_blank(),
        axis.title.x = element_text(angle = 0, vjust = 0.5, face = "bold"),
        axis.text.x = element_text(angle = 270, vjust = 0.5, hjust = 0.5, size = 8, face = "bold"),
        axis.text.y = element_blank(),
        strip.text = element_text(size = 8), 
        strip.text.x = element_text(size = 8, angle = 0, face = "bold"),
        strip.text.y = element_text(size = 8, angle = 0, face = "bold"),
        strip.background = element_rect(colour = "black", fill = "white"),
        legend.text = element_text(size = 8), # Incrementar el tamaño del texto de la leyenda
        legend.position = "top",
        legend.box = "vertical",
        legend.margin = margin(t = 0, r = 0, b = 0, l = 0, unit = "cm"),
        legend.box.margin = margin(t = 0, r = 0, b = 0, l = 0, unit = "cm"),
        legend.spacing = unit(0.005, "cm"),
        legend.key.size = unit(0.3, "cm"),
        legend.key.height = unit(0.3, "cm"),
        legend.key.width = unit(0.3, "cm"),
        panel.spacing = unit(0.2, "lines")) +
  scale_fill_manual(values = my.colors_All) +
  scale_size(range = c(1, 4), breaks = c(1, 3, 5)) +
  xlim(-10, 10) +
  facet_nested(Subcategory + gene_protein ~ Time + comparation,  
               space = "free", 
               # scales  = "free_y", 
               strip = strip_nested(size = "variable"), 
               labeller = label_wrap_gen(15)) +
  guides(fill = guide_legend(nrow = 4, byrow = TRUE, override.aes = list(size = 3)),
         size = guide_legend(order = 1))

Phosphorus_DGE_sig_plot


Phosphorus_DGE_sig_plot

# Imprime el gráfico final
print(Phosphorus_DGE_sig_plot)

# Cierra el dispositivo de gráficos
dev.off()
Phosphorus_DGE_sig_plot 
```






```{r, fig.height=7, fig.width=7}
set.seed(123)
Euk_logCPM = 1

Phosphorus_DGE_sig <- PolyA_DGE_INTERES_Selected_Genes %>%
  filter(Category == "Phosphorus metabolism") 
# write.csv(Phosphorus_DGE_sig, "../Data Frames/WP2/Euk_DGE_INTERES_Selected_Genes.csv")


Phosphorus_DGE_sig <- PolyA_DGE_INTERES_Selected_Genes %>%
  filter(Category == "Phosphorus metabolism") %>% # & 
  filter(gene_protein %in% c("pho84", "ugpQ", 
                             "nptA", "pit", 
                             "acp5", "phoA", "pho-3", "phoD",  
                             "pho80", "pho81", "phoR", 
                             "pepM", "phnX", "phnY", "ppd",
                             "ppA", "EPT1", "PCYT2")) %>% #
  arrange(factor(Final_Taxonomy, levels= levels(.$Final_Taxonomy)))%>%
  mutate( geneid=forcats::fct_inorder( geneid))


# Set the transparenci 
Phosphorus_DGE_sig$transparency <- ifelse(Phosphorus_DGE_sig$logCPM <= Euk_logCPM, 
                                          0.1, # Set as 10% of the alpha (90% transparency) if logCPM is less than 2
                                          ifelse(Phosphorus_DGE_sig$PValue < 0.05 & # Significant PValue
                                                   Phosphorus_DGE_sig$logFC > -1.9 & # logFC between -2 and 2
                                                   Phosphorus_DGE_sig$logFC < 1.9, 
                                                 0.1, # Set as 10% of the alpha (90% transparency)
                                                 ifelse(Phosphorus_DGE_sig$PValue > 0.05 & # Non-significant PValue
                                                          (Phosphorus_DGE_sig$logFC < 1.9 | # logFC less than 2
                                                             Phosphorus_DGE_sig$logFC > -1.9), # logFC greater than -2
                                                        0.05, 1))) # Set as 100% of the alpha (0% transparency)




# # 💾 Guardar
# png("../Results/WP2/Figure_5.png",
#     width = 18, height = 24, units = 'cm', res=600 )


# Reordenar el factor Final_Taxonomy
Phosphorus_DGE_sig$Final_Taxonomy <- factor(Phosphorus_DGE_sig$Final_Taxonomy, 
                                             levels = rev(levels(Phosphorus_DGE_sig$Final_Taxonomy)))

Phosphorus_DGE_sig_plot <- ggplot(Phosphorus_DGE_sig, aes(y = geneid, x = logFC, size = logCPM, fill = Final_Taxonomy, alpha = transparency)) + 
  annotate("rect", xmin = -Inf, xmax = 0, ymin = -Inf, ymax = Inf, fill = "dimgrey", alpha = 0.3) +
  annotate("rect", xmin = 0, xmax = Inf, ymin = -Inf, ymax = Inf, fill = "snow3", alpha = 0.3)+
  geom_point(alpha = Phosphorus_DGE_sig$transparency, shape = 21) +
  geom_vline(xintercept = 0) +
  labs(x = "(logFC)", y = "", fill = "", size = "logCPM") +
  theme_bw(base_size = 8) +
  theme(plot.title = element_text(size = 8, face = "bold", hjust = 0),
        plot.subtitle = element_text(size = 8, hjust = 0), 
        plot.caption = element_text(size = 8, hjust = 0, vjust = 0),
        axis.title.y = element_blank(),
        axis.title.x = element_text(angle = 0, vjust = 0.5, face = "bold"),
        axis.text.x = element_text(angle = 270, vjust = 0.5, hjust = 0.5, size = 8, face = "bold"),
        axis.text.y = element_blank(),
        strip.text = element_text(size = 8), 
        strip.text.x = element_text(size = 8, angle = 0, face = "bold"),
        strip.text.y = element_text(size = 8, angle = 0, face = "bold"),
        strip.background = element_rect(colour = "black", fill = "white"),
        legend.text = element_text(size = 8), # Incrementar el tamaño del texto de la leyenda
        legend.position = "top",
        legend.box = "vertical",
        legend.margin = margin(t = 0, r = 0, b = 0, l = 0, unit = "cm"),
        legend.box.margin = margin(t = 0, r = 0, b = 0, l = 0, unit = "cm"),
        legend.spacing = unit(0.005, "cm"),
        legend.key.size = unit(0.3, "cm"),
        legend.key.height = unit(0.3, "cm"),
        legend.key.width = unit(0.3, "cm"),
        panel.spacing = unit(0.2, "lines")) +
  scale_fill_manual(values = my.colors_All) +
  scale_size(range = c(1, 4), breaks = c(1, 3, 5)) +
  xlim(-10, 10) +
  facet_nested(Subcategory + gene_protein ~ Time + comparation,  
               space = "free", 
               strip = strip_nested(size = "variable"), 
               labeller = label_wrap_gen(15)) +
  guides(fill = guide_legend(nrow = 4, byrow = TRUE, override.aes = list(size = 3)),
         size = guide_legend(order = 1), 
         alpha = FALSE)



# # Imprime el gráfico final
# print(Phosphorus_DGE_sig_plot)
# 
# # Cierra el dispositivo de gráficos
# dev.off()
# Phosphorus_DGE_sig_plot

ggsave(
  filename = "../Results/WP2/Figure_5.pdf",
  plot     = Phosphorus_DGE_sig_plot,
  width    = 18, height = 24, units = "cm",
  device   = cairo_pdf          # mejor para transparencias y texto
)

```

```{r, fig.height=7, fig.width=7}
set.seed(123)
Phosphorus_DGE_sig <- PolyA_DGE_INTERES_Selected_Genes %>%
  filter(Category == "Phosphorus metabolism") %>% # & 
  filter(Subcategory %in% c("High affinity transporters", "Low affinity transporters")) %>% #
  arrange(factor(Final_Taxonomy, levels= levels(.$Final_Taxonomy)))%>%
  mutate( geneid=forcats::fct_inorder( geneid))


# Set the transparenci 
Phosphorus_DGE_sig$transparency <- ifelse(Phosphorus_DGE_sig$logCPM <= Euk_logCPM, 
                                          0.1, # Set as 10% of the alpha (90% transparency) if logCPM is less than 2
                                          ifelse(Phosphorus_DGE_sig$PValue < 0.05 & # Significant PValue
                                                   Phosphorus_DGE_sig$logFC > -1.9 & # logFC between -2 and 2
                                                   Phosphorus_DGE_sig$logFC < 1.9, 
                                                 0.1, # Set as 10% of the alpha (90% transparency)
                                                 ifelse(Phosphorus_DGE_sig$PValue > 0.05 & # Non-significant PValue
                                                          (Phosphorus_DGE_sig$logFC < 1.9 | # logFC less than 2
                                                             Phosphorus_DGE_sig$logFC > -1.9), # logFC greater than -2
                                                        0.05, 1))) # Set as 100% of the alpha (0% transparency)




# 💾 Guardar
png("../Results/WP2/Supplementary/Bubbles/Eukaryotes_DGE_Phosphorus_transporters.png",
    width = 18, height = 24, units = 'cm', res=600 )


# Reordenar el factor Final_Taxonomy
Phosphorus_DGE_sig$Final_Taxonomy <- factor(Phosphorus_DGE_sig$Final_Taxonomy, 
                                             levels = rev(levels(Phosphorus_DGE_sig$Final_Taxonomy)))

Phosphorus_DGE_sig_plot <- ggplot(Phosphorus_DGE_sig, aes(y = geneid, x = logFC, size = logCPM, fill = Final_Taxonomy, alpha = transparency)) + 
  annotate("rect", xmin = -Inf, xmax = 0, ymin = -Inf, ymax = Inf, fill = "dimgrey", alpha = 0.3) +
  annotate("rect", xmin = 0, xmax = Inf, ymin = -Inf, ymax = Inf, fill = "snow3", alpha = 0.3)+
  geom_point(alpha = Phosphorus_DGE_sig$transparency, shape = 21) +
  geom_vline(xintercept = 0) +
  labs(x = "(logFC)", y = "", fill = "", size = "logCPM") +
  theme_bw(base_size = 8) +
  theme(plot.title = element_text(size = 8, face = "bold", hjust = 0),
        plot.subtitle = element_text(size = 8, hjust = 0), 
        plot.caption = element_text(size = 8, hjust = 0, vjust = 0),
        axis.title.y = element_blank(),
        axis.title.x = element_text(angle = 0, vjust = 0.5, face = "bold"),
        axis.text.x = element_text(angle = 270, vjust = 0.5, hjust = 0.5, size = 8, face = "bold"),
        axis.text.y = element_blank(),
        strip.text = element_text(size = 8), 
        strip.text.x = element_text(size = 8, angle = 0, face = "bold"),
        strip.text.y = element_text(size = 8, angle = 0, face = "bold"),
        strip.background = element_rect(colour = "black", fill = "white"),
        legend.text = element_text(size = 8), # Incrementar el tamaño del texto de la leyenda
        legend.position = "top",
        legend.box = "vertical",
        legend.margin = margin(t = 0, r = 0, b = 0, l = 0, unit = "cm"),
        legend.box.margin = margin(t = 0, r = 0, b = 0, l = 0, unit = "cm"),
        legend.spacing = unit(0.005, "cm"),
        legend.key.size = unit(0.3, "cm"),
        legend.key.height = unit(0.3, "cm"),
        legend.key.width = unit(0.3, "cm"),
        panel.spacing = unit(0.2, "lines")) +
  scale_fill_manual(values = my.colors_All) +
  scale_size(range = c(1, 4), breaks = c(1, 3, 5)) +
  xlim(-10, 10) +
  facet_nested(Subcategory + gene_protein ~ Time + comparation,  
               space = "free", 
               strip = strip_nested(size = "variable"), 
               labeller = label_wrap_gen(15)) +
  guides(fill = guide_legend(nrow = 4, byrow = TRUE, override.aes = list(size = 3)),
         size = guide_legend(order = 1), 
         alpha = FALSE)



# Imprime el gráfico final
print(Phosphorus_DGE_sig_plot)

# Cierra el dispositivo de gráficos
dev.off()
Phosphorus_DGE_sig_plot

```


```{r, fig.height=7, fig.width=7}
set.seed(123)
Phosphorus_DGE_sig <- PolyA_DGE_INTERES_Selected_Genes %>%
  filter(Category == "Phosphorus metabolism") %>% # & 
  filter(!Subcategory %in% c("High affinity transporters", "Low affinity transporters")) %>% #
  arrange(factor(Final_Taxonomy, levels= levels(.$Final_Taxonomy)))%>%
  mutate( geneid=forcats::fct_inorder( geneid))


# Set the transparenci 
Phosphorus_DGE_sig$transparency <- ifelse(Phosphorus_DGE_sig$logCPM <= Euk_logCPM, 
                                          0.1, # Set as 10% of the alpha (90% transparency) if logCPM is less than 2
                                          ifelse(Phosphorus_DGE_sig$PValue < 0.05 & # Significant PValue
                                                   Phosphorus_DGE_sig$logFC > -1.9 & # logFC between -2 and 2
                                                   Phosphorus_DGE_sig$logFC < 1.9, 
                                                 0.1, # Set as 10% of the alpha (90% transparency)
                                                 ifelse(Phosphorus_DGE_sig$PValue > 0.05 & # Non-significant PValue
                                                          (Phosphorus_DGE_sig$logFC < 1.9 | # logFC less than 2
                                                             Phosphorus_DGE_sig$logFC > -1.9), # logFC greater than -2
                                                        0.05, 1))) # Set as 100% of the alpha (0% transparency)




# 💾 Guardar
png("../Results/WP2/Supplementary/Bubbles/Eukaryotes_DGE_Phosphorus.png",
    width = 18, height = 24, units = 'cm', res=600 )


# Reordenar el factor Final_Taxonomy
Phosphorus_DGE_sig$Final_Taxonomy <- factor(Phosphorus_DGE_sig$Final_Taxonomy, 
                                             levels = rev(levels(Phosphorus_DGE_sig$Final_Taxonomy)))

Phosphorus_DGE_sig_plot <- ggplot(Phosphorus_DGE_sig, aes(y = geneid, x = logFC, size = logCPM, fill = Final_Taxonomy, alpha = transparency)) + 
  annotate("rect", xmin = -Inf, xmax = 0, ymin = -Inf, ymax = Inf, fill = "dimgrey", alpha = 0.3) +
  annotate("rect", xmin = 0, xmax = Inf, ymin = -Inf, ymax = Inf, fill = "snow3", alpha = 0.3)+
  geom_point(alpha = Phosphorus_DGE_sig$transparency, shape = 21) +
  geom_vline(xintercept = 0) +
  labs(x = "(logFC)", y = "", fill = "", size = "logCPM") +
  theme_bw(base_size = 8) +
  theme(plot.title = element_text(size = 8, face = "bold", hjust = 0),
        plot.subtitle = element_text(size = 8, hjust = 0), 
        plot.caption = element_text(size = 8, hjust = 0, vjust = 0),
        axis.title.y = element_blank(),
        axis.title.x = element_text(angle = 0, vjust = 0.5, face = "bold"),
        axis.text.x = element_text(angle = 270, vjust = 0.5, hjust = 0.5, size = 8, face = "bold"),
        axis.text.y = element_blank(),
        strip.text = element_text(size = 8), 
        strip.text.x = element_text(size = 8, angle = 0, face = "bold"),
        strip.text.y = element_text(size = 8, angle = 0, face = "bold"),
        strip.background = element_rect(colour = "black", fill = "white"),
        legend.text = element_text(size = 8), # Incrementar el tamaño del texto de la leyenda
        legend.position = "top",
        legend.box = "vertical",
        legend.margin = margin(t = 0, r = 0, b = 0, l = 0, unit = "cm"),
        legend.box.margin = margin(t = 0, r = 0, b = 0, l = 0, unit = "cm"),
        legend.spacing = unit(0.005, "cm"),
        legend.key.size = unit(0.3, "cm"),
        legend.key.height = unit(0.3, "cm"),
        legend.key.width = unit(0.3, "cm"),
        panel.spacing = unit(0.2, "lines")) +
  scale_fill_manual(values = my.colors_All) +
  scale_size(range = c(1, 4), breaks = c(1, 3, 5)) +
  xlim(-10, 10) +
  facet_nested(Subcategory + gene_protein ~ Time + comparation,  
               space = "free", 
               strip = strip_nested(size = "variable"), 
               labeller = label_wrap_gen(15)) +
  guides(fill = guide_legend(nrow = 4, byrow = TRUE, override.aes = list(size = 3)),
         size = guide_legend(order = 1), 
         alpha = FALSE)



# Imprime el gráfico final
print(Phosphorus_DGE_sig_plot)

# Cierra el dispositivo de gráficos
dev.off()
Phosphorus_DGE_sig_plot

```



```{r, cache=TRUE}
Prok_INTERES_WP2_counts_replics <- read_parquet("../Data Frames/WP2/INTERES_Prok_WP2_counts_Annotated_1KEGG_ko.parquet")


# Suma por ORF
Prok_INTERES_nMDS <- Prok_INTERES_WP2_counts_replics %>%
    unite(sample, Workpackage, treatment, time, replic, sep = "_", remove = T) %>%
     dplyr::select(sample, orf, count) %>%
    group_by(sample, orf) %>%
  dplyr::summarise(count=sum(count)) %>% 
  # mutate(count = count + 1 ) %>%
  spread(orf, count, fill = 0)

# # Transformacion CLR
# Prok_INTERES_nMDS_codaseq_clr <- Prok_INTERES_nMDS %>%
#   column_to_rownames('sample') %>%
#   codaSeq.clr(samples.by.row = FALSE) %>% #calculate clr
#   as.data.frame() %>%
#   rownames_to_column('sample')
# saveRDS(ENV_field_codaseq_clr_MATRIX, file = "ENV_field_c odaseq_clr.rds")

# Unir con lo de arriba
ENV_nMDS <- Prok_INTERES_nMDS %>%
  separate(sample, c("Workpackage", "treatment", "time", "replic"), sep = "_", remove = F) 

# primera_columna <- ENV_nMDS[, 1]
# primera_columna
```


```{r}
# Establecer e orden
ENV_nMDS$treatment_time=factor(rep(c(
  rep("Control 0h", 3), 
  rep("Control 72h", 3), 
  rep("River 0h", 3), 
  rep("River 72h", 3),
  rep("River+P 0h", 3), 
  rep("River+P 72h", 3)
  )))
```


```{r nMDS}
ENV_nMDS.matrix <- as.matrix(ENV_nMDS[,6:307609])

ENV_nMDS.dist <- vegdist(ENV_nMDS.matrix, method='bray')

set.seed(123)
ENV_nMDS.div <- adonis2(ENV_nMDS.dist~treatment*treatment_time, data=ENV_nMDS, permutations = 999, method="bray")

# anova(ENV_nMDS.dist) ### overall test of the significant of the analysis


ENV_nMDS.div
```


```{r nMDS}
NMDS=metaMDS(ENV_nMDS.dist, k=2)

ENV_nMDS.perm=as.data.frame(scores(NMDS))
ENV_nMDS.perm$treatment_time=ENV_nMDS$treatment_time
ENV_nMDS.perm$Div=ENV_nMDS$time
```


```{r nMDS}

MDS=data.frame(MDS1=NMDS$points[,1], MDS2=NMDS$points[,2], group=ENV_nMDS$treatment_time) # This is the gruping parameter



veganCovEllipse<-function (cov, center = c(0, 0), scale = 1, npoints = 100) 
{
  theta <- (0:npoints) * 2 * pi/npoints
  Circle <- cbind(cos(theta), sin(theta))
  t(center + scale * t(Circle %*% chol(cov)))
}

df_ell <- data.frame()
for(g in levels(MDS$group)){
  df_ell <- rbind(df_ell, cbind(as.data.frame(with(MDS[MDS$group==g,],
                                                   veganCovEllipse(cov.wt(cbind(MDS1,MDS2),wt=rep(1/length(MDS1),length(MDS1)))$cov,center=c(mean(MDS1),mean(MDS2)))))
                                ,group=g))
}
```




```{r, fig.height=7, fig.width=7}
library(ggplot2)

# Asignar colores y formas
color_values <- c("Control 0h" = "deepskyblue", "Control 72h" = "deepskyblue4",
                  "River 0h" = "deeppink", "River 72h" = "deeppink4",
                  "River+P 0h" = "aquamarine", "River+P 72h" = "aquamarine4")

shape_values <- c("Control 0h" = 19, "Control 72h" = 19,
                  "River 0h" = 17, "River 72h" = 17,
                  "River+P 0h" = 15, "River+P 72h" = 15)

# Crear el gráfico
Prok_nMDS_OG <- ggplot() + 
  geom_point(data = ENV_nMDS.perm, aes(x = NMDS1, y = NMDS2, colour = treatment_time, shape = treatment_time), size = 3) + 
  geom_polygon(data = df_ell, aes(x = MDS1, y = MDS2, fill = group), alpha = 0.2) +
  theme_bw() +
     ggtitle ("Prokaryotes")+
  theme(panel.background = element_rect(fill = NA, colour = "black", size = 0.5, linetype = "solid")) +
  scale_colour_manual(name = "", values = color_values,
                      labels = c("Control 0h", 
                                 "Control 72h", 
                                 "River 0h", 
                                 "River 72h", 
                                 "River+P 0h",
                                 "River+P 72h")) +
  scale_fill_manual(name = "", values = color_values,
                    labels = c("Control 0h", 
                               "Control 72h", 
                               "River 0h", 
                               "River 72h", 
                               "River+P 0h",
                               "River+P 72h")) +
  scale_shape_manual(name = "", values = shape_values,
                     labels = c("Control 0h", 
                                "Control 72h", 
                                "River 0h", 
                                "River 72h", 
                                "River+P 0h",
                                "River+P 72h")) +
  theme(
    legend.position = "top",
        legend.box = "horizontal",
        legend.margin = margin(t = 0, r = 0, b = 0, l = 0, unit = "cm"),
        legend.box.margin = margin(t = 0, r = 0, b = 0, l = 0, unit = "cm"),
        legend.spacing = unit(0.005, "cm"),
    legend.key.size = unit(0.2, "cm"),  # Ajuste general del tamaño del recuadro
    legend.key.height = unit(0.2, "cm"),  # Ajuste del tamaño de altura del recuadro
    legend.key.width = unit(0.2, "cm"), 
        legend.title = element_blank()) +
        theme(plot.title = element_text(size = 10, face = "bold",hjust = 0.04, vjust = -25),
              axis.text.x = element_text(angle = 0, vjust = 0.5, hjust = 0.5, size=8, face = "bold"),
            axis.text.y = element_text(angle = 0, vjust = 0.5, hjust = 1, size=8, face = "bold"),
            axis.title.x = element_text(angle = 0, vjust = 0.5, size=8, face = "bold"),
            axis.title.y = element_text(angle = 90, vjust = 0.5, size=8, face = "bold")) +
  guides(
    fill = guide_legend(override.aes = list(shape = NA, size = 2, fill = color_values), nrow = 2),
    colour = guide_legend(override.aes = list(shape = shape_values, size = 2), nrow = 2),
    shape = guide_legend(override.aes = list(colour = color_values, size = 2), nrow = 2)
  )

Prok_nMDS_OG


```


```{r, cache=TRUE}
Euk_INTERES_WP2_counts_replics <- read_parquet("../Data Frames/WP2/INTERES_Euk_WP2_counts_Annotated_1KEGG_ko.parquet")


# Suma por geneid
Euk_INTERES_nMDS <- Euk_INTERES_WP2_counts_replics %>%
    unite(sample, Workpackage, treatment, time, replic, sep = "_", remove = T) %>%
  # dplyr::filter(sample !="WP2_R+P_0h_R1") %>%
  # dplyr::filter(sample !="WP2_R+P_0h_R2") %>%
     dplyr::select(sample, geneid, count) %>%
    group_by(sample, geneid) %>%
  dplyr::summarise(count=sum(count)) %>% 
#     mutate(count = count + 1 ) %>%
  spread(geneid, count, fill = 0)

# # Transformacion CLR
# Euk_INTERES_nMDS_codaseq_clr <- Euk_INTERES_nMDS %>%
#   column_to_rownames('sample') %>%
#   codaSeq.clr(samples.by.row = FALSE) %>% #calculate clr
#   as.data.frame() %>%
#   rownames_to_column('sample')
# # saveRDS(ENV_field_codaseq_clr_MATRIX, file = "ENV_field_c odaseq_clr.rds")

# Unir con lo de arriba
Euk_nMDS <- Euk_INTERES_nMDS %>%
  separate(sample, c("Workpackage", "treatment", "time", "replic"), sep = "_", remove = F)

# primera_columna <- Euk_nMDS[, 1]
# primera_columna 
```


```{r, cache=TRUE}
# Establecer e orden
Euk_nMDS$treatment_time=factor(rep(c(
  rep("Control 0h", 3), 
  rep("Control 72h", 3), 
  rep("River 0h", 3),
  rep("River 72h", 3),
  rep("River+P 0h", 2),
  rep("River+P 72h", 3)
  )))
```




```{r nMDS}
Euk_nMDS.matrix <- as.matrix(Euk_nMDS[,6:1104603]) #CAMBIA ESTE NUMERO

Euk_nMDS.dist <- vegdist(Euk_nMDS.matrix, method='bray')

set.seed(123)
Euk_nMDS.div <- adonis2(Euk_nMDS.dist~treatment*treatment_time, data=Euk_nMDS, permutations = 999, method="bray")

# anova(Euk_nMDS.dist) ### overall test of the significant of the analysis


Euk_nMDS.div
```


```{r nMDS}
NMDS=metaMDS(Euk_nMDS.dist, k=2)

Euk_nMDS.perm=as.data.frame(scores(NMDS))
Euk_nMDS.perm$treatment_time=Euk_nMDS$treatment_time
Euk_nMDS.perm$Div=Euk_nMDS$time
```


```{r nMDS}

# MDS=data.frame(MDS1=NMDS$points[,1], MDS2=NMDS$points[,2], group=Euk_nMDS$treatment_time) # This is the gruping parameter
# 
# 
# veganCovEllipse<-function (cov, center = c(0, 0), scale = 1, npoints = 100) 
# {
#   theta <- (0:npoints) * 2 * pi/npoints
#   Circle <- cbind(cos(theta), sin(theta))
#   t(center + scale * t(Circle %*% chol(cov)))
# }
# 
# df_ell <- data.frame()
# for(g in levels(MDS$group)){
#   df_ell <- rbind(df_ell, cbind(as.data.frame(with(MDS[MDS$group==g,],
#                                                    veganCovEllipse(cov.wt(cbind(MDS1,MDS2),wt=rep(1/length(MDS1),length(MDS1)))$cov,center=c(mean(MDS1),mean(MDS2)))))
#                                 ,group=g))
# }
```
```{r}
MDS <- data.frame(
  MDS1 = NMDS$points[,1],
  MDS2 = NMDS$points[,2],
  group = droplevels(Euk_nMDS$treatment_time)
)

veganCovEllipse <- function (cov, center = c(0, 0), scale = 1, npoints = 100){
  theta <- (0:npoints) * 2 * pi/npoints
  Circle <- cbind(cos(theta), sin(theta))
  t(center + scale * t(Circle %*% chol(cov)))
}

safe_ellipse <- function(df, npoints = 100, scale = 1){
  if(nrow(df) < 3) return(NULL)  # sin elipse si n < 3
  S <- cov.wt(df[,c("MDS1","MDS2")], wt = rep(1/nrow(df), nrow(df)))$cov
  # regularización mínima si hiciera falta
  ev <- eigen(S, symmetric = TRUE, only.values = TRUE)$values
  if(any(ev <= 0)) {
    S <- S + diag(max(1e-8, 1e-6*mean(diag(S))), 2)
  }
  ctr <- colMeans(df[,c("MDS1","MDS2")])
  as.data.frame(veganCovEllipse(S, center = ctr, scale = scale, npoints = npoints))
}

library(dplyr)
df_ell <- split(MDS, MDS$group) |>
  lapply(function(d){
    e <- safe_ellipse(d)
    if(is.null(e)) return(NULL)
    e$group <- d$group[1]; e
  }) |>
  bind_rows()

# Hulls para grupos con n >= 2 (sirve para n=2)
hulls <- MDS |>
  group_by(group) |>
  filter(n() >= 2) |>
  reframe(MDS1 = MDS1[chull(MDS1, MDS2)],
          MDS2 = MDS2[chull(MDS1, MDS2)])

```

```{r}
Euk_nMDS_OG <- ggplot() +
  geom_point(data = Euk_nMDS.perm,
             aes(NMDS1, NMDS2, colour = treatment_time, shape = treatment_time), size = 3) +
  geom_polygon(data = df_ell,
               aes(MDS1, MDS2, fill = group), alpha = 0.2, inherit.aes = FALSE) +
  geom_polygon(data = hulls,
               aes(MDS1, MDS2, fill = group), alpha = 0.12, inherit.aes = FALSE)

```

```{r}
Euk_nMDS_OG <- ggplot(Euk_nMDS.perm,
                      aes(NMDS1, NMDS2, colour = treatment_time, shape = treatment_time)) +
  geom_point(size = 3) +
  stat_ellipse(aes(group = treatment_time, fill = treatment_time),
               type = "norm", geom = "polygon", alpha = 0.2, level = 0.68,
               show.legend = FALSE, na.rm = TRUE)
Euk_nMDS_OG
```


```{r, fig.height=7, fig.width=7}
library(ggplot2)

# Asignar colores y formas
color_values <- c("Control 0h" = "slateblue", "Control 72h" = "slateblue4",
                  "River 0h" = "green1", "River 72h" = "green4",
                   "River+P 0h" = "orangered1", "River+P 72h" = "orangered4")

shape_values <- c("Control 0h" = 19, "Control 72h" = 19,
                  "River 0h" = 17, "River 72h" = 17,
                   "River+P 0h" = 15, "River+P 72h" = 15)

# Crear el gráfico
Euk_nMDS_OG <- ggplot() + 
  geom_point(data = Euk_nMDS.perm, aes(x = NMDS1, y = NMDS2, colour = treatment_time, shape = treatment_time), size = 3) + 
  geom_polygon(data = df_ell, aes(x = MDS1, y = MDS2, fill = group), alpha = 0.2) +
  theme_bw() +
       ggtitle ("Eukaryotes")+
  theme(panel.background = element_rect(fill = NA, colour = "black", size = 1, linetype = "solid")) +
  scale_colour_manual(name = "", values = color_values,
                      labels = c("Control 0h", 
                                 "Control 72h", 
                                 "River 0h", 
                                 "River 72h", 
                                 "River+P 0h",
                                 "River+P 72h")) +
  # scale_fill_manual(name = "", values = color_values,
  #                   labels = c("Control 0h", 
  #                              "Control 72h", 
  #                              "River 0h", 
  #                              "River 72h", 
  #                              # "River+P 0h",
  #                              "River+P 72h")) +
  scale_shape_manual(name = "", values = shape_values,
                     labels = c("Control 0h", 
                                "Control 72h", 
                                "River 0h", 
                                "River 72h", 
                                "River+P 0h",
                                "River+P 72h")) +
  theme(
    legend.position = "top",
        legend.box = "horizontal",
        legend.margin = margin(t = 0, r = 0, b = 0, l = 0, unit = "cm"),
        legend.box.margin = margin(t = 0, r = 0, b = 0, l = 0, unit = "cm"),
        legend.spacing = unit(0.005, "cm"),
    legend.key.size = unit(0.2, "cm"),  # Ajuste general del tamaño del recuadro
    legend.key.height = unit(0.2, "cm"),  # Ajuste del tamaño de altura del recuadro
    legend.key.width = unit(0.2, "cm"), 
        legend.title = element_blank()) +
        theme(plot.title = element_text(size = 10, face = "bold",hjust = 0.04, vjust = -25),
              axis.text.x = element_text(angle = 0, vjust = 0.5, hjust = 0.5, size=8, face = "bold"),
            axis.text.y = element_text(angle = 0, vjust = 0.5, hjust = 1, size=8, face = "bold"),
            axis.title.x = element_text(angle = 0, vjust = 0.5, size=8, face = "bold"),
            axis.title.y = element_text(angle = 90, vjust = 0.5, size=8, face = "bold")) +
  guides(
    fill = guide_legend(override.aes = list(shape = NA, size = 2, fill = color_values), nrow = 2),
    colour = guide_legend(override.aes = list(shape = shape_values, size = 2), nrow = 2),
    shape = guide_legend(override.aes = list(colour = color_values, size = 2), nrow = 2)
  )


Euk_nMDS_OG


```

```{r}
library(dplyr)
library(ggplot2)

# Paletas completas (nombradas)
color_values <- c("Control 0h" = "slateblue", "Control 72h" = "slateblue4",
                  "River 0h" = "green1", "River 72h" = "green4",
                  "River+P 0h" = "orangered1", "River+P 72h" = "orangered4")
shape_values <- c("Control 0h" = 19, "Control 72h" = 19,
                  "River 0h" = 17, "River 72h" = 17,
                  "River+P 0h" = 15, "River+P 72h" = 15)

# Niveles realmente presentes en puntos y elipses
lvls_pts  <- levels(droplevels(Euk_nMDS.perm$treatment_time))
lvls_ell  <- if(nrow(df_ell)) levels(droplevels(df_ell$group)) else character(0)

Euk_nMDS_OG <- ggplot() +
  # Elipses (sin leyenda de fill)
  geom_polygon(data = df_ell,
               aes(MDS1, MDS2, fill = group),
               alpha = 0.2, inherit.aes = FALSE, show.legend = FALSE) +
  # Puntos
  geom_point(data = Euk_nMDS.perm,
             aes(NMDS1, NMDS2, colour = treatment_time, shape = treatment_time),
             size = 3) +
  theme_bw() +
  ggtitle("Eukaryotes") +
  theme(panel.background = element_rect(fill = NA, colour = "black", size = 1)) +
  # Escalas SOLO con los niveles presentes
  scale_colour_manual(values = color_values[lvls_pts], breaks = lvls_pts) +
  scale_shape_manual(values = shape_values[lvls_pts], breaks = lvls_pts) +
  scale_fill_manual(values = color_values[lvls_ell], breaks = lvls_ell, guide = "none") +
  theme(
    legend.position = "top",
        legend.box = "horizontal",
        legend.margin = margin(t = 0, r = 0, b = 0, l = 0, unit = "cm"),
        legend.box.margin = margin(t = 0, r = 0, b = 0, l = 0, unit = "cm"),
        legend.spacing = unit(0.005, "cm"),
    legend.key.size = unit(0.2, "cm"),  # Ajuste general del tamaño del recuadro
    legend.key.height = unit(0.2, "cm"),  # Ajuste del tamaño de altura del recuadro
    legend.key.width = unit(0.2, "cm"), 
        legend.title = element_blank()) +
        theme(plot.title = element_text(size = 10, face = "bold",hjust = 0.04, vjust = -25),
              axis.text.x = element_text(angle = 0, vjust = 0.5, hjust = 0.5, size=8, face = "bold"),
            axis.text.y = element_text(angle = 0, vjust = 0.5, hjust = 1, size=8, face = "bold"),
            axis.title.x = element_text(angle = 0, vjust = 0.5, size=8, face = "bold"),
            axis.title.y = element_text(angle = 90, vjust = 0.5, size=8, face = "bold")) +
  guides(
    colour = guide_legend(nrow = 2),
    shape  = guide_legend(nrow = 2)
  )

Euk_nMDS_OG

```


```{r}
# Paleta ejemplo para grupos (agrupados y seguros para daltonismo)
colores_taxones <- c(
  "Alphaproteobacteria" = "#56B4E9",  # Azul
  "Rhodobacterales"     = "#0072B2",  # Azul oscuro
  "Puniceispirillales"  = "#CC79A7",  # Magenta
  "Rhizobiales"         = "#E69F00",  # Naranja
  "Gammaproteobacteria"= "#D55E00",  # Rojo
  "Burkholderiales"     = "#009E73",  # Verde
  "Enterobacterales"    = "#F0E442",  # Amarillo
  "Pseudomonadales"     = "#999999",  # Gris
  "SAR86"               = "#000000",  # Negro
  "Bacteroidota"        = "#56B4E9",
  "Flavobacteriales"    = "#0072B2",
  "Firmicutes"          = "#E69F00",
  "Cyanobacteria"       = "#009E73",
  "Actinobacteriota"    = "#D55E00",
  "Planctomycetota"     = "#CC79A7",
  "Archaea"             = "#999999",
  "Other prokaryotes"   = "#F0E442",
  "Spirotrichea"        = "#56B4E9",
  "Choreotrichida"      = "#0072B2",
  "Tintinnida"          = "#E69F00",
  "Dinoflagellata"      = "#D55E00",
  "Gonyaulacales"       = "#009E73",
  "Alexandrium"         = "#CC79A7",
  "Gymnodiniales"       = "#999999",
  "Peridiniales"        = "#F0E442",
  "Syndiniales"         = "#000000",
  "Symbiodinium"        = "#56B4E9",
  "Sarmatiales"         = "#0072B2",
  "Ochromonadales"      = "#E69F00",
  "Bacillariophyta"     = "#009E73",
  "Thalassiosira"       = "#D55E00",
  "Chaetoceros"         = "#CC79A7",
  "Skeletonema"         = "#999999",
  "Pseudo-nitzschia"    = "#F0E442",
  "Glaucophyta"         = "#000000",
  "Chlorophyta"         = "#56B4E9",
  "Amoebozoa"           = "#0072B2",
  "Haptophyta"          = "#E69F00",
  "Rhizaria"            = "#009E73",
  "Other eukaryotes"    = "#999999"
)
```






```{r, fig.height=9, fig.width=7}
# 💾 Guardar
# png("../Results/WP2/Figure_2.png",
#     width = 18, height = 24, units = 'cm', res=600 )

# # Crea un objeto ggdraw con el título
# Title_A <- ggdraw() + 
#   draw_label("a) Metatranscriptomic Taxonomy Distribution", fontface = 'bold', size = 10, y= 0.5)
# 
# MetaTs_plot <- plot_grid(Title_A, 
#                          plot_grid(Prok_Transcriptome_proportion_plot, Euk_Transcriptome_proportion_plot, ncol = 2, rel_widths = c(1, 1)),
#                          ncol = 1,
#                          rel_heights = c(0.05, 1)) # Ajusta rel_heights según sea necesario



# Crea un objeto ggdraw con el título
Title_B <- ggdraw() + 
  draw_label("b) nMDS Analysis of Prokaryotic and Eukaryotic Metatranscriptome", fontface = 'bold', size = 10, y= 0.5)

nMDS_plot <- plot_grid(Title_B,
                         plot_grid(Prok_nMDS_OG, Euk_nMDS_OG, ncol = 2, rel_widths = c(1, 1)),
                         ncol = 1,
                         rel_heights = c(0.03, 1)) # Ajusta rel_heights según sea necesario



# Combina el título, las gráficas y el texto final
Figure_2 <- plot_grid(MetaTs_plot, nMDS_plot, ncol = 1, rel_heights = c(1.5, 1)) # Ajusta rel_heights según sea necesario



# # Imprime el gráfico final
# print(Figure_2)
# 
# # Cierra el dispositivo de gráficos
# dev.off()
# Figure_2

ggsave(
  filename = "../Results/WP2/Figure_2.pdf",
  plot     = Figure_2,
  width    = 18, height = 24, units = "cm",
  device   = cairo_pdf          # mejor para transparencias y texto
)
```






```{r}
Prok_correl <- read_excel("../Data Frames/WP2/Correlations.xlsx", sheet = "Prok_1KEGG",  col_names = TRUE) %>% #range = "A1:D10",
  dplyr::select(sample, gene_protein,	Final_Taxonomy, tpm, PO4,	NP,	PP,	DIN,	chla) %>%
  dplyr::filter(Final_Taxonomy %in% c("Pseudomonadales", "Rhodobacterales", "Gammaproteobacteria", "Rhodobacterales", "SAR86"))%>%
  dplyr::filter(gene_protein %in% c("phoA", "phoD", "pit", "pstABCS", "phnC",	"phnA",	"phnD",	"phnE"))%>%
  spread(gene_protein, tpm, fill = 0)
```




```{r}
library(ggplot2)
library(dplyr)
library(readxl)

# 🔹 Leer datos desde Excel
High_affinity <- read_excel("../Data Frames/WP2/Correlations.xlsx", sheet = "High_affinity", col_names = TRUE)

# 🔹 Función para ajustar nls() y calcular p-valor desde un modelo log-log + corrección de Good
ajustar_nls <- function(data) {
    fit <- nls(pst_pit ~ a * PO4^b, data = data, start = list(a = 1, b = -1))

    # Ajustar modelo log-log paralelo
    log_model <- lm(log(pst_pit) ~ log(PO4), data = data)
    p_global <- summary(log_model)$coefficients[2, 4]

    # Aplicar corrección de Good
    p_good <- p_global * sqrt(6 / 100)

    # Calcular R²
    r2 <- 1 - sum(residuals(fit)^2) / sum((data$pst_pit - mean(data$pst_pit))^2)

    return(list(a = coef(fit)["a"], b = coef(fit)["b"], r2 = r2,
                p_global = p_global, p_good = p_good, fit = fit))
}

# 🔹 Ajustes para cada grupo
pseudo_data <- High_affinity %>% filter(Final_Taxonomy == "Pseudomonadales")
pseudo_res <- ajustar_nls(pseudo_data)

rhodo_data <- High_affinity %>% filter(Final_Taxonomy == "Rhodobacterales")
rhodo_res <- ajustar_nls(rhodo_data)

base_x <- max(High_affinity$PO4) * 0.1
base_y <- max(High_affinity$pst_pit) * 0.9
line_spacing <- 0.1 * max(High_affinity$pst_pit)  # Ajusta según escala

# 🔹 Crear la gráfica con p-valores corregidos
High_affinity_plot <- ggplot() +
  # 🔸 Pseudomonadales
  geom_point(data = pseudo_data, aes(x = PO4, y = pst_pit), color = "plum3", size = 3) +
  geom_smooth(data = pseudo_data, aes(x = PO4, y = pst_pit), method = "nls",
              formula = y ~ a * x^b, method.args = list(start = list(a = 1, b = -1)),
              se = FALSE, linetype = "dashed", color = "plum3") +

  # 🔸 Rhodobacterales
  geom_point(data = rhodo_data, aes(x = PO4, y = pst_pit), color = "deepskyblue4", size = 3) +
  geom_smooth(data = rhodo_data, aes(x = PO4, y = pst_pit), method = "nls",
              formula = y ~ a * x^b, method.args = list(start = list(a = 1, b = -1)),
              se = FALSE, linetype = "dashed", size = 0.5, color = "deepskyblue4") +
  annotate("text", x = base_x, y = base_y,
           label = "Rhodobacterales: R² = 0.893   p = 0.001",
           hjust = 0, color = "deepskyblue4", size = 3, fontface = "bold") +
  
  annotate("text", x = base_x, y = base_y - line_spacing,
           label = "Pseudomonadales: R² = 0.750   p = 0.006",
           hjust = 0, color = "plum3", size = 3, fontface = "bold")+

  # 🔹 Título y ejes
  ggtitle("a) High affinity transport vs PO₄⁻³") +
  labs(x = "PO₄⁻³ (µmol L⁻¹)", y = "pst:pit ratio") +
  theme_bw() +
  theme(text = element_text(size = 10),
        plot.title = element_text(size = 10, face = "bold", hjust = 0.5))

# 🔹 Mostrar gráfica
High_affinity_plot

```




```{r}
library(ggplot2)
library(dplyr)
library(readxl)

# Leer datos
Low_affinity <- read_excel("../Data Frames/WP2/Correlations.xlsx", sheet = "Low_affinity")

# Filtrar diatoms y evitar ceros
diatom_data <- Low_affinity %>%
  filter(Final_Taxonomy == "Diatom", PO4 > 0, nptA > 0)

# Ajuste log-log
log_model <- lm(log(nptA) ~ log(PO4), data = diatom_data)
a <- exp(coef(log_model)[1])
b <- coef(log_model)[2]

# Gráfica base
Low_affinity_plot <- ggplot(diatom_data, aes(x = PO4, y = nptA)) +
  geom_point(color = "green4", size = 3) +
  stat_function(fun = function(x) a * x^b, color = "green4", linetype = "dotted") +

  # 🔸 Texto personalizado: edítalo tú
  annotate("text", x = 0.9, y = 15000, 
           label = "Diatoms: R² = 0.702 p = 0.009", 
           color = "green4", , size = 3, hjust = 0.76,  fontface = "bold") +

  ggtitle("b) Low affinity transport vs PO₄⁻³") +
  labs(x = "PO₄⁻³ (µmol L⁻¹)", y = "nptA (TPM)") +
  theme_bw()+
    theme(text = element_text(size = 10),
        plot.title = element_text(size = 10, face = "bold", hjust = 0.5))

Low_affinity_plot

```




```{r}
library(ggplot2)
library(dplyr)
library(readxl)

# 📥 Cargar datos desde Excel
P_mobilization <- read_excel("../Data Frames/WP2/Correlations.xlsx", sheet = "P_mobilization", col_names = TRUE)

# 🔹 Función para ajustar modelo exponencial y calcular R² y p-valor
ajustar_exponencial <- function(data) {
  fit_exp <- nls(ppA ~ a * exp(b * DIN), data = data, start = list(a = 10, b = 0.5))
  
  # Extraer coeficientes
  coeffs <- coef(fit_exp)
  a_exp <- coeffs["a"]
  b_exp <- coeffs["b"]
  
  # Calcular R² manualmente
  y_pred <- a_exp * exp(b_exp * data$DIN)
  ss_total <- sum((data$ppA - mean(data$ppA))^2)
  ss_residual <- sum((data$ppA - y_pred)^2)
  r2_exp <- 1 - (ss_residual / ss_total)
  
  # Ajuste log-lineal para obtener p-valor
  fit_log <- lm(log(ppA) ~ DIN, data = data)
  summary_log <- summary(fit_log)
  p_value <- summary_log$coefficients[2, 4]

  # 🔹 Aplicar corrección de Good
  p_good <- p_value * sqrt(6 / 100)

  # Generar predicciones para la curva ajustada
  din_seq <- seq(min(data$DIN), max(data$DIN), length.out = 100)
  exp_pred <- data.frame(DIN = din_seq, ppA = a_exp * exp(b_exp * din_seq), Final_Taxonomy = unique(data$Final_Taxonomy))

  return(list(r2 = r2_exp, p_value = p_value, p_good = p_good, pred = exp_pred))
}

# 🔹 Ajustes para cada grupo
# bacteroidota_data <- P_mobilization %>% filter(Final_Taxonomy == "Bacteroidota")
diatom_data <- P_mobilization %>% filter(Final_Taxonomy == "Diatom")

bacteroidota_res <- ajustar_exponencial(bacteroidota_data)
diatom_res <- ajustar_exponencial(diatom_data)

# 🔹 Generar predicciones para cada grupo
exp_pred_all <- bind_rows(bacteroidota_res$pred, diatom_res$pred)

# 🔹 Coordenadas base para alineación y espaciado
base_x <- max(P_mobilization$DIN) * 0.7
base_y <- max(P_mobilization$ppA) * 0.7
line_spacing <- max(P_mobilization$ppA) * 0.15  # Puedes afinarlo visualmente


# 🔹 Crear la gráfica con colores personalizados
P_mobilization_plot <- ggplot() +
  # 🔹 Bacteroidota (puntos y línea)
  # geom_point(data = bacteroidota_data, aes(x = DIN, y = ppA), color = "peachpuff4", size = 3) +
  # geom_line(data = bacteroidota_res$pred, aes(x = DIN, y = ppA), color = "peachpuff4", size = 0.5, linetype = "dashed") +

  # 🔹 Diatoms (puntos y línea)
  geom_point(data = diatom_data, aes(x = DIN, y = ppA), color = "green4", size = 3) +
  geom_line(data = diatom_res$pred, aes(x = DIN, y = ppA), color = "green4", size = 0.5, linetype = "dashed") +

  # 🔹 Anotaciones con R² y p (Good)
  annotate("text", x = 0.5, y = 3000,
           label = "Diatoms:        R² = 0.72   p = 0.008",
           hjust = 0, color = "green4", size = 3, fontface = "bold") +
  
  # annotate("text", x =0.5 , y = 200,
  #          label = "Bacteroidota: R² = 0.76   p = 0.006",
  #          hjust = 0, color = "peachpuff4", size = 3, fontface = "bold")+
  # 📏 Escala logarítmica en Y
  scale_y_log10(breaks = scales::log_breaks(base = 10), labels = scales::comma) +

  # 📌 Títulos y estilos
  ggtitle("c) Internal P mobilization vs DIN") +
  labs(x = "DIN (µmol L⁻¹)", y = "ppA (TPM)") +
  theme_bw() +
  theme(text = element_text(size = 10),
        plot.title = element_text(size = 10, face = "bold", hjust = 0.5))

# 🔹 Mostrar gráfica
P_mobilization_plot

```




```{r}
library(ggplot2)
library(dplyr)
library(readxl)

# 📥 Cargar datos desde Excel
phoA_data <- read_excel("../Data Frames/WP2/Correlations.xlsx", sheet = "Organic_P", col_names = TRUE)

# 🔹 Filtrar datos válidos
phoA_data <- phoA_data %>% filter(phoA > 0, NP > 0)

# 🔹 Función para ajustar modelo lineal y calcular p corregido
ajustar_lineal <- function(data) {
  fit <- lm(phoA ~ NP, data = data)
  coeffs <- coef(fit)
  r2 <- summary(fit)$r.squared
  p_val <- summary(fit)$coefficients[2, 4]
  p_good <- p_val * sqrt(6 / 100)

  # Para línea de predicción
  np_seq <- seq(min(data$NP), max(data$NP), length.out = 100)
  pred <- data.frame(NP = np_seq, phoA = coeffs[1] + coeffs[2] * np_seq, Final_Taxonomy = unique(data$Final_Taxonomy))

  return(list(r2 = r2, p_good = p_good, pred = pred))
}

# 🔹 Separar grupos
pseudomonadales_data <- phoA_data %>% filter(Final_Taxonomy == "Pseudomonadales")
diatom_data <- phoA_data %>% filter(Final_Taxonomy == "Diatom")

# 🔹 Ajustes
pseudomonadales_res <- ajustar_lineal(pseudomonadales_data)
diatom_res <- ajustar_lineal(diatom_data)

# 🔹 Combinar predicciones
pred_all <- bind_rows(pseudomonadales_res$pred, diatom_res$pred)

# 🔹 Gráfica
Organic_P_plot <- ggplot() +
  # Pseudomonadales
  geom_point(data = pseudomonadales_data, aes(x = NP, y = phoA), color = "plum3", size = 3) +
  geom_line(data = pseudomonadales_res$pred, aes(x = NP, y = phoA), color = "plum3", linetype = "dashed", size = 0.5) +

  # Diatoms
  geom_point(data = diatom_data, aes(x = NP, y = phoA), color = "green4", size = 3) +
  geom_line(data = diatom_res$pred, aes(x = NP, y = phoA), color = "green4", linetype = "dashed", size = 0.5) +

  # Anotaciones con R² y p (Good)
  annotate("text", x = 5, y = 1700, 
           label = "Pseudomonadales: R² = 0.483   p = 0.031",
           color = "plum3", size = 3, hjust = 0, fontface = "bold") +
  
  annotate("text", x = 5, y = 2000, 
           label = "Diatoms: R² = 0.560   p = 0.021",
           color = "green4", size = 3, hjust = 0, fontface = "bold") +

  # Título y ejes
  ggtitle("d) Organic P utilization vs N:P") +
  labs(x = "N:P ratio", y = "phoA (TPM)") +
  scale_y_continuous(labels = scales::comma) +
  theme_bw() +
  theme(text = element_text(size = 10),
        plot.title = element_text(size = 10, face = "bold", hjust = 0.5))

# 🔹 Mostrar gráfica
Organic_P_plot

```


```{r}
library(ggplot2)
library(dplyr)
library(readxl)

# 📥 Cargar datos desde Excel
data <- read_excel("../Data Frames/WP2/Correlations.xlsx", sheet = "Organic_p_and_Phosphonate", col_names = TRUE)

# ✅ Renombrar columnas con nombres válidos para R
colnames(data) <- colnames(data) %>% gsub("-", "_", .)

# 🔹 Función para ajustar modelo exponencial y calcular R² y p (Good)
ajustar_exponencial <- function(data, x_var, y_var) {
  data <- data %>% filter(.data[[y_var]] > 0, .data[[x_var]] > 0)
  
  if (nrow(data) < 3) {
    return(list(r2 = NA, p_value = NA, p_good = NA,
                pred = data.frame(PP = data[[x_var]], Value = NA, Variable = y_var)))
  }

  a_start <- max(data[[y_var]], na.rm = TRUE) / 2
  b_start <- coef(lm(log(data[[y_var]]) ~ data[[x_var]]))[2]

  fit_exp <- tryCatch({
    nls(as.formula(paste(y_var, "~ a * exp(b *", x_var, ")")),
        data = data, 
        start = list(a = a_start, b = b_start),
        control = list(minFactor = 1e-10, maxiter = 5000, tol = 1e-6))
  }, error = function(e) return(NULL))
  
  if (is.null(fit_exp)) {
    return(list(r2 = NA, p_value = NA, p_good = NA,
                pred = data.frame(PP = data[[x_var]], Value = NA, Variable = y_var)))
  }

  coeffs <- coef(fit_exp)
  a_exp <- coeffs["a"]
  b_exp <- coeffs["b"]

  y_pred <- a_exp * exp(b_exp * data[[x_var]])
  ss_total <- sum((data[[y_var]] - mean(data[[y_var]]))^2, na.rm = TRUE)
  ss_residual <- sum((data[[y_var]] - y_pred)^2, na.rm = TRUE)
  r2_exp <- 1 - (ss_residual / ss_total)

  fit_log <- lm(log(data[[y_var]]) ~ data[[x_var]])
  summary_log <- summary(fit_log)
  p_value <- summary_log$coefficients[2, 4]
  
  # 🔹 Aplicar corrección de Good
  p_good <- p_value * sqrt(6 / 100)

  x_seq <- seq(min(data[[x_var]], na.rm = TRUE), max(data[[x_var]], na.rm = TRUE), length.out = 100)
  exp_pred <- data.frame(PP = x_seq, Value = a_exp * exp(b_exp * x_seq), Variable = y_var)

  return(list(r2 = r2_exp, p_value = p_value, p_good = p_good, pred = exp_pred))
}

# 🔹 Ajustes para cada grupo de variables
acp5_res <- ajustar_exponencial(data, "PP", "acp5")
pho3_res <- ajustar_exponencial(data, "PP", "pho_3")
phoA_res <- ajustar_exponencial(data, "PP", "phoA")
pepM_res <- ajustar_exponencial(data, "PP", "pepM")

# 🔹 Predicciones
exp_pred_all <- bind_rows(acp5_res$pred, pho3_res$pred, phoA_res$pred, pepM_res$pred)

base_x <- max(data$PP) * 0.6
base_y <- max(data$acp5, na.rm = TRUE) * 0.98
line_spacing <- 80  # Ajusta esto según cómo se vea en tu escala

# 🔹 Crear gráfica
Organic_P_Phosphonate_plot <- ggplot() +
  geom_point(data = data, aes(x = PP, y = acp5), color = "royalblue4", size = 3) +
  geom_line(data = acp5_res$pred, aes(x = PP, y = Value), color = "royalblue4", linetype = "dashed") +

  geom_point(data = data, aes(x = PP, y = pho_3), color = "royalblue2", size = 3) +
  geom_line(data = pho3_res$pred, aes(x = PP, y = Value), color = "royalblue2", linetype = "dashed") +

  geom_point(data = data, aes(x = PP, y = phoA), color = "lightskyblue4", size = 3) +
  geom_line(data = phoA_res$pred, aes(x = PP, y = Value), color = "lightskyblue4", linetype = "dashed") +
  
  geom_point(data = data, aes(x = PP, y = pepM), color = "lightskyblue3", size = 3) +
  geom_line(data = pepM_res$pred, aes(x = PP, y = Value), color = "lightskyblue3", linetype = "dashed") +


  annotate("text", x = base_x, y = base_y, 
           label = "Dinoflagellates:", hjust = 0, fontface = "bold", color = "black", size = 3.2) +
  
  annotate("text", x = base_x, y = base_y - line_spacing * 1, 
           label = "acp5:   R² = 0.942   p = 0.001", hjust = 0, color = "royalblue4", fontface = "bold", size = 3) +
  
  annotate("text", x = base_x, y = base_y - line_spacing * 2, 
           label = "pho-3: R² = 0.920   p = 0.001", hjust = 0, color = "royalblue2", fontface = "bold", size = 3) +
  
  annotate("text", x = base_x, y = base_y - line_spacing * 3, 
           label = "phoA:  R² = 0.775   p = 0.005", hjust = 0, color = "lightskyblue4", fontface = "bold", size = 3) +
  
  annotate("text", x = base_x, y = base_y - line_spacing * 4, 
           label = "pepM: R² = 0.806   p = 0.004", hjust = 0, color = "lightskyblue3", fontface = "bold", size = 3)+

  
  scale_y_continuous(labels = scales::comma) +  
  ggtitle("e) Organic P and phosphonate utilization vs PP") +
  labs(x = "Primary production (µgC L⁻¹ h⁻¹)", y = "(TPM)") +
  theme_bw() +
  theme(text = element_text(size = 10),
        plot.title = element_text(size = 10, face = "bold", hjust = 0.5))

# 🔥 Mostrar la gráfica
Organic_P_Phosphonate_plot

```



```{r}
library(ggplot2)
library(dplyr)
library(readxl)

# 📥 Cargar datos desde Excel
datazz <- read_excel("../Data Frames/WP2/Correlations.xlsx", sheet = "Phosphonate", col_names = TRUE)

# 🔹 Filtrar valores válidos
data <- datazz %>% filter(phnC > 0, PP > 0)

# 🔹 Ajuste lineal + p corregido
ajustar_lineal <- function(data, x_var, y_var) {
  fit <- lm(as.formula(paste(y_var, "~", x_var)), data = data)
  coeffs <- coef(fit)
  r2 <- summary(fit)$r.squared
  p_val <- summary(fit)$coefficients[2, 4]
  p_good <- p_val * sqrt(6 / 100)

  # Predicciones para línea
  x_seq <- seq(min(data[[x_var]]), max(data[[x_var]]), length.out = 100)
  pred <- data.frame(PP = x_seq, Value = coeffs[1] + coeffs[2] * x_seq)

  return(list(r2 = r2, p_good = p_good, pred = pred))
}

# 🔹 Ajustar phnC vs PP
phnC_res <- ajustar_lineal(data, "PP", "phnC")

# 🔹 Gráfica
Phosphonate_plot <- ggplot() +
  geom_point(data = data, aes(x = PP, y = phnC), color = "deepskyblue4", size = 3) +
  geom_line(data = phnC_res$pred, aes(x = PP, y = Value), color = "deepskyblue4", linetype = "dotted") +

  # 🔹 Texto con R² y p (Good)
  annotate("text", x = max(data$PP) * 0.75, y = max(data$phnC, na.rm = TRUE) * 0.9, 
           label = sprintf("Rhodobacterales: R² = %.3f  p = %.3f", 
                           phnC_res$r2, phnC_res$p_good),
           color = "deepskyblue4", size = 3, hjust = 0.65, fontface = "bold") +

  # 🎨 Estilo
  scale_y_continuous(labels = scales::comma) +
  ggtitle("f) Phosphonate utilization vs PP") +
  labs(x = "Primary production (µgC L⁻¹ h⁻¹)", y = "phnC (TPM)") +
  theme_bw() +
  theme(text = element_text(size = 10),
        plot.title = element_text(size = 10, face = "bold", hjust = 0.5))

# 🔥 Mostrar gráfica
Phosphonate_plot

```


```{r, fig.height=15, fig.width=15'}
# 📚 Cargar la librería patchwork
library(patchwork)

# 📌 Unir las cuatro gráficas en dos columnas
combined_plot <- (High_affinity_plot | Low_affinity_plot) / 
                 (P_mobilization_plot | Organic_P_plot) / 
                 (Organic_P_Phosphonate_plot | Phosphonate_plot)




# 💾 Guardar
png("../Results/WP2/Figure_6.png",
    width = 18, height = 24, units = 'cm', res=600 )

# Mostrar el gráfico combinado
combined_plot

# Imprime el gráfico final
print(combined_plot)

# Cierra el dispositivo de gráficos
dev.off()
combined_plot
```

```{r, fig.height=7, fig.width=7}

counts_raw_1 <- read_parquet("../Data Frames/WP2/INTERES_Prok_WP2_TPMs_Domain_Annotated.parquet")

my.colors_All <- c("Bacteria" = "purple2", "Archaea"  = "darkorange2","No domain"  = "grey33")


MetaTs_compleat_datasetr_plot <- ggplot(counts_raw_1, aes(y=tpm, x=treatment, fill=Domain)) + # fill=Our_Taxonomy
    geom_bar(position="fill", stat="identity") + #, color ="black"
  # geom_text(aes(label = Final_Taxonomy), position = position_fill(vjust = 0.5)) + # Agregar esta línea
  ggtitle ("Prokariotic metatranscriptome")+
    labs(x="", y="", fill="", col="") +
    theme_bw(base_size = 8) +
  theme(plot.title = element_text(size = 10, face = "bold", hjust = 0.5),
        plot.subtitle  = element_text(size = 8, hjust = 0), 
        plot.caption = element_text(size = 8, hjust = 0, vjust = 0),
        axis.title.y = element_blank(),
        axis.title.x = element_text(angle = 0, vjust = 0.5, face = "bold"),
        axis.text.x = element_text(angle = 0, vjust = 0.5, hjust = 0.5, size=8, face = "bold"),
        axis.text.y = element_text(angle = 0, vjust = 0.5, hjust = 0.5, size=8, face = "bold"),
        strip.text = element_text(size = 8), 
        strip.text.x = element_text(size=8, angle=0, face = "bold"),
        strip.text.y = element_text(size=8, angle=270, face = "bold"),
        strip.background = element_rect(colour="black", fill="white"),
        legend.text = element_text(size = 9), # Incrementar el tamaño del texto de la leyenda
        legend.position = "none",
        legend.box = "horizontal",
        legend.margin = margin(t = -1, r = 0, b = 0, l = 0, unit = "cm"),
        legend.box.margin = margin(t = 0, r = 0, b = 0, l = 0, unit = "cm"),
        legend.spacing = unit(0.05, "cm"),
    legend.key.size = unit(0.2, "cm"),  # Ajuste general del tamaño del recuadro
    legend.key.height = unit(0.2, "cm"),  # Ajuste del tamaño de altura del recuadro
    legend.key.width = unit(0.3, "cm"), 
        legend.title = element_blank()) +
      guides(fill = guide_legend(nrow = 41)) +
      scale_fill_manual(values = my.colors_All) +
scale_y_continuous(breaks = seq(0, 1, 0.25), labels = scales::percent)+
facet_nested( ~ time, scales = "free")+
  theme(panel.spacing = unit(0.2, "lines"))

MetaTs_compleat_datasetr_plot


# ggsave("../Results/WP1/Supplementary/Supplementary_Figure_1.png",
#        width = 18, # anchura
#        height = 18, # altura
#        units = "cm",
#        dpi = 600)

```

```{r, fig.height=7, fig.width=7}
polyA_counts_raw_1 <- read_parquet("../Data Frames/WP2/INTERES_Euk_WP2_TPMs_Domain_Annotated.parquet")

my.colors_All <- c("Bacteria" = "purple2", "Archaea"  = "darkorange2", "Eukaryota"  = "darkgreen",
                          "No domain"  = "grey33")


PolyA_MetaTs_compleat_datasetr_plot <- ggplot(polyA_counts_raw_1, aes(y=tpm, x=treatment, fill=Domain)) + # fill=Our_Taxonomy
    geom_bar(position="fill", stat="identity") + #, color ="black"
  # geom_text(aes(label = Final_Taxonomy), position = position_fill(vjust = 0.5)) + # Agregar esta línea
  ggtitle ("Eukariotic metatranscriptome")+
    labs(x="", y="", fill="", col="") +
    theme_bw(base_size = 8) +
  theme(plot.title = element_text(size = 10, face = "bold", hjust = 0.5),
        plot.subtitle  = element_text(size = 8, hjust = 0), 
        plot.caption = element_text(size = 8, hjust = 0, vjust = 0),
        axis.title.y = element_blank(),
        axis.title.x = element_text(angle = 0, vjust = 0.5, face = "bold"),
        axis.text.x = element_text(angle = 0, vjust = 0.5, hjust = 0.5, size=8, face = "bold"),
        axis.text.y = element_text(angle = 0, vjust = 0.5, hjust = 0.5, size=8, face = "bold"),
        strip.text = element_text(size = 8), 
        strip.text.x = element_text(size=8, angle=0, face = "bold"),
        strip.text.y = element_text(size=8, angle=270, face = "bold"),
        strip.background = element_rect(colour="black", fill="white"),
        legend.text = element_text(size = 9), # Incrementar el tamaño del texto de la leyenda
        legend.position = "none",
        legend.box = "horizontal",
        legend.margin = margin(t = -1, r = 0, b = 0, l = 0, unit = "cm"),
        legend.box.margin = margin(t = 0, r = 0, b = 0, l = 0, unit = "cm"),
        legend.spacing = unit(0.05, "cm"),
    legend.key.size = unit(0.2, "cm"),  # Ajuste general del tamaño del recuadro
    legend.key.height = unit(0.2, "cm"),  # Ajuste del tamaño de altura del recuadro
    legend.key.width = unit(0.3, "cm"), 
        legend.title = element_blank()) +
      guides(fill = guide_legend(nrow = 41)) +
        scale_fill_manual(values = my.colors_All) +
scale_y_continuous(breaks = seq(0, 1, 0.25), labels = scales::percent)+
  facet_nested( ~ time, scales = "free")+
  theme(panel.spacing = unit(0.2, "lines"))

PolyA_MetaTs_compleat_datasetr_plot


# ggsave("../Results/WP1/Supplementary/Supplementary_Figure_1.png",
#        width = 18, # anchura
#        height = 18, # altura
#        units = "cm",
#        dpi = 600)

```

```{r}
# Cargar librería
library(ggplot2)

# Paleta de colores
my.colors <- c(
  "Bacteria" = "purple2",
  "Archaea" = "darkorange2",
  "Eukaryota" = "darkgreen",
  "No domain" = "grey33"
)

# Dataset para que cada barra represente una categoría
dummy_data <- data.frame(
  Domain = factor(c("Bacteria", "Archaea", "Eukaryota", "No domain"),
                  levels = c("Bacteria", "Archaea", "Eukaryota", "No domain")),
  value = rep(1, 4)
)

# Crear gráfico con barras bajas y leyenda visible arriba
ggplot(dummy_data, aes(x = Domain, y = value, fill = Domain)) +
  geom_bar(stat = "identity", width = 0.0001) +  # barras mínimas
  scale_fill_manual(values = my.colors) +
  theme_void() +
  theme(
    legend.position = "top",
    legend.direction = "horizontal",
    legend.title = element_blank(),
    legend.text = element_text(size = 12),
    legend.key.height = unit(0.4, "cm"),
    legend.key.width = unit(0.8, "cm"),
    plot.margin = margin(1, 1, 1, 1, unit = "cm")
  )


```




```{r}
library(ggplot2)
library(patchwork)
library(grid)  # Para usar textGrob

# 🎨 Colores
my.colors <- c(
  "Bacteria" = "purple2",
  "Archaea" = "darkorange2",
  "Eukaryota" = "darkgreen",
  "No domain" = "grey33"
)

# 📊 Gráfico de leyenda
legend_plot <- ggplot(data.frame(Domain = names(my.colors), value = 1),
                      aes(x = Domain, y = value, fill = Domain)) +
  geom_bar(stat = "identity", width = 0.0001) +
  scale_fill_manual(values = my.colors) +
  theme_void() +
  theme(
    legend.position = "top",
    legend.direction = "horizontal",
    legend.title = element_blank(),
    legend.text = element_text(size = 10),
    legend.key.height = unit(0.4, "cm"),
    legend.key.width = unit(0.8, "cm")
  )

# 🧪 Eliminar leyenda de los plots principales
MetaTs_compleat_datasetr_plot <- MetaTs_compleat_datasetr_plot +
  theme(legend.position = "none")

PolyA_MetaTs_compleat_datasetr_plot <- PolyA_MetaTs_compleat_datasetr_plot +
  theme(legend.position = "none")

# 🧩 Componer: título + gráficas + leyenda al fondo
combined_plot <- wrap_elements(full = textGrob("Taxonomic assignment of:",
                                               gp = gpar(fontsize = 13, fontface = "bold"))) /
                 (MetaTs_compleat_datasetr_plot | PolyA_MetaTs_compleat_datasetr_plot) /
                 legend_plot +
  plot_layout(heights = c(0.06, 0.85, 0.002))  # proporciones ajustadas

# 💾 Guardar
png("../Results/WP2/Supplementary/Supplementary_Figure_1.png",
    width = 18, height = 14, units = 'cm', res = 600)

print(combined_plot)
dev.off()


```


